---
permalink: audit/common-elements-in-audit-messages.html 
sidebar: sidebar 
keywords: storagegrid, audit, messages, message, common elements, AMID, ANID, ASES, ASQN, ATID, ATIM, ATYP, AVER, RSLT 
summary: 所有审计消息都包含共同的元素。 
---
= 审计消息中的常见元素
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所有审计消息都包含共同的元素。

[cols="1a,1a,4a"]
|===
| 代码 | 类型 | 描述 


 a| 
之中
 a| 
FC32
 a| 
模块 ID：生成消息的模块 ID 的四个字符标识符。这表示生成审计消息的代码段。



 a| 
安尼德
 a| 
UI32
 a| 
节点 ID：分配给生成消息的服务的网格节点 ID。在配置和安装StorageGRID系统时，每个服务都会分配一个唯一的标识符。此 ID 无法更改。



 a| 
东南大学
 a| 
UI64
 a| 
审计会话标识符：在以前的版本中，此元素指示服务启动后审计系统初始化的时间。该时间值以操作系统纪元（1970 年 1 月 1 日 00:00:00 UTC）以来的微秒为单位进行测量。

*注意：*此元素已过时，不再出现在审计消息中。



 a| 
美国质量协会
 a| 
UI64
 a| 
序列计数：在以前的版本中，此计数器会随着网格节点（ANID）上生成的每个审计消息而递增，并在服务重启时重置为零。

*注意：*此元素已过时，不再出现在审计消息中。



 a| 
急性胰腺炎
 a| 
UI64
 a| 
跟踪 ID：由单个事件触发的一组消息共享的标识符。



 a| 
ATIM
 a| 
UI64
 a| 
时间戳：触发审计消息的事件的生成时间，以自操作系统纪元（1970 年 1 月 1 日 00:00:00 UTC）以来的微秒为单位。请注意，大多数用于将时间戳转换为本地日期和时间的工具都是基于毫秒的。

可能需要对记录的时间戳进行四舍五入或截断。审计消息开头出现的可读时间 `audit.log`文件是 ISO 8601 格式的 ATIM 属性。日期和时间表示为 `_YYYY-MMDDTHH:MM:SS.UUUUUU_`，其中 `T`是一个文字字符串字符，表示日期时间段的开始。 `_UUUUUU_`是微秒。



 a| 
典型蛋白
 a| 
FC32
 a| 
事件类型：正在记录的事件的四个字符的标识符。这决定了消息的“有效负载”内容：所包含的属性。



 a| 
断言
 a| 
UI32
 a| 
版本：审计消息的版本。随着StorageGRID软件的发展，新版本的服务可能会在审计报告中加入新功能。该字段使 AMS 服务能够向后兼容，以处理来自旧版本服务的消息。



 a| 
放射学研究实验室
 a| 
FC32
 a| 
结果：事件、过程或交易的结果。如果与消息无关，则使用 NONE 而不是 SUCS，以免意外过滤消息。

|===