---
permalink: audit/idel-ilm-initiated-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, IDEL, ILM Initiated Delete 
summary: 当 ILM 启动删除对象的过程时会生成此消息。 
---
= IDEL：ILM 发起的删除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 ILM 启动删除对象的过程时会生成此消息。

IDEL 消息在以下任一情况下生成：

* *对于兼容 S3 存储桶中的对象*：当 ILM 启动自动删除对象的过程时会生成此消息，因为该对象的保留期已过期（假设自动删除设置已启用且合法保留已关闭）。
* *对于不合规的 S3 存储桶中的对象*。当 ILM 开始删除对象的过程时会生成此消息，因为活动 ILM 策略中当前没有适用于该对象的放置指令。


[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 描述 


 a| 
中央商务区
 a| 
内容块标识符
 a| 
对象的 CBID。



 a| 
CMPA
 a| 
合规性：自动删除
 a| 
仅适用于兼容 S3 存储桶中的对象。  0（false）或 1（true），指示合规对象在其保留期结束时是否应自动删除，除非存储桶处于合法保留状态。



 a| 
CMPL
 a| 
合规性：合法保留
 a| 
仅适用于兼容 S3 存储桶中的对象。  0（假）或 1（真），表示存储桶当前是否处于合法保留之下。



 a| 
CMPR
 a| 
合规性：保留期
 a| 
仅适用于兼容 S3 存储桶中的对象。对象的保留期限（以分钟为单位）。



 a| 
计算机辅助制造
 a| 
合规性：摄取时间
 a| 
仅适用于兼容 S3 存储桶中的对象。对象的摄取时间。您可以将保留期（分钟）添加到此值，以确定何时可以从存储桶中删除对象。



 a| 
DMRK
 a| 
删除标记版本 ID
 a| 
从版本控制的存储桶中删除对象时创建的删除标记的版本 ID。对 bucket 的操作不包含该字段。



 a| 
CSIZ
 a| 
内容大小
 a| 
对象的大小（以字节为单位）。



 a| 
本地控制
 a| 
位置
 a| 
StorageGRID系统内对象数据的存储位置。如果对象没有位置（例如，已被删除），则 LOCS 的值为“”。

CLEC：对于擦除编码对象，应用于对象数据的擦除编码配置文件 ID 和擦除编码组 ID。

CLDI：对于复制的对象，LDR 节点 ID 和对象位置的卷 ID。

CLNL：如果对象数据已存档，则为对象位置的 ARC 节点 ID。



 a| 
路径
 a| 
S3 存储桶/密钥
 a| 
S3 存储桶名称和 S3 密钥名称。



 a| 
放射学研究实验室
 a| 
结果
 a| 
ILM 操作的结果。

SUCS：ILM 操作成功。



 a| 
规则
 a| 
规则标签
 a| 
* 如果兼容 S3 存储桶中的对象由于其保留期已过期而被自动删除，则此字段为空白。
* 如果由于没有更多当前适用于该对象的放置指令而导致对象被删除，则此字段将显示适用于该对象的最后一条 ILM 规则的可读标签。




 a| 
SGRP
 a| 
站点（组）
 a| 
如果存在，则表示该对象已在指定站点被删除，但该站点不是该对象被摄取的站点。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
StorageGRID系统内对象的标识符。



 a| 
垂直集成式
 a| 
版本 ID
 a| 
已删除对象的特定版本的版本 ID。对存储桶和未版本控制的存储桶中的对象的操作不包含此字段。

|===