---
permalink: audit/lkdm-leaked-object-cleanup.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, LKDM, Leaked Object Cleanup 
summary:  
---
= LKDM：泄漏对象清理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当泄漏的块已被清理或删除时，会生成此消息。块可以是复制对象或擦除编码对象的一部分。

[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 描述 


 a| 
克洛奇
 a| 
区块位置
 a| 
已删除的泄露块的文件路径。



 a| 
CTYP
 a| 
块类型
 a| 
块类型：

`ec: Erasure-coded object chunk`

`repl: Replicated object chunk`



 a| 
长期典型
 a| 
泄漏类型
 a| 
可以检测到的五种泄漏类型：

`object_leaked: Object doesn’t exist in the grid`

`location_leaked: Object exists in the grid, but found location doesn’t belong to object`

`mup_seg_leaked: Multipart upload was stopped or not completed, and the segment/part was left out`

`segment_leaked: Parent UUID/CBID (associated container object) is valid but doesn't contain this segment`

`no_parent: Container object is deleted, but object segment was left out and not deleted`



 a| 
计算机辅助制造技术研究所
 a| 
块创建时间
 a| 
泄漏块的创建时间。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
块所属对象的标识符。



 a| 
中央商务区
 a| 
内容块标识符
 a| 
泄漏的块所属对象的 CBID。



 a| 
CSIZ
 a| 
内容大小
 a| 
块的大小（以字节为单位）。

|===