---
permalink: audit/s3-select-request.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, S3SL, S3 Select request 
summary: 此消息表明用户启动了 S3 Select 作业。 
---
= S3SL：S3 选择请求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3 Select 请求返回给客户端后，此消息记录完成。 S3SL 消息可以包含错误消息和错误代码详细信息。请求可能未成功。

[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 描述 


 a| 
比萨中心
 a| 
已扫描字节数
 a| 
从存储节点扫描（接收）的字节数。

如果物体被压缩，BYSC 和 BYPR 可能会有所不同。如果对象被压缩，BYSC 将具有压缩后的字节数，而 BYPR 将具有解压缩后的字节数。



 a| 
BYPR
 a| 
已处理字节数
 a| 
处理的字节数。指示 S3 Select 作业实际处理或操作的“已扫描字节数”的字节数。



 a| 
拜耳
 a| 
返回的字节数
 a| 
S3 Select 作业返回给客户端的字节数。



 a| 
雷普尔
 a| 
已处理的记录
 a| 
S3 Select 作业从存储节点接收的记录数或行数。



 a| 
远程放射治疗
 a| 
已返回的记录
 a| 
S3 Select 作业返回给客户端的记录数或行数。



 a| 
乔菲
 a| 
工作完成
 a| 
指示 S3 Select 作业是否已完成处理。如果为假，则作业无法完成，并且错误字段中可能会包含数据。客户端可能收到了部分结果，或者根本没有收到结果。



 a| 
里德
 a| 
请求 ID
 a| 
S3 Select 请求的标识符。



 a| 
扩展
 a| 
执行时间
 a| 
S3 选择作业完成所需的时间（以秒为单位）。



 a| 
急性呼吸机管理组
 a| 
错误消息
 a| 
S3 Select 作业生成的错误消息。



 a| 
ERTY
 a| 
错误类型
 a| 
S3 Select 作业生成的错误类型。



 a| 
ERST
 a| 
错误堆栈跟踪
 a| 
S3 Select 作业生成的错误堆栈跟踪。



 a| 
S3BK
 a| 
S3 存储分段
 a| 
S3 存储桶名称。



 a| 
S3AK
 a| 
S3 访问密钥 ID（请求发送者）
 a| 
发送请求的用户的 S3 访问密钥 ID。



 a| 
S3AI
 a| 
S3 租户帐户 ID（请求发送者）
 a| 
发送请求的用户的租户帐户 ID。



 a| 
S3KY
 a| 
S3 键
 a| 
S3 密钥名称，不包括存储桶名称。

|===