---
permalink: audit/sdel-s3-delete.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SDEL, S3 DELETE 
summary: 当 S3 客户端发出 DELETE 事务时，会发出删除指定对象或存储桶的请求。如果交易成功，服务器将发出此消息。 
---
= SDEL：S3 删除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 S3 客户端发出 DELETE 事务时，会发出删除指定对象或存储桶，或删除存储桶/对象子资源的请求。如果交易成功，服务器将发出此消息。

[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 描述 


 a| 
中央商务区
 a| 
内容块标识符
 a| 
所请求内容块的唯一标识符。如果 CBID 未知，则该字段设置为 0。对 bucket 的操作不包含该字段。



 a| 
数控机床
 a| 
一致性控制头
 a| 
如果请求中存在 Consistency-Control HTTP 请求标头的值。



 a| 
全国药品信息中心
 a| 
连接标识符
 a| 
TCP/IP 连接的唯一系统标识符。



 a| 
CSIZ
 a| 
内容大小
 a| 
已删除对象的大小（以字节为单位）。对 bucket 的操作不包含该字段。



 a| 
DMRK
 a| 
删除标记版本 ID
 a| 
从版本控制的存储桶中删除对象时创建的删除标记的版本 ID。对 bucket 的操作不包含该字段。



 a| 
全球互联网信息办公室
 a| 
电网联盟连接ID
 a| 
与跨网格复制删除请求关联的网格联合连接的连接 ID。仅包含在目标网格上的审计日志中。



 a| 
GFSA
 a| 
电网联盟源账户ID
 a| 
跨网格复制删除请求的源网格上租户的帐户 ID。仅包含在目标网格上的审计日志中。



 a| 
HTRH
 a| 
HTTP 请求标头
 a| 
配置期间选择的已记录 HTTP 请求标头名称和值的列表。

 `X-Forwarded-For`如果请求中存在，则会自动包含在内，并且 `X-Forwarded-For`值与请求发送者IP地址（SAIP审计字段）不同。

`x-amz-bypass-governance-retention`如果请求中存在，则会自动包含在内。



 a| 
移动式微电子
 a| 
上次修改时间
 a| 
Unix 时间戳（以微秒为单位），指示对象最后修改的时间。



 a| 
放射学研究实验室
 a| 
结果代码
 a| 
DELETE 事务的结果。结果总是：

SUCS：成功



 a| 
S3AI
 a| 
S3 租户帐户 ID（请求发送者）
 a| 
发送请求的用户的租户帐户 ID。空值表示匿名访问。



 a| 
S3AK
 a| 
S3 访问密钥 ID（请求发送者）
 a| 
发送请求的用户的哈希 S3 访问密钥 ID。空值表示匿名访问。



 a| 
S3BK
 a| 
S3 存储桶
 a| 
S3 存储桶名称。



 a| 
S3KY
 a| 
S3 键
 a| 
S3 密钥名称，不包括存储桶名称。对 bucket 的操作不包含该字段。



 a| 
S3SR
 a| 
S3 子资源
 a| 
正在操作的存储桶或对象子资源（如果适用）。



 a| 
南卡罗来纳大学
 a| 
S3 租户帐户名称（请求发送者）
 a| 
发送请求的用户的租户帐户的名称。对于匿名请求则为空。



 a| 
萨伊普
 a| 
IP地址（请求发送者）
 a| 
发出请求的客户端应用程序的 IP 地址。



 a| 
SBAC
 a| 
S3 租户帐户名称（存储桶所有者）
 a| 
存储桶所有者的租户帐户名称。用于识别跨账户或匿名访问。



 a| 
SBAI
 a| 
S3 租户帐户 ID（存储桶所有者）
 a| 
目标Bucket拥有者的租户账户ID。用于识别跨账户或匿名访问。



 a| 
SGRP
 a| 
站点（组）
 a| 
如果存在，则表示该对象已在指定站点被删除，但该站点不是该对象被摄取的站点。



 a| 
SUSR
 a| 
S3 用户 URN（请求发送者）
 a| 
租户帐户 ID 和发出请求的用户的用户名。用户可以是本地用户或 LDAP 用户。例如：  `urn:sgws:identity::03393893651506583485:root`

对于匿名请求则为空。



 a| 
时间
 a| 
时间
 a| 
请求的总处理时间（以微秒为单位）。



 a| 
TLIP
 a| 
受信任的负载均衡器 IP 地址
 a| 
如果请求由受信任的第 7 层负载均衡器路由，则为负载均衡器的 IP 地址。



 a| 
联合城市发展委员会
 a| 
删除标记的通用唯一标识符
 a| 
删除标记的标识符。审计日志消息指定 UUDM 或 UUID，其中 UUDM 表示由于对象删除请求而创建的删除标记，而 UUID 表示对象。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
StorageGRID系统内对象的标识符。



 a| 
垂直集成式
 a| 
版本 ID
 a| 
已删除对象的特定版本的版本 ID。对存储桶和未版本控制的存储桶中的对象的操作不包含此字段。

|===