---
permalink: audit/supd-s3-metadata-updated.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, SUPD, S3 Metadata Updated 
summary: 当 S3 客户端更新所摄取对象的元数据时，S3 API 会生成此消息。如果元数据更新成功，服务器将发出该消息。 
---
= SUPD：S3 元数据已更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 S3 客户端更新所摄取对象的元数据时，S3 API 会生成此消息。如果元数据更新成功，服务器将发出该消息。

[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 描述 


 a| 
中央商务区
 a| 
内容块标识符
 a| 
所请求内容块的唯一标识符。如果 CBID 未知，则该字段设置为 0。对 bucket 的操作不包含该字段。



 a| 
数控机床
 a| 
一致性控制头
 a| 
更新存储桶的合规性设置时，Consistency-Control HTTP 请求标头的值（如果存在于请求中）。



 a| 
全国药品信息中心
 a| 
连接标识符
 a| 
TCP/IP 连接的唯一系统标识符。



 a| 
CSIZ
 a| 
内容大小
 a| 
检索到的对象的大小（以字节为单位）。对 bucket 的操作不包含该字段。



 a| 
HTRH
 a| 
HTTP 请求标头
 a| 
配置期间选择的已记录 HTTP 请求标头名称和值的列表。

 `X-Forwarded-For`如果请求中存在，则会自动包含在内，并且 `X-Forwarded-For`值与请求发送者IP地址（SAIP审计字段）不同。



 a| 
放射学研究实验室
 a| 
结果代码
 a| 
GET 事务的结果。结果总是：

SUCS：成功



 a| 
S3AI
 a| 
S3 租户帐户 ID（请求发送者）
 a| 
发送请求的用户的租户帐户 ID。空值表示匿名访问。



 a| 
S3AK
 a| 
S3 访问密钥 ID（请求发送者）
 a| 
发送请求的用户的哈希 S3 访问密钥 ID。空值表示匿名访问。



 a| 
S3BK
 a| 
S3 存储桶
 a| 
S3 存储桶名称。



 a| 
S3KY
 a| 
S3 键
 a| 
S3 密钥名称，不包括存储桶名称。对 bucket 的操作不包含该字段。



 a| 
南卡罗来纳大学
 a| 
S3 租户帐户名称（请求发送者）
 a| 
发送请求的用户的租户帐户的名称。对于匿名请求则为空。



 a| 
萨伊普
 a| 
IP地址（请求发送者）
 a| 
发出请求的客户端应用程序的 IP 地址。



 a| 
SBAC
 a| 
S3 租户帐户名称（存储桶所有者）
 a| 
存储桶所有者的租户帐户名称。用于识别跨账户或匿名访问。



 a| 
SBAI
 a| 
S3 租户帐户 ID（存储桶所有者）
 a| 
目标Bucket拥有者的租户账户ID。用于识别跨账户或匿名访问。



 a| 
SUSR
 a| 
S3 用户 URN（请求发送者）
 a| 
租户帐户 ID 和发出请求的用户的用户名。用户可以是本地用户或 LDAP 用户。例如：  `urn:sgws:identity::03393893651506583485:root`

对于匿名请求则为空。



 a| 
时间
 a| 
时间
 a| 
请求的总处理时间（以微秒为单位）。



 a| 
TLIP
 a| 
受信任的负载均衡器 IP 地址
 a| 
如果请求由受信任的第 7 层负载均衡器路由，则为负载均衡器的 IP 地址。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
StorageGRID系统内对象的标识符。



 a| 
垂直集成式
 a| 
版本 ID
 a| 
已更新元数据的对象的特定版本的版本 ID。对存储桶和未版本控制的存储桶中的对象的操作不包含此字段。

|===