---
permalink: audit/whea-swift-head.html 
sidebar: sidebar 
keywords: storagegrid, audit, message, WHEA, Swift HEAD 
summary: 当 Swift 客户端发出 HEAD 交易时，会发出请求来检查帐户、容器或对象是否存在，并检索任何相关的元数据。如果交易成功，服务器将发出此消息。 
---
= WHEA：Swift HEAD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 Swift 客户端发出 HEAD 交易时，会发出请求来检查帐户、容器或对象是否存在，并检索任何相关的元数据。如果交易成功，服务器将发出此消息。

[cols="1a,1a,4a"]
|===
| 代码 | 字段 | 描述 


 a| 
中央商务区
 a| 
内容块标识符
 a| 
所请求内容块的唯一标识符。如果 CBID 未知，则该字段设置为 0。对账户和容器的操作不包含此字段。



 a| 
CSIZ
 a| 
内容大小
 a| 
检索到的对象的大小（以字节为单位）。对账户和容器的操作不包含此字段。



 a| 
HTRH
 a| 
HTTP 请求标头
 a| 
配置期间选择的已记录 HTTP 请求标头名称和值的列表。

 `X-Forwarded-For`如果请求中存在，则会自动包含在内，并且 `X-Forwarded-For`值与请求发送者IP地址（SAIP审计字段）不同。



 a| 
放射学研究实验室
 a| 
结果代码
 a| 
HEAD 事务的结果。结果总是：

SUCS：成功



 a| 
萨伊普
 a| 
请求客户端的 IP 地址
 a| 
发出请求的客户端应用程序的 IP 地址。



 a| 
时间
 a| 
时间
 a| 
请求的总处理时间（以微秒为单位）。



 a| 
TLIP
 a| 
受信任的负载均衡器 IP 地址
 a| 
如果请求由受信任的第 7 层负载均衡器路由，则为负载均衡器的 IP 地址。



 a| 
UUID
 a| 
通用唯一标识符
 a| 
StorageGRID系统内对象的标识符。



 a| 
加权平均资本成本
 a| 
Swift 账户 ID
 a| 
StorageGRID系统指定的唯一帐户 ID。



 a| 
WCON
 a| 
Swift 容器
 a| 
Swift 容器名称。对账户的操作不包含此字段。



 a| 
沃本杰明
 a| 
Swift 对象
 a| 
Swift 对象标识符。对账户和容器的操作不包含此字段。



 a| 
乌苏拉
 a| 
Swift 账户用户
 a| 
唯一标识执行交易的客户的 Swift 帐户用户名。

|===