---
permalink: upgrade/estimating-time-to-complete-upgrade.html 
sidebar: sidebar 
keywords: upgrade, time estimate, duration, cassandra upgrade 
summary: 根据升级可能需要的时间考虑何时升级。请注意在升级的每个阶段可以执行和不能执行的操作。 
---
= 估计完成升级的时间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据升级可能需要的时间考虑何时升级。请注意在升级的每个阶段可以执行和不能执行的操作。

.关于此任务
完成StorageGRID升级所需的时间取决于多种因素，例如客户端负载和硬件性能。

该表总结了主要的升级任务并列出了每个任务所需的大约时间。表格后面的步骤提供了可用于估计系统升级时间的说明。

[cols="1a,2a,2a,4a"]
|===
| 升级任务 | 描述 | 大约需要的时间 | 在此任务期间 


 a| 
运行预检查并升级主管理节点
 a| 
运行升级预检查，并停止、升级和重新启动主管理节点。
 a| 
30 分钟到 1 小时，其中服务设备节点需要的时间最多。

未解决的预检错误这次将会增加。
 a| 
您无法访问主管理节点。可能会报告连接错误，您可以忽略。

在开始升级之前运行升级预检查可让您在计划的升级维护时段之前解决任何错误。



 a| 
启动升级服务
 a| 
软件文件分发完毕，启动升级服务。
 a| 
每个网格节点 3 分钟
 a| 



 a| 
升级其他网格节点
 a| 
所有其他网格节点上的软件都将按照您批准节点的顺序进行升级。系统中的每个节点将一次关闭一个。
 a| 
每个节点 15 分钟到 1 小时，其中设备节点需要的时间最长

*注意*：对于设备节点， StorageGRID设备安装程序会自动更新到最新版本。
 a| 
* 不要改变网格配置。
* 不要更改审计级别配置。
* 不要更新 ILM 配置。
* 您无法执行其他维护程序，例如修补程序、退役或扩展。


*注意*：如果您需要执行恢复，请联系技术支持。



 a| 
启用功能
 a| 
新版本的新功能已启用。
 a| 
不到5分钟
 a| 
* 不要改变网格配置。
* 不要更改审计级别配置。
* 不要更新 ILM 配置。
* 您无法执行其他维护程序。




 a| 
升级数据库
 a| 
升级过程会检查每个节点以验证 Cassandra 数据库不需要更新。
 a| 
每个节点 10 秒或整个网格几分钟
 a| 
从StorageGRID 11.8 升级到 11.9 不需要升级 Cassandra 数据库；但是，每个存储节点上的 Cassandra 服务将停止并重新启动。

对于未来的StorageGRID功能版本，Cassandra 数据库更新步骤可能需要几天时间才能完成。



 a| 
最终升级步骤
 a| 
临时文件已被删除，新版本的升级已完成。
 a| 
5分钟
 a| 
当*最终升级步骤*任务完成后，您可以执行所有维护程序。

|===
.步骤
. 估计升级所有网格节点所需的时间。
+
.. 将StorageGRID系统中的节点数乘以 1 小时/节点。
+
一般来说，设备节点的升级时间比基于软件的节点更长。

.. 在此时间上添加 1 小时，以计算下载所需的时间 `.upgrade`文件，运行预检验证，并完成最后的升级步骤。


. 如果您有 Linux 节点，请为每个节点增加 15 分钟，以计算下载和安装 RPM 或 DEB 包所需的时间。
. 将步骤 1 和 2 的结果相加，计算升级的总预计时间。




== 示例：升级到StorageGRID 11.9 的预计时间

假设您的系统有 14 个网格节点，其中 8 个是 Linux 节点。

. 将 14 乘以 1 小时/节点。
. 添加 1 小时以用于下载、预检和最后步骤。
+
升级所有节点预计需要 15 小时。

. 将 8 乘以 15 分钟/节点，以计算在 Linux 节点上安装 RPM 或 DEB 包的时间。
+
此步骤预计耗时 2 小时。

. 将这些值加在一起。
+
您最多需要 17 个小时才能完成系统到StorageGRID 11.9.0 的升级。




NOTE: 根据需要，您可以通过批准网格节点子集在多个会话中进行升级，将维护窗口拆分为更小的窗口。例如，您可能希望在一个会话中升级站点 A 上的节点，然后在稍后的会话中升级站点 B 上的节点。如果您选择在多个会话中执行升级，请注意，只有在所有节点都升级完成后，您才能开始使用新功能。
