---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html 
sidebar: sidebar 
keywords: upgrade, firmware, appliance, alert 
summary: 了解您的StorageGRID系统在升级期间将受到怎样的影响。 
---
= 升级期间您的系统会受到什么影响
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解您的StorageGRID系统在升级期间将受到怎样的影响。



== StorageGRID升级不会造成中断

StorageGRID系统可以在整个升级过程中从客户端应用程序提取和检索数据。如果您批准升级所有相同类型的节点（例如，存储节点），则会一次关闭一个节点，因此不会出现所有网格节点或某种类型的所有网格节点都不可用的情况。

为了实现持续可用性，请确保您的 ILM 策略包含指定存储每个对象的多个副本的规则。您还必须确保所有外部 S3 客户端都配置为将请求发送到以下之一：

* 高可用性 (HA) 组虚拟 IP 地址
* 高可用性第三方负载均衡器
* 每个客户端有多个网关节点
* 每个客户端有多个存储节点




== 客户端应用程序可能会遭遇短期中断

StorageGRID系统可以在整个升级过程中从客户端应用程序提取和检索数据；但是，如果升级需要重新启动这些节点上的服务，则客户端与各个网关节点或存储节点的连接可能会暂时中断。升级过程完成后，连接将恢复，并且各个节点上的服务将恢复。

如果短时间内失去连接是不可接受的，您可能需要安排停机时间来应用升级。您可以使用选择性批准来安排某些节点的更新时间。


NOTE: 您可以使用多个网关和高可用性 (HA) 组在升级过程中提供自动故障转移。请参阅说明link:../admin/configure-high-availability-group.html["配置高可用性组"]。



== 设备固件已升级

在StorageGRID 11.9 升级期间：

* 所有StorageGRID设备节点都会自动升级到StorageGRID Appliance Installer 固件版本 3.9。
* SG6060 和 SGF6024 设备自动升级到 BIOS 固件版本 3B08.EX 和BMC固件版本 4.00.07。
* SG100 和 SG1000 设备自动升级到 BIOS 固件版本 3B13.EC 和BMC固件版本 4.74.07。
* SGF6112、SG6160、SG110 和 SG1100 设备自动升级到BMC固件版本 3.16.07。




== ILM 策略根据其状态进行不同的处理

* 升级后，有效策略将保持不变。
* 升级时仅保留最新的 10 条历史策略。
* 如果有建议的政策，它将在升级期间被删除。




== 可能会触发警报

当服务启动和停止时，以及当StorageGRID系统作为混合版本环境运行时（一些网格节点运行早期版本，而其他网格节点已升级到更高版本），可能会触发警报。升级完成后可能会触发其他警报。

例如，当服务停止时，您可能会看到*无法与节点通信*警报，或者当某些节点已升级到StorageGRID 11.9 但其他节点仍在运行StorageGRID 11.8 时，您可能会看到*Cassandra 通信错误*警报。一般来说，升级完成后这些警报将会清除。

在升级到StorageGRID 11.9 期间存储节点停止时，可能会触发 *ILM 放置无法实现* 警报。升级完成后，此警报可能会持续 1 天。

升级完成后，您可以通过从网格管理器仪表板中选择*最近解决的警报*或*当前警报*来查看任何与升级相关的警报。



== 生成许多 SNMP 通知

请注意，升级期间停止并重新启动网格节点时可能会生成大量 SNMP 通知。为避免过多的通知，请在开始升级之前清除*启用 SNMP 代理通知*复选框（*配置* > *监控* > *SNMP 代理*）以禁用 SNMP 通知。然后，升级完成后重新启用通知。



== 配置更改受到限制


NOTE: 此列表专门适用于从StorageGRID 11.8 升级到StorageGRID 11.9。如果您要升级到另一个StorageGRID版本，请参阅该版本升级说明中的受限更改列表。

直到“启用新功能”任务完成：

* 不要进行任何网格配置更改。
* 不要启用或禁用任何新功能。
* 不要更新 ILM 配置。否则，您可能会遇到不一致且意外的 ILM 行为。
* 不要应用修补程序或恢复网格节点。
+

NOTE: 如果您需要在升级期间恢复节点，请联系技术支持。

* 升级到StorageGRID 11.9 时，您不应管理 HA 组、VLAN 接口或负载均衡器端点。
* 在升级到StorageGRID 11.9 完成之前，请勿删除任何 HA 组。其他 HA 组中的虚拟 IP 地址可能变得无法访问。


直到*最终升级步骤*任务完成：

* 不要执行扩展程序。
* 不要执行退役程序。




== 您无法从租户管理器查看存储桶详细信息或管理存储桶

在升级到StorageGRID 11.9 期间（即系统作为混合版本环境运行时），您无法使用租户管理器查看存储桶详细信息或管理存储桶。租户管理器中的“存储桶”页面上出现以下错误之一：

* 升级到 11.9 时无法使用此 API。
* 升级到 11.9 时，您无法在租户管理器中查看存储桶版本控制详细信息。


升级到 11.9 后，此错误将会解决。

.临时解决策
在 11.9 升级过程中，请使用以下工具查看存储桶详细信息或管理存储桶，而不是使用租户管理器：

* 要在存储桶上执行标准 S3 操作，请使用link:../s3/operations-on-buckets.html["S3 REST API"]或link:../tenant/understanding-tenant-management-api.html["租户管理 API"]。
* 要对存储桶执行StorageGRID自定义操作（例如，查看和修改存储桶一致性、启用或禁用上次访问时间更新或配置搜索集成），请使用租户管理 API。

