---
permalink: upgrade/performing-upgrade.html 
sidebar: sidebar 
keywords: upgrade, how to perform a software upgrade 
summary: 您可以升级到StorageGRID 11.9 并同时应用该版本的最新修补程序。StorageGRID升级页面提供了推荐的升级路径并直接链接到正确的下载页面。 
---
= 执行升级
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升级到StorageGRID 11.9 并同时应用该版本的最新修补程序。StorageGRID升级页面提供了推荐的升级路径并直接链接到正确的下载页面。

.开始之前
您已审查了所有注意事项并完成了所有规划和准备步骤。



== 访问StorageGRID升级页面

第一步，访问网格管理器中的StorageGRID升级页面。

.步骤
. Sign inlink:../admin/web-browser-requirements.html["支持的网络浏览器"]。
. 选择*维护* > *系统* > *软件更新*。
. 从StorageGRID升级图块中，选择 *升级*。




== 选择文件

StorageGRID升级页面上的更新路径指示必须安装哪些主要版本（例如，11.9.0）和修补程序（例如，11.9.0.1）才能获得最新的StorageGRID版本。您应该按照显示的顺序安装推荐的版本和修补程序。


TIP: 如果没有显示更新路径，您的浏览器可能无法访问NetApp支持站点，或者AutoSupport页面（*支持* > *工具* > *AutoSupport* > *设置*）上的 *检查软件更新*复选框可能被禁用。

.步骤
. 对于*选择文件*步骤，检查更新路径。
. 从下载文件部分，选择每个*下载*链接以从NetApp支持站点下载所需的文件。
+
如果没有显示更新路径，请转至 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下载： StorageGRID"^]确定是否有新版本或修补程序可用并下载所需的文件。

+

NOTE: 如果您需要在所有 Linux 主机上下载并安装 RPM 或 DEB 包，您可能已经在更新路径中列出了StorageGRID升级和修补程序文件。

. 选择*浏览*将版本升级文件上传到StorageGRID： `NetApp_StorageGRID_11.9.0_Software_uniqueID.upgrade`
+
上传和验证过程完成后，文件名旁边会出现一个绿色复选标记。

. 如果您下载了修补程序文件，请选择“*浏览*”来上传该文件。该修补程序将作为版本升级的一部分自动应用。
. 选择*继续*。




== 运行预检

运行预检查可让您在开始升级电网之前检测并解决任何升级问题。

.步骤
. 对于*运行预检查*步骤，首先输入网格的配置密码。
. 选择*下载恢复包*。
+
在升级主管理节点之前，您应该下载恢复包文件的当前副本。如果发生故障，恢复包文件允许您恢复系统。

. 下载文件后，请确认您可以访问其内容，包括 `Passwords.txt`文件。
. 复制下载的文件(`.zip`）到两个安全、可靠且独立的位置。
+

CAUTION: 恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。

. 选择*运行预检查*，然后等待预检查完成。
. 查看每个报告的预检的详细信息并解决任何报告的错误。查看 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["StorageGRID软件升级解决指南"^]适用于StorageGRID 11.9 版本。
+
您必须先解决所有预检错误，然后才能升级系统。但是，您不需要在升级之前解决预检_警告_。

+

CAUTION: 如果您打开了任何自定义防火墙端口，则会在预检验证期间收到通知。您必须在继续升级之前联系技术支持。

. 如果您进行了任何配置更改来解决报告的问题，请再次选择*运行预检查*以获取更新的结果。
+
如果所有错误都已解决，系统将提示您开始升级。





== 开始升级并升级主管理节点

当您开始升级时，升级预检查将再次运行，并且主管理节点将自动升级。升级的这一部分最多可能需要 30 分钟。


NOTE: 在主管理节点升级期间，您将无法访问任何其他网格管理器页面。审计日志也将不可用。

.步骤
. 选择*开始升级*。
+
出现警告，提醒您将暂时失去对网格管理器的访问权限。

. 选择“*确定*”确认警告并开始升级。
. 等待升级预检查完成并等待主管理节点升级。
+

NOTE: 如果报告任何预检错误，请解决它们并再次选择*开始升级*。

+
如果网格有另一个在线且准备就绪的管理节点，则可以使用它来监视主管理节点的状态。一旦主管理节点升级，您就可以批准其他网格节点。

. 根据需要，选择*继续*以访问*升级其他节点*步骤。




== 升级其他节点

您必须升级所有网格节点，但您可以执行多个升级会话并自定义升级顺序。例如，您可能希望在一个会话中升级站点 A 上的节点，然后在稍后的会话中升级站点 B 上的节点。如果您选择在多个会话中执行升级，请注意，只有在所有节点都升级完成后，您才能开始使用新功能。

如果节点升级的顺序很重要，请一次批准一个节点或节点组，并等到每个节点的升级完成后再批准下一个节点或节点组。


NOTE: 当网格节点上开始升级时，该节点上的服务将停止。稍后，网格节点重新启动。为了避免与节点通信的客户端应用程序的服务中断，除非您确定节点已准备好停止并重新启动，否则不要批准节点的升级。根据需要安排维护时段或通知客户。

.步骤
. 对于*升级其他节点*步骤，请查看摘要，其中提供了整个升级的开始时间以及每个主要升级任务的状态。
+
** *启动升级服务*是第一个升级任务。在此任务期间，软件文件被分发到网格节点，并且在每个节点上启动升级服务。
** 当*启动升级服务*任务完成后，*升级其他网格节点*任务将启动，并提示您下载恢复包的新副本。


. 出现提示时，输入您的配置密码并下载恢复包的新副本。
+

CAUTION: 主管理节点升级后，您应该下载恢复包文件的新副本。如果发生故障，恢复包文件允许您恢复系统。

. 查看每种类型节点的状态表。有非主要管理节点、网关节点和存储节点的表。
+
当表格首次出现时，网格节点可能处于以下阶段之一：

+
** 解压升级包
** 正在下载
** 等待批准


. [[approval-step]]当您准备好选择要升级的网格节点（或者如果您需要取消批准选定的节点）时，请使用以下说明：
+
[cols="1a,1a"]
|===
| 任务 | 操作说明 


 a| 
搜索要批准的特定节点，例如特定站点的所有节点
 a| 
在*搜索*字段中输入搜索字符串



 a| 
选择所有节点进行升级
 a| 
选择*批准所有节点*



 a| 
选择所有相同类型的节点进行升级（例如，所有存储节点）
 a| 
选择节点类型的“*全部批准*”按钮

如果您批准多个相同类型的节点，则将一次升级一个节点。



 a| 
选择单个节点进行升级
 a| 
选择节点的*批准*按钮



 a| 
推迟所有选定节点的升级
 a| 
选择*取消批准所有节点*



 a| 
推迟所有选定的同类型节点的升级
 a| 
选择节点类型的“全部取消批准”按钮



 a| 
推迟单个节点的升级
 a| 
选择节点的*取消批准*按钮

|===
. 等待批准的节点完成以下升级阶段：
+
** 已批准并等待升级
** 停止服务
+

NOTE: 当节点的阶段达到*停止服务*时，您无法删除该节点。  *取消批准*按钮已被禁用。

** 停止容器
** 清理 Docker 镜像
** 升级基础操作系统包
+

NOTE: 当设备节点到达此阶段时，设备上的StorageGRID Appliance Installer 软件将更新。此自动化过程可确保StorageGRID Appliance Installer 版本与StorageGRID软件版本保持同步。

** 正在重新启动
+

NOTE: 某些设备型号可能会重启多次以升级固件和 BIOS。

** 重启后执行步骤
** 启动服务
** 完毕


. 重复<<approval-step,批准步骤>>根据需要多次，直到所有网格节点都升级完毕。




== 全面升级

当所有网格节点都完成升级阶段后，“升级其他网格节点”任务将显示为“已完成”。其余升级任务在后台自动执行。

.步骤
. 一旦“启用功能”任务完成（很快就会完成），您就可以开始使用link:whats-new.html["新功能"]在升级的StorageGRID版本中。
. 在*升级数据库*任务期间，升级过程会检查每个节点以验证 Cassandra 数据库不需要更新。
+

NOTE: 从StorageGRID 11.8 升级到 11.9 不需要升级 Cassandra 数据库；但是，每个存储节点上的 Cassandra 服务将停止并重新启动。对于未来的StorageGRID功能版本，Cassandra 数据库更新步骤可能需要几天时间才能完成。

. 当*升级数据库*任务完成后，等待几分钟以完成*最终升级步骤*。
. 当*最终升级步骤*完成后，升级就完成了。第一步，*选择文件*，重新显示绿色成功横幅。
. 验证电网运行是否已恢复正常：
+
.. 检查服务是否正常运行并且没有意外警报。
.. 确认客户端与StorageGRID系统的连接是否按预期运行。



