---
permalink: upgrade/removed-or-deprecated-features.html 
sidebar: sidebar 
keywords:  
summary: 此版本中删除或弃用了某些特性和功能。查看这些项目以了解升级之前是否需要更新客户端应用程序或修改配置。 
---
= 已删除或弃用的功能和能力
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此版本中删除或弃用了某些特性和功能。查看这些项目以了解升级之前是否需要更新客户端应用程序或修改配置。



== 定义

已弃用:: 该功能*不应*在新的生产环境中使用。现有的生产环境可以继续使用该功能。
生命终结:: 支持该功能的最新版本。在某些情况下，该功能的文档可能会在此阶段被删除。
已移除:: 第一个不支持该功能的版本。




== StorageGRID功能支持终止

弃用的功能将在 N+2 主要版本中被删除。例如，如果某个功能在版本 N（例如 6.3）中被弃用，则该功能将存在的最后一个版本是 N+1（例如 6.4）。版本 N+2（例如 6.5）是产品中不存在该功能时的第一个版本。

查看 https://mysupport.netapp.com/site/info/version-support["软件版本支持页面"^]了解更多信息。


NOTE: 在某些情况下， NetApp可能会提前终止对特定功能的支持。

[cols="2a,1a,1a,1a,3a"]
|===
| 功能 | 已弃用 | 生命终结 | 已移除 | 早期文档的链接 


 a| 
传统警报（不是警报）
 a| 
11.7
 a| 
11.8
 a| 
11.9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html["警报参考（StorageGRID 11.8）"^]



 a| 
存档节点支持
 a| 
11.7
 a| 
11.8
 a| 
11.9
 a| 
https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html["退役存档节点的注意事项（StorageGRID 11.8）"^]

*注意*：在开始升级之前，您必须：

. 退役所有存档节点。看 https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html["网格节点退役（StorageGRID 11.8 文档站点）"^]。
. 从存储池和 ILM 策略中删除所有存档节点引用。看 https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide["NetApp知识库： StorageGRID 11.9 软件升级解决指南"^]。




 a| 
通过 CIFS/Samba 进行审计导出
 a| 
11.1
 a| 
11.6
 a| 
11.7
 a| 



 a| 
CLB 服务
 a| 
11.4
 a| 
11.6
 a| 
11.7
 a| 



 a| 
Docker容器引擎
 a| 
11.8
 a| 
11.9
 a| 
待定
 a| 
不再支持将 Docker 作为纯软件部署的容器引擎。Docker 将在未来的版本中被另一个容器引擎取代。请参阅link:../ubuntu/software-requirements.html#docker-versions-tested["当前支持的 Docker 版本列表"]。



 a| 
NFS 审计导出
 a| 
11.8
 a| 
11.9
 a| 
12.0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-audit-client-access.html["配置 NFS 的审计客户端访问（StorageGRID 11.8）"^]



 a| 
Swift API 支持
 a| 
11.7
 a| 
11.9
 a| 
12.0
 a| 
https://docs.netapp.com/us-en/storagegrid-118/swift/index.html["使用 Swift REST API（StorageGRID 11.8）"^]



 a| 
RHEL 8.8
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
RHEL 9.0
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
RHEL 9.2
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Ubuntu 18.04
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Ubuntu 20.04
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 



 a| 
Debian 11
 a| 
11.9
 a| 
11.9
 a| 
12.0
 a| 

|===
另请参阅：

* link:../upgrade/changes-to-grid-management-api.html["网格管理 API 的变更"]
* link:../upgrade/changes-to-tenant-management-api.html["租户管理 API 的变更"]

