---
permalink: upgrade/troubleshooting-upgrade-issues.html 
sidebar: sidebar 
keywords: upgrade, troubleshoot, troubleshooting, errors, upgrade precheck 
summary: 如果升级时出现问题，您也许能够自己解决问题。如果您无法解决问题，请收集尽可能多的信息，然后联系技术支持。 
---
= 解决升级问题
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果升级时出现问题，您也许能够自己解决问题。如果您无法解决问题，请收集尽可能多的信息，然后联系技术支持。



== 升级未完成

以下部分介绍如何从升级部分失败的情况中恢复。



=== 升级预检查错误

为了检测和解决问题，您可以在开始实际升级之前手动运行升级预检查。大多数预检错误都提供了有关如何解决问题的信息。



=== 预配失败

如果自动配置过程失败，请联系技术支持。



=== 网格节点崩溃或无法启动

如果网格节点在升级过程中崩溃或升级完成后无法成功启动，请联系技术支持调查并纠正任何潜在问题。



=== 提取或数据检索中断

如果在未升级网格节点时数据提取或检索意外中断，请联系技术支持。



=== 数据库升级错误

如果数据库升级失败并出现错误，请重试升级。如果再次失败，请联系技术支持。

.相关信息
link:checking-systems-condition-before-upgrading-software.html["升级软件前检查系统状况"]



== 用户界面问题

升级期间或升级后，您可能会遇到网格管理器或租户管理器的问题。



=== 网格管理器在升级过程中显示多条错误消息

如果在主管理节点升级时刷新浏览器或导航到另一个网格管理器页面，您可能会看到多个“503：服务不可用”和“连接服务器时出现问题”消息。您可以放心地忽略这些消息——节点升级后它们将不再出现。

如果这些消息在您开始升级后出现超过一小时，则可能发生了一些事情，导致主管理节点无法升级。如果您无法自行解决问题，请联系技术支持。



=== Web 界面未按预期响应

StorageGRID软件升级后，网格管理器或租户管理器可能无法按预期响应。

如果您在使用 Web 界面时遇到问题：

* 确保您使用的是link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
+

NOTE: 浏览器支持通常会随着每个StorageGRID版本的发布而发生变化。

* 清除您的网络浏览器缓存。
+
清除缓存会删除以前版本的StorageGRID软件使用的过时资源，并允许用户界面再次正常运行。有关说明，请参阅 Web 浏览器的文档。





== “Docker 镜像可用性检查”错误消息

尝试启动升级过程时，您可能会收到一条错误消息，指出“Docker 映像可用性检查验证套件识别出以下问题。”必须先解决所有问题，然后才能完成升级。

如果您不确定解决已发现的问题需要进行哪些更改，请联系技术支持。

[cols="1a,1a,1a"]
|===
| 消息 | 发生原因 | 解决方案 


 a| 
无法确定升级版本。升级版本信息文件 `{file_path}`与预期格式不匹配。
 a| 
升级包已损坏。
 a| 
重新上传升级包，再试一次。如果问题仍然存在，请联系技术支持。



 a| 
升级版本信息文件 `{file_path}`未找到。无法确定升级版本。
 a| 
升级包已损坏。
 a| 
重新上传升级包，再试一次。如果问题仍然存在，请联系技术支持。



 a| 
无法确定当前安装的发行版本 `{node_name}`。
 a| 
节点上的关键文件已损坏。
 a| 
请联系技术支持。



 a| 
尝试列出版本时出现连接错误 `{node_name}`
 a| 
节点离线或连接中断。
 a| 
检查以确保所有节点均在线且可从主管理节点访问，然后重试。



 a| 
节点的主机 `{node_name}`没有StorageGRID `{upgrade_version}`图像已加载。升级之前必须在主机上安装映像和服务。
 a| 
节点运行的主机上尚未安装升级所需的 RPM 或 DEB 包，或者映像仍处于导入过程中。

*注意：*此错误仅适用于在 Linux 上作为容器运行的节点。
 a| 
检查以确保所有运行节点的 Linux 主机上都已安装 RPM 或 DEB 包。确保服务和图像文件的版本正确。请稍等几分钟，然后重试。

看link:../upgrade/linux-installing-rpm-or-deb-package-on-all-hosts.html["Linux：在所有主机上安装 RPM 或 DEB 包"] 。



 a| 
检查节点时出错 `{node_name}`
 a| 
发生了意外错误。
 a| 
请稍等几分钟，然后重试。



 a| 
运行预检时未捕获的错误。 `{error_string}`
 a| 
发生了意外错误。
 a| 
请稍等几分钟，然后重试。

|===