---
permalink: upgrade/verifying-installed-version-of-storagegrid.html 
sidebar: sidebar 
keywords: storagegrid, version, current version, previous version 
summary: 在开始升级之前，请验证当前是否安装了先前版本的StorageGRID并应用了最新的可用修补程序。 
---
= 验证已安装的StorageGRID版本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在开始升级之前，请验证当前是否安装了先前版本的StorageGRID并应用了最新的可用修补程序。

.关于此任务
在升级到StorageGRID 11.9 之前，您的网格必须安装StorageGRID 11.8。如果您当前正在使用以前版本的StorageGRID，则必须安装所有以前的升级文件及其最新的修补程序（强烈推荐），直到网格的当前版本为StorageGRID 11.8._x.y_。

一种可能的升级路径如下<<example-upgrade-path,示例>>。


CAUTION: NetApp强烈建议您在升级到下一个版本之前为每个StorageGRID版本应用最新的修补程序，并且还为您安装的每个新版本应用最新的修补程序。在某些情况下，您必须应用修补程序以避免数据丢失的风险。看 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下载： StorageGRID"^]以及每个修补程序的发行说明以了解更多信息。

.步骤
. Sign inlink:../admin/web-browser-requirements.html["支持的网络浏览器"]。
. 从网格管理器的顶部，选择*帮助* > *关于*。
. 验证*版本*是否为 11.8._x.y_。
+
在StorageGRID 11.8._x.y_ 版本号中：

+
** *主要版本*的 _x_ 值为 0（11.8.0）。
** 如果已应用 *hotfix*，则其值为 _y_（例如，11.8.0.1）。


. 如果 *Version* 不是 11.8._x.y_，请转到 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下载： StorageGRID"^]下载每个先前版本的文件，包括每个版本的最新修补程序。
. 获取您下载的每个版本的升级说明。然后，执行该版本的软件升级过程，并应用该版本的最新修补程序（强烈推荐）。
+
查看link:../maintain/storagegrid-hotfix-procedure.html["StorageGRID修补程序程序"]。





== [[example-upgrade-path]]示例：从版本 11.6 升级到StorageGRID 11.9

以下示例显示了从StorageGRID版本 11.6 升级到版本 11.8 以准备升级到StorageGRID 11.9 的步骤。

按照以下顺序下载并安装软件，为系统升级做好准备：

. 升级到StorageGRID 11.6.0 主要版本。
. 应用最新的StorageGRID 11.6.0._y_ 修补程序。
. 升级到StorageGRID 11.7.0 主要版本。
. 应用最新的StorageGRID 11.7.0._y_ 修补程序。
. 升级到StorageGRID 11.8.0 主要版本。
. 应用最新的StorageGRID 11.8.0._y_ 修补程序。

