---
permalink: harden/hardening-guidelines-for-software-upgrades.html 
sidebar: sidebar 
keywords: Hardening guidelines, upgrades 
summary: 您必须保持StorageGRID系统和相关服务为最新版本以防御攻击。 
---
= 软件升级强化指南
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须保持StorageGRID系统和相关服务为最新版本以防御攻击。



== StorageGRID软件升级

只要有可能，您就应该将StorageGRID软件升级到最新的主要版本或之前的主要版本。保持StorageGRID为最新状态有助于减少已知漏洞的活跃时间并减少整体攻击面。此外， StorageGRID的最新版本通常包含早期版本中未包含的安全强化功能。

咨询 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^]（IMT）来确定您应该使用哪个版本的StorageGRID软件。当需要修补程序时， NetApp会优先为最新版本创建更新。某些补丁可能与早期版本不兼容。

* 要下载最新的StorageGRID版本和修补程序，请访问 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp下载： StorageGRID"^]。
* 要升级StorageGRID软件，请参阅link:../upgrade/performing-upgrade.html["升级说明"]。
* 要应用修补程序，请参阅link:../maintain/storagegrid-hotfix-procedure.html["StorageGRID修补程序程序"]。




== 外部服务升级

外部服务可能存在间接影响StorageGRID 的漏洞。您应该确保StorageGRID所依赖的服务保持最新。这些服务包括 LDAP、KMS（或 KMIP 服务器）、DNS 和 NTP。

有关受支持版本的列表，请参阅 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^]。



== 升级虚拟机管理程序

如果您的StorageGRID节点在 VMware 或其他虚拟机管理程序上运行，则必须确保虚拟机管理程序软件和固件是最新的。

有关受支持版本的列表，请参阅 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^]。



== *升级到 Linux 节点*

如果您的StorageGRID节点使用 Linux 主机平台，则必须确保安全更新和内核更新已应用于主机操作系统。此外，当这些更新可用时，您必须将固件更新应用于易受攻击的硬件。

有关受支持版本的列表，请参阅 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^]。
