---
permalink: network/linux-deployments.html 
sidebar: sidebar 
keywords: linux network, container engine, red hat enterprise linux rhel network, ubuntu network 
summary: 为了提高效率、可靠性和安全性， StorageGRID系统作为容器引擎的集合在 Linux 上运行。  StorageGRID系统中不需要与容器引擎相关的网络配置。 
---
= Linux 部署
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为了提高效率、可靠性和安全性， StorageGRID系统作为容器引擎的集合在 Linux 上运行。  StorageGRID系统中不需要与容器引擎相关的网络配置。

使用非绑定设备（例如 VLAN 或虚拟以太网 (veth) 对）作为容器网络接口。在节点配置文件中将此设备指定为网络接口。


CAUTION: 不要直接使用绑定或桥接设备作为容器网络接口。这样做可能会阻止节点启动，因为在容器命名空间中使用 macvlan 与绑定和桥接设备存在内核问题。

请参阅安装说明link:../rhel/index.html["Red Hat Enterprise Linux"]或者link:../ubuntu/index.html["Ubuntu 或 Debian"]部署。



== 容器引擎部署的主机网络配置

在容器引擎平台上开始StorageGRID部署之前，请确定每个节点将使用哪些网络（网格、管理、客户端）。您必须确保每个节点的网络接口都配置在正确的虚拟或物理主机接口上，并且每个网络都具有足够的带宽。



=== 物理主机

如果您使用物理主机来支持网格节点：

* 确保所有主机的每个节点接口都使用相同的主机接口。该策略简化了主机配置并支持未来的节点迁移。
* 获取物理主机本身的 IP 地址。
+

NOTE: 主机上的物理接口可供主机本身以及主机上运行的一个或多个节点使用。使用此接口分配给主机或节点的任何 IP 地址都必须是唯一的。主机和节点不能共享IP地址。

* 向主机开放所需的端口。
* 如果您打算在StorageGRID中使用 VLAN 接口，则主机必须具有一个或多个中继接口以提供对所需 VLAN 的访问。这些接口可以作为 eth0、eth2 或附加接口传递到节点容器中。要添加中继或访问接口，请参阅以下内容：
+
** *RHEL（安装节点之前）*：link:../rhel/creating-node-configuration-files.html["创建节点配置文件"]
** *Ubuntu 或 Debian（安装节点之前）*：link:../ubuntu/creating-node-configuration-files.html["创建节点配置文件"]
** *RHEL、Ubuntu 或 Debian（安装节点后）*：link:../maintain/linux-adding-trunk-or-access-interfaces-to-node.html["Linux：向节点添加主干或访问接口"]






=== 最小带宽建议

下表提供了每种类型的StorageGRID节点和每种类型的网络的最低​​ LAN 带宽建议。您必须为每个物理或虚拟主机配备足够的网络带宽，以满足您计划在该主机上运行的StorageGRID节点总数和类型的总体最低带宽要求。

[cols="1a,1a,1a,1a"]
|===
| 节点类型 3+| 网络类型 


 a| 
 a| 
Grid
 a| 
管理员
 a| 
客户端



 a| 
 a| 
*最低 LAN 带宽*



 a| 
管理员
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
1 Gbps



 a| 
网关
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps



 a| 
存储
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps



 a| 
归档
 a| 
10 Gbps
 a| 
1 Gbps
 a| 
10 Gbps

|===

NOTE: 该表不包括访问共享存储所需的 SAN 带宽。如果您使用通过以太网（iSCSI 或 FCoE）访问的共享存储，则应在每个主机上配置单独的物理接口以提供足够的 SAN 带宽。为了避免引入瓶颈，给定主机的 SAN 带宽应大致与该主机上运行的所有存储节点的总存储节点网络带宽相匹配。

根据您计划在每个主机上运行的StorageGRID节点的数量和类型，使用该表确定每个主机上要配置的最小网络接口数量。

例如，要在单个主机上运行一个管理节点、一个网关节点和一个存储节点：

* 在管理节点上连接网格和管理网络（需要 10 + 1 = 11 Gbps）
* 连接网关节点上的电网和客户端网络（需要 10 + 10 = 20 Gbps）
* 连接存储节点上的电网网络（需要 10 Gbps）


在这种情况下，您应该提供至少 11 + 20 + 10 = 41 Gbps 的网络带宽，可以通过两个 40 Gbps 接口或五个 10 Gbps 接口来满足，可能聚合成中继，然后由承载主机所在物理数据中心本地的网格、管理和客户端子网的三个或更多 VLAN 共享。

有关在StorageGRID集群中的主机上配置物理和网络资源以准备StorageGRID部署的一些推荐方法，请参阅以下内容：

* link:../rhel/configuring-host-network.html["配置主机网络（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html["配置主机网络（Ubuntu 或 Debian）"]

