---
permalink: network/networking-requirements-and-guidelines.html 
sidebar: sidebar 
keywords: storagegrid, networking requirements, network requirements, nat 
summary: 您必须验证当前的网络基础设施和配置是否可以支持计划的StorageGRID网络设计。 
---
= 网络要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须验证当前的网络基础设施和配置是否可以支持计划的StorageGRID网络设计。



== 常规网络要求

所有StorageGRID部署必须能够支持以下连接。

这些连接可以通过网格、管理或客户端网络进行，或者通过网络拓扑示例中所示的这些网络的组合进行。

* *管理连接*：从管理员到节点的入站连接，通常通过 SSH。通过 Web 浏览器访问网格管理器、租户管理器和StorageGRID设备安装程序。
* *NTP 服务器连接*：接收入站 UDP 响应的出站 UDP 连接。
+
主管理节点必须能够访问至少一个 NTP 服务器。

* *DNS 服务器连接*：接收入站 UDP 响应的出站 UDP 连接。
* *LDAP/Active Directory 服务器连接*：来自存储节点上的身份服务的出站 TCP 连接。
* * AutoSupport*：从管理节点到 `support.netapp.com`或客户配置的代理。
* *外部密钥管理服务器*：来自每个启用节点加密的设备节点的出站 TCP 连接。
* 来自 S3 客户端的入站 TCP 连接。
* 来自StorageGRID平台服务（例如 CloudMirror 复制）或来自云存储池的出站请求。


如果StorageGRID无法使用默认路由规则联系任何已配置的 NTP 或 DNS 服务器，只要指定了 DNS 和 NTP 服务器的 IP 地址，它就会自动尝试联系所有网络（网格、管理和客户端）。如果可以通过任何网络访问 NTP 或 DNS 服务器， StorageGRID将自动创建额外的路由规则，以确保该网络在未来的所有连接尝试中均有效。


TIP: 虽然您可以使用这些自动发现的主机路由，但通常您应该手动配置 DNS 和 NTP 路由，以确保在自动发现失败时能够保持连接。

如果您尚未准备好在部署期间配置可选的管理员和客户端网络，则可以在配置步骤中批准网格节点时配置这些网络。此外，您可以在安装后使用更改 IP 工具配置这些网络（请参阅link:../maintain/configuring-ip-addresses.html["配置 IP 地址"]）。

VLAN 接口仅支持 S3 客户端连接和 SSH、Grid Manager 和 Tenant Manager 管理连接。出站连接（例如与 NTP、DNS、LDAP、 AutoSupport和 KMS 服务器的连接）必须直接通过客户端、管理或网格网络接口。如果将接口配置为中继以支持 VLAN 接口，则此流量将流过接口的本机 VLAN，如交换机上配置的那样。



== 多个站点的广域网 (WAN)

在配置具有多个站点的StorageGRID系统时，站点之间的 WAN 连接在每个方向上必须具有至少 25 Mbit/秒的带宽，然后才会考虑客户端流量。站点之间的数据复制或擦除编码、节点或站点扩展、节点恢复以及其他操作或配置将需要额外的带宽。

实际的最低 WAN 带宽要求取决于客户端活动和 ILM 保护方案。如需帮助估算最低 WAN 带宽要求，请联系您的NetApp专业服务顾问。



== 管理节点和网关节点的连接

管理节点必须始终受到保护，免受不受信任的客户端（例如开放互联网上的客户端）的攻击。您必须确保不受信任的客户端无法访问网格网络、管理网络或客户端网络上的任何管理节点。

您计划添加到高可用性组的管理节点和网关节点必须配置静态 IP 地址。有关更多信息，请参阅link:../admin/managing-high-availability-groups.html["管理高可用性组"] 。



== 使用网络地址转换（NAT）

不要在网格节点之间或StorageGRID站点之间的网格网络上使用网络地址转换 (NAT)。当您为网格网络使用私有 IPv4 地址时，这些地址必须能够从每个站点的每个网格节点直接路由。但是，根据需要，您可以在外部客户端和网格节点之间使用 NAT，例如为网关节点提供公共 IP 地址。仅当您使用对网格中的所有节点透明的隧道应用程序时，才支持使用 NAT 桥接公共网络段，这意味着网格节点不需要了解公共 IP 地址。
