= 节点配置文件的位置
:allow-uri-read: 




== 节点配置文件的位置

将每个StorageGRID节点的配置文件放在 `/etc/storagegrid/nodes`节点将运行的主机上的目录。例如，如果您计划在 HostA 上运行一个管理节点、一个网关节点和一个存储节点，则必须将三个节点配置文件放在 `/etc/storagegrid/nodes`在 HostA 上。

您可以使用文本编辑器（例如 vim 或 nano）直接在每个主机上创建配置文件，也可以在其他地方创建它们并将它们移动到每个主机。



== 节点配置文件的命名

配置文件的名称很重要。格式为 `node-name.conf`， 在哪里 `node-name`是您分配给节点的名称。此名称出现在StorageGRID安装程序中，用于节点维护操作，例如节点迁移。

节点名称必须遵循以下规则：

* 必须是唯一的
* 必须以字母开头
* 可以包含字符 A 到 Z 和 a 到 z
* 可以包含数字 0 到 9
* 可以包含一个或多个连字符 (-)
* 不得超过 32 个字符，不包括 `.conf`扩大


任何文件 `/etc/storagegrid/nodes`不遵循这些命名约定的内容将不会被主机服务解析。

如果您计划为电网采用多站点拓扑，则典型的节点命名方案可能是：

`site-nodetype-nodenumber.conf`

例如，您可以使用 `dc1-adm1.conf`对于数据中心 1 中的第一个管理节点，以及 `dc2-sn3.conf`用于数据中心 2 中的第三个存储节点。但是，您可以使用任何您喜欢的方案，只要所有节点名称都遵循命名规则。



== 节点配置文件的内容

配置文件包含键/值对，每行一个键和一个值。对于每个键/值对，遵循以下规则：

* 键和值必须用等号分隔(`=`) 和可选的空格。
* 键中不能包含空格。
* 值可以包含嵌入空格。
* 任何前导或尾随空格都会被忽略。


下表定义了所有受支持的键的值。每个键都有以下标识之一：

* *必需*：每个节点或指定节点类型都需要
* *最佳实践*：可选，但建议使用
* *可选*：所有节点可选




=== 管理网络密钥



==== 管理员IP

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
该节点所属网格的主管理节点的网格网络 IPv4 地址。对于 NODE_TYPE = VM_Admin_Node 和 ADMIN_ROLE = Primary 的网格节点，使用您为 GRID_NETWORK_IP 指定的相同值。如果省略此参数，节点将尝试使用 mDNS 发现主管理节点。

link:how-grid-nodes-discover-primary-admin-node.html["网格节点如何发现主管理节点"]

*注意*：在主管理节点上，此值会被忽略，甚至可能被禁止。
 a| 
最佳实践

|===


==== 管理网络配置

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
DHCP、静态或禁用
 a| 
可选

|===


==== 管理员网络

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
以 CIDR 表示法表示的子网的逗号分隔列表，此节点应使用管理网络网关与其进行通信。

例子： `172.16.0.0/21,172.17.0.0/21`
 a| 
可选

|===


==== 管理员网络网关

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
此节点的本地管理网络网关的 IPv4 地址。必须位于由 ADMIN_NETWORK_IP 和 ADMIN_NETWORK_MASK 定义的子网上。对于 DHCP 配置的网络，此值将被忽略。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
如果 `ADMIN_NETWORK_ESL`已指定。否则为可选。

|===


==== 管理网络 IP

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
管理网络上此节点的 IPv4 地址。仅当 ADMIN_NETWORK_CONFIG = STATIC 时才需要此键；不要将其指定为其他值。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
当 ADMIN_NETWORK_CONFIG = STATIC 时必需。

否则为可选。

|===


==== 管理员网络MAC地址

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
容器中管理网络接口的 MAC 地址。

此字段是可选的。如果省略，则会自动生成 MAC 地址。

必须是用冒号分隔的 6 对十六进制数字。

例子： `b2:9c:02:c2:27:10`
 a| 
可选

|===


==== 管理网络掩码

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
管理网络上此节点的 IPv4 网络掩码。当 ADMIN_NETWORK_CONFIG = STATIC 时指定此键；不要为其他值指定它。

例子：

`255.255.255.0`

`255.255.248.0`
 a| 
如果指定了 ADMIN_NETWORK_IP 并且 ADMIN_NETWORK_CONFIG = STATIC，则必需。

否则为可选。

|===


==== 管理网络最大传输单元 (MTU)

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
管理网络上此节点的最大传输单元 (MTU)。如果 ADMIN_NETWORK_CONFIG = DHCP，则不要指定。如果指定，则值必须介于 1280 和 9216 之间。如果省略，则使用 1500。

如果要使用巨型帧，请将 MTU 设置为适合巨型帧的值，例如 9000。否则，保留默认值。

*重要*：网络的 MTU 值必须与节点连接到的交换机端口上配置的值相匹配。否则，可能会出现网络性能问题或数据包丢失。

例子：

`1500`

`8192`
 a| 
可选

|===


==== 管理网络目标

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
用于StorageGRID节点管理网络访问的主机设备的名称。仅支持网络接口名称。通常，您使用的接口名称与 GRID_NETWORK_TARGET 或 CLIENT_NETWORK_TARGET 指定的接口名称不同。

*注意*：不要使用绑定或桥接设备作为网络目标。在绑定设备上配置 VLAN（或其他虚拟接口），或者使用网桥和虚拟以太网（veth）对。

*最佳实践*：即使此节点最初没有管理网络 IP 地址，也要指定一个值。然后，您可以稍后添加管理网络 IP 地址，而无需重新配置主机上的节点。

例子：

`bond0.1002`

`ens256`
 a| 
最佳实践

|===


==== 管理网络目标类型

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
接口（这是唯一支持的值。）
 a| 
可选

|===


==== ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
对还是错

将该键设置为“true”以使StorageGRID容器使用管理网络上主机目标接口的 MAC 地址。

*最佳实践：*在需要混杂模式的网络中，请改用 ADMIN_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 键。

有关 MAC 克隆的更多详细信息：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆的注意事项和建议（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆的注意事项和建议（Ubuntu 或 Debian）"]

 a| 
最佳实践

|===


==== 管理员角色

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
主或非主

仅当 NODE_TYPE = VM_Admin_Node 时才需要此键；不要为其他节点类型指定它。
 a| 
当 NODE_TYPE = VM_Admin_Node 时必需

否则为可选。

|===


=== 块设备密钥



==== 块设备审计日志

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
此节点将用于持久存储审计日志的块设备特殊文件的路径和名称。

例子：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-audit-logs`
 a| 
对于 NODE_TYPE = VM_Admin_Node 的节点是必需的。不要为其他节点类型指定它。

|===


==== BLOCK_DEVICE_RANGEDB_nnn

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
此节点将用于持久对象存储的块设备特殊文件的路径和名称。仅 NODE_TYPE = VM_Storage_Node 的节点需要此键；不要为其他节点类型指定它。

仅 BLOCK_DEVICE_RANGEDB_000 是必需的；其余的是可选的。为 BLOCK_DEVICE_RANGEDB_000 指定的块设备必须至少为 4 TB；其他的可以更小。

不要留下空隙。如果您指定 BLOCK_DEVICE_RANGEDB_005，则还必须指定 BLOCK_DEVICE_RANGEDB_004。

*注意*：为了与现有部署兼容，升级的节点支持两位数密钥。

例子：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-rangedb-000`
 a| 
必需的：

BLOCK_DEVICE_RANGEDB_000

选修的：

BLOCK_DEVICE_RANGEDB_001

BLOCK_DEVICE_RANGEDB_002

BLOCK_DEVICE_RANGEDB_003

BLOCK_DEVICE_RANGEDB_004

BLOCK_DEVICE_RANGEDB_005

BLOCK_DEVICE_RANGEDB_006

BLOCK_DEVICE_RANGEDB_007

BLOCK_DEVICE_RANGEDB_008

BLOCK_DEVICE_RANGEDB_009

BLOCK_DEVICE_RANGEDB_010

BLOCK_DEVICE_RANGEDB_011

BLOCK_DEVICE_RANGEDB_012

BLOCK_DEVICE_RANGEDB_013

BLOCK_DEVICE_RANGEDB_014

BLOCK_DEVICE_RANGEDB_015

|===


==== 块设备表

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
此节点将用于数据库表的持久存储的块设备特殊文件的路径和名称。仅 NODE_TYPE = VM_Admin_Node 的节点需要此键；不要为其他节点类型指定它。

例子：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-adm1-tables`
 a| 
必填项

|===


==== 块设备变量本地

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
此节点将使用的块设备特殊文件的路径和名称 `/var/local`持久存储。

例子：

`/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0`

`/dev/disk/by-id/wwn-0x600a09800059d6df000060d757b475fd`

`/dev/mapper/sgws-sn1-var-local`
 a| 
必填项

|===


=== 客户端网络密钥



==== 客户端网络配置

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
DHCP、静态或禁用
 a| 
可选

|===


==== 客户端网络网关

[cols="4a,2a"]
|===


 a| 
值
 a| 
指定



 a| 
此节点的本地客户端网络网关的 IPv4 地址，必须位于 CLIENT_NETWORK_IP 和 CLIENT_NETWORK_MASK 定义的子网上。对于 DHCP 配置的网络，此值将被忽略。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
可选

|===


==== 客户端网络 IP

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
客户端网络上此节点的 IPv4 地址。

仅当 CLIENT_NETWORK_CONFIG = STATIC 时才需要此键；不要将其指定为其他值。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
当 CLIENT_NETWORK_CONFIG = STATIC 时必需

否则为可选。

|===


==== 客户端网络MAC地址

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
容器中客户端网络接口的 MAC 地址。

此字段是可选的。如果省略，则会自动生成 MAC 地址。

必须是用冒号分隔的 6 对十六进制数字。

例子： `b2:9c:02:c2:27:20`
 a| 
可选

|===


==== 客户端网络掩码

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
客户端网络上此节点的 IPv4 网络掩码。

当 CLIENT_NETWORK_CONFIG = STATIC 时指定此键；不要为其他值指定它。

例子：

`255.255.255.0`

`255.255.248.0`
 a| 
如果指定了 CLIENT_NETWORK_IP 并且 CLIENT_NETWORK_CONFIG = STATIC，则为必需

否则为可选。

|===


==== 客户端网络 MTU

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
客户端网络上此节点的最大传输单元 (MTU)。如果 CLIENT_NETWORK_CONFIG = DHCP，则不要指定。如果指定，则值必须介于 1280 和 9216 之间。如果省略，则使用 1500。

如果要使用巨型帧，请将 MTU 设置为适合巨型帧的值，例如 9000。否则，保留默认值。

*重要*：网络的 MTU 值必须与节点连接到的交换机端口上配置的值相匹配。否则，可能会出现网络性能问题或数据包丢失。

例子：

`1500`

`8192`
 a| 
可选

|===


==== 客户端网络目标

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
用于StorageGRID节点客户端网络访问的主机设备的名称。仅支持网络接口名称。通常，您使用的接口名称与 GRID_NETWORK_TARGET 或 ADMIN_NETWORK_TARGET 指定的接口名称不同。

*注意*：不要使用绑定或桥接设备作为网络目标。在绑定设备上配置 VLAN（或其他虚拟接口），或者使用网桥和虚拟以太网（veth）对。

*最佳实践：*即使此节点最初没有客户端网络 IP 地址，也要指定一个值。然后，您可以稍后添加客户端网络 IP 地址，而无需重新配置主机上的节点。

例子：

`bond0.1003`

`ens423`
 a| 
最佳实践

|===


==== 客户端网络目标类型

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
接口（这是唯一支持的值。）
 a| 
可选

|===


==== 客户端网络目标类型接口克隆MAC地址

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
对还是错

将该键设置为“true”以使StorageGRID容器使用客户端网络上主机目标接口的 MAC 地址。

*最佳实践：*在需要混杂模式的网络中，请改用 CLIENT_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 键。

有关 MAC 克隆的更多详细信息：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆的注意事项和建议（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆的注意事项和建议（Ubuntu 或 Debian）"]

 a| 
最佳实践

|===


=== 网格网络键



==== 网格网络配置

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
静态或 DHCP

如果未指定，则默认为 STATIC。
 a| 
最佳实践

|===


==== GRID_NETWORK_GATEWAY

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
此节点的本地网格网络网关的 IPv4 地址，必须位于由 GRID_NETWORK_IP 和 GRID_NETWORK_MASK 定义的子网上。对于 DHCP 配置的网络，此值将被忽略。

如果网格网络是没有网关的单个子网，请使用子网的标准网关地址（XYZ1）或此节点的 GRID_NETWORK_IP 值；任一值都将简化未来潜在的网格网络扩展。
 a| 
必填项

|===


==== 网格网络IP

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
网格网络上此节点的 IPv4 地址。仅当 GRID_NETWORK_CONFIG = STATIC 时才需要此键；不要将其指定为其他值。

例子：

`1.1.1.1`

`10.224.4.81`
 a| 
当 GRID_NETWORK_CONFIG = STATIC 时必需

否则为可选。

|===


==== 网格网络MAC地址

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
容器中网格网络接口的 MAC 地址。

必须是用冒号分隔的 6 对十六进制数字。

例子： `b2:9c:02:c2:27:30`
 a| 
可选

如果省略，则会自动生成 MAC 地址。

|===


==== 网格网络掩码

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
网格网络上此节点的 IPv4 网络掩码。当 GRID_NETWORK_CONFIG = STATIC 时指定此键；不要为其他值指定它。

例子：

`255.255.255.0`

`255.255.248.0`
 a| 
当指定 GRID_NETWORK_IP 且 GRID_NETWORK_CONFIG = STATIC 时必需。

否则为可选。

|===


==== GRID_NETWORK_MTU

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
网格网络上此节点的最大传输单元 (MTU)。如果 GRID_NETWORK_CONFIG = DHCP，则不要指定。如果指定，则值必须介于 1280 和 9216 之间。如果省略，则使用 1500。

如果要使用巨型帧，请将 MTU 设置为适合巨型帧的值，例如 9000。否则，保留默认值。

*重要*：网络的 MTU 值必须与节点连接到的交换机端口上配置的值相匹配。否则，可能会出现网络性能问题或数据包丢失。

*重要*：为了获得最佳网络性能，所有节点都应在其网格网络接口上配置相似的 MTU 值。如果各个节点上的网格网络的 MTU 设置存在显著差异，则会触发*网格网络 MTU 不匹配*警报。所有网络类型的 MTU 值不必相同。

例子：

`1500`

`8192`
 a| 
可选

|===


==== 网格网络目标

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
用于StorageGRID节点网格网络访问的主机设备的名称。仅支持网络接口名称。通常，您使用的接口名称与为 ADMIN_NETWORK_TARGET 或 CLIENT_NETWORK_TARGET 指定的接口名称不同。

*注意*：不要使用绑定或桥接设备作为网络目标。在绑定设备上配置 VLAN（或其他虚拟接口），或者使用网桥和虚拟以太网（veth）对。

例子：

`bond0.1001`

`ens192`
 a| 
必填项

|===


==== 网格网络目标类型

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
接口（这是唯一支持的值。）
 a| 
可选

|===


==== GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
对还是错

将该键的值设置为“true”，以使StorageGRID容器使用网格网络上主机目标接口的 MAC 地址。

*最佳实践：*在需要混杂模式的网络中，请改用 GRID_NETWORK_TARGET_TYPE_INTERFACE_CLONE_MAC 键。

有关 MAC 克隆的更多详细信息：

* link:../rhel/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆的注意事项和建议（Red Hat Enterprise Linux）"]
* link:../ubuntu/configuring-host-network.html#considerations-and-recommendations-for-mac-address-cloning["MAC 地址克隆的注意事项和建议（Ubuntu 或 Debian）"]

 a| 
最佳实践

|===


=== 安装密码密钥（临时）



==== 自定义临时密码哈希

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
对于主管理节点，在安装期间为StorageGRID安装 API 设置默认临时密码。

*注意*：仅在主管理节点上设置安装密码。如果您尝试在另一个节点类型上设置密码，则节点配置文件的验证将失败。

安装完成后，设置此值不会产生任何效果。

如果省略此键，则默认不设置临时密码。或者，您可以使用StorageGRID安装 API 设置临时密码。

必须是 `crypt()`SHA-512 密码哈希及其格式 `$6$<salt>$<password hash>`密码长度至少为 8 个字符且不超过 32 个字符。

可以使用 CLI 工具生成此哈希，例如 `openssl passwd`SHA-512 模式下的命令。
 a| 
最佳实践

|===


=== 接口关键



==== 接口目标_nnnn

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
您想要添加到此节点的额外接口的名称和可选描述。您可以为每个节点添加多个额外的接口。

对于 _nnnn_，为您要添加的每个 INTERFACE_TARGET 条目指定一个唯一的编号。

对于该值，请指定裸机主机上的物理接口的名称。然后，可选择添加逗号并提供接口的描述，该描述显示在 VLAN 接口页面和 HA 组页面上。

例子： `INTERFACE_TARGET_0001=ens256, Trunk`

如果添加中继接口，则必须在StorageGRID中配置 VLAN 接口。如果添加访问接口，则可以将该接口直接添加到 HA 组；无需配置 VLAN 接口。
 a| 
可选

|===


=== 最大 RAM 键



==== 最大内存

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
此节点允许消耗的最大 RAM 量。如果省略此键，则节点没有内存限制。为生产级节点设置此字段时，请指定一个至少比系统总 RAM 少 24 GB 且少 16 到 32 GB 的值。

*注意*：RAM 值会影响节点的实际元数据保留空间。查看link:../admin/managing-object-metadata-storage.html["元数据保留空间的描述"]。

该字段的格式为 `_numberunit_`， 在哪里 `_unit_`可以 `b`， `k` ， `m` ， 或者 `g`。

例子：

`24g`

`38654705664b`

*注意*：如果您想使用此选项，您必须启用内核对内存 cgroups 的支持。
 a| 
可选

|===


=== 节点类型键



==== 节点类型

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
节点类型：

* VM_Admin_Node
* VM_存储_节点
* VM_Archive_Node
* VM_API_网关

 a| 
必填项

|===


==== 存储类型

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
定义存储节点包含的对象类型。有关更多信息，请参阅link:../primer/what-storage-node-is.html#types-of-storage-nodes["存储节点的类型"] 。仅 NODE_TYPE = VM_Storage_Node 的节点需要此键；不要为其他节点类型指定它。存储类型：

* 合并
* 数据
* metadata


*注意*：如果未指定 STORAGE_TYPE，则存储节点类型默认设置为组合（数据和元数据）。
 a| 
可选

|===


=== 端口重新映射键



==== 端口重新映射

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
重新映射节点用于内部网格节点通信或外部通信的任何端口。如果企业网络策略限制StorageGRID使用的一个或多个端口，则需要重新映射端口，如link:../network/internal-grid-node-communications.html["内部网格节点通信"]或者link:../network/external-communications.html["外部沟通"]。

*重要*：不要重新映射您计划用于配置负载均衡器端点的端口。

*注意*：如果仅设置了 PORT_REMAP，则您指定的映射将用于入站和出站通信。如果还指定了 PORT_REMAP_INBOUND，则 PORT_REMAP 仅适用于出站通信。

使用的格式是： `_network type_/_protocol_/_default port used by grid node_/_new port_` ， 在哪里 `_network type_`是网格、管理员或客户端，并且 `_protocol_`是 tcp 还是 udp。

例子： `PORT_REMAP = client/tcp/18082/443`

您还可以使用逗号分隔的列表重新映射多个端口。

例子： `PORT_REMAP = client/tcp/18082/443, client/tcp/18083/80`
 a| 
可选

|===


==== 端口重新映射入站

[cols="4a,2a"]
|===
| 值 | 指定 


 a| 
将入站通信重新映射到指定端口。如果您指定了 PORT_REMAP_INBOUND 但没有指定 PORT_REMAP 的值，则该端口的出站通信将保持不变。

*重要*：不要重新映射您计划用于配置负载均衡器端点的端口。

使用的格式是： `_network type_/_protocol_/_remapped port_/_default port used by grid node_` ， 在哪里 `_network type_`是网格、管理员或客户端，并且 `_protocol_`是 tcp 还是 udp。

例子： `PORT_REMAP_INBOUND = grid/tcp/3022/22`

您还可以使用逗号分隔的列表重新映射多个入站端口。

例子： `PORT_REMAP_INBOUND = grid/tcp/3022/22, admin/tcp/3022/22`
 a| 
可选

|===