= 什么是 S3 对象锁？
:allow-uri-read: 




== 什么是 S3 对象锁？

StorageGRID S3 对象锁功能是一种对象保护解决方案，相当于 Amazon Simple Storage Service (Amazon S3) 中的 S3 对象锁。

当为StorageGRID系统启用全局 S3 对象锁定设置时，S3 租户帐户可以创建启用或未启用 S3 对象锁定的存储桶。如果存储桶启用了 S3 对象锁，则需要存储桶版本控制，并且会自动启用。

*没有 S3 对象锁的存储桶*只能包含未指定保留设置的对象。任何摄取的对象都不会有保留设置。

*具有 S3 对象锁的存储桶*可以包含由 S3 客户端应用程序指定的具有或不具有保留设置的对象。一些摄取的对象将具有保留设置。

*配置了 S3 对象锁定和默认保留的存储桶*可以拥有指定了保留设置的上传对象和不带保留设置的新对象。新对象使用默认设置，因为尚未在对象级别配置保留设置。

实际上，当配置默认保留时，所有新摄取的对象都有保留设置。没有对象保留设置的现有对象不受影响。



=== 保留模式

StorageGRID S3 对象锁定功能支持两种保留模式，以对对象应用不同级别的保护。这些模式相当于 Amazon S3 保留模式。

* 在合规模式下：
+
** 在达到保留截止日期之前，无法删除该对象。
** 对象的保留截止日期可以增加，但不能减少。
** 在达到该日期之前，不能删除对象的保留截止日期。


* 在治理模式下：
+
** 具有特殊权限的用户可以在请求中使用绕过标头来修改某些保留设置。
** 这些用户可以在达到保留截止日期之前删除对象版本。
** 这些用户可以增加、减少或删除对象的保留期限。






=== 对象版本的保留设置

如果创建存储桶时启用了 S3 对象锁定，则用户可以使用 S3 客户端应用程序选择性地为添加到存储桶的每个对象指定以下保留设置：

* *保留模式*：合规或治理。
* *保留至日期*：如果对象版本的保留至日期在未来，则可以检索该对象，但不能删除它。
* *合法保留*：对对象版本应用合法保留会立即锁定该对象。例如，您可能需要对与调查或法律纠纷相关的对象实施法律保留。合法保留没有到期日，但会一直有效，直到被明确取消。合法保留与保留截止日期无关。
+

NOTE: 如果某个对象处于合法保留之下，则无论其保留模式如何，任何人都无法删除该对象。

+
有关对象设置的详细信息，请参阅link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 配置 S3 对象锁"]。





=== 存储桶的默认保留设置

如果创建存储桶时启用了 S3 对象锁定，用户可以选择为存储桶指定以下默认设置：

* *默认保留模式*：合规或治理。
* *默认保留期*：添加到此存储桶的新对象版本应保留多长时间（从添加之日起）。


默认存储桶设置仅适用于没有自己的保留设置的新对象。添加或更改这些默认设置时，现有的存储桶对象不会受到影响。

看link:../tenant/creating-s3-bucket.html["创建 S3 存储桶"]和link:../tenant/update-default-retention-settings.html["更新 S3 对象锁默认保留"]。
