= 启用 S3 对象锁定的存储桶的要求
:allow-uri-read: 




== 启用 S3 对象锁定的存储桶的要求

* 如果为StorageGRID系统启用了全局 S3 对象锁定设置，则您可以使用租户管理器、租户管理 API 或 S3 REST API 创建启用了 S3 对象锁定的存储桶。
* 如果您计划使用 S3 对象锁，则必须在创建存储桶时启用 S3 对象锁。您无法为现有存储桶启用 S3 对象锁定。
* 当为存储桶启用 S3 对象锁定时， StorageGRID会自动为该存储桶启用版本控制。您无法禁用 S3 对象锁定或暂停存储桶的版本控制。
* 或者，您可以使用租户管理器、租户管理 API 或 S3 REST API 为每个存储桶指定默认保留模式和保留期限。存储桶的默认保留设置仅适用于添加到存储桶且没有自己的保留设置的新对象。您可以通过在上传每个对象版本时为其指定保留模式和保留截止日期来覆盖这些默认设置。
* 启用 S3 对象锁的存储桶支持存储桶生命周期配置。
* 启用了 S3 对象锁的存储桶不支持 CloudMirror 复制。




== 启用 S3 对象锁的存储桶中的对象要求

* 为了保护对象版本，您可以为存储桶指定默认保留设置，也可以为每个对象版本指定保留设置。可以使用 S3 客户端应用程序或 S3 REST API 指定对象级保留设置。
* 保留设置适用于单个对象版本。对象版本可以同时具有保留截止日期和合法保留设置，或者只具有其中之一，或者两者都不具有。为对象指定保留期限或合法保留设置仅保护请求中指定的版本。您可以创建该对象的新版本，同时该对象的先前版本仍保持锁定状态。




== 启用 S3 对象锁的存储桶中对象的生命周期

启用 S3 对象锁后，保存在存储桶中的每个对象都会经历以下阶段：

. *对象摄取*
+
当对象版本添加到启用了 S3 对象锁定的存储桶时，将应用以下保留设置：

+
** 如果为对象指定了保留设置，则应用对象级别的设置。任何默认存储桶设置都将被忽略。
** 如果没有为对象指定保留设置，则应用默认存储桶设置（如果存在）。
** 如果没有为对象或存储桶指定保留设置，则该对象不受 S3 对象锁保护。


+
如果应用了保留设置，则对象和任何 S3 用户定义的元数据都受到保护。

. *对象保留和删除*
+
StorageGRID会存储每个受保护对象的多个副本，并保留指定的期限。对象副本的确切数量和类型以及存储位置由活动 ILM 策略中的兼容规则决定。受保护对象是否可以在达到保留期限之前被删除取决于其保留模式。

+
** 如果某个对象处于合法保留之下，则无论其保留模式如何，任何人都无法删除该对象。



