---
permalink: tenant/creating-s3-bucket.html 
sidebar: sidebar 
keywords: how to create S3 bucket 
summary: 您可以使用租户管理器为对象数据创建 S3 存储桶。 
---
= 创建 S3 存储桶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用租户管理器为对象数据创建 S3 存储桶。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 您属于具有 Root 访问权限或管理所有存储桶的用户组link:tenant-management-permissions.html["权限"]。这些权限将覆盖组或存储桶策略中的权限设置。
+

NOTE: 设置或修改存储桶或对象的 S3 对象锁定属性的权限可以通过以下方式授予link:../s3/bucket-and-group-access-policies.html["存储桶策略或组策略"]。

* 如果您计划为存储桶启用 S3 对象锁定，则网格管理员已为StorageGRID系统启用全局 S3 对象锁定设置，并且您已查看了 S3 对象锁定存储桶和对象的要求。
* 如果每个租户有 5,000 个存储桶，则网格中的每个存储节点至少有 64 GB 的 RAM。
+

NOTE: 每个网格最多可以有 100,000 个桶。





== 访问向导

.步骤
. 从仪表板中选择 *查看存储桶*，或选择 *存储（S3）* > *存储桶*。
. 选择*创建存储桶*。




== 输入详细信息

.步骤
. 输入存储桶的详细信息。
+
[cols="1a,3a"]
|===
| 字段 | 描述 


 a| 
存储桶名称
 a| 
符合以下规则的存储桶的名称：

** 每个StorageGRID系统中必须是唯一的（不仅仅是在租户帐户内是唯一的）。
** 必须符合 DNS 标准。
** 必须包含至少 3 个字符且不超过 63 个字符。
** 每个标签必须以小写字母或数字开头和结尾，并且只能使用小写字母、数字和连字符。
** 虚拟托管样式请求中不得包含句点。句点将导致服务器通配符证书验证出现问题。


有关详细信息，请参阅 https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html["Amazon Web Services (AWS) 有关存储桶命名规则的文档"^]。

*注意*：创建存储桶后，您无法更改存储桶名称。



 a| 
地区
 a| 
存储桶的区域。

您的StorageGRID管理员管理可用区域。存储桶的区域会影响应用于对象的数据保护策略。默认情况下，所有存储桶均在 `us-east-1`地区。

*注意*：创建存储桶后，您无法更改区域。

|===
. 选择*继续*。




== 管理设置

.步骤
. 或者，为存储桶启用对象版本控制。
+
如果您想要将每个对象的每个版本存储在此存储桶中，请启用对象版本控制。然后，您可以根据需要检索对象的先前版本。如果存储桶将用于跨网格复制，则必须启用对象版本控制。

. 如果启用了全局 S3 对象锁定设置，则可以选择为存储桶启用 S3 对象锁定，以使用一次写入多次读取 (WORM) 模型存储对象。
+
仅当您需要将对象保留固定时间（例如，为了满足某些监管要求）时，才为存储桶启用 S3 对象锁定。S3 对象锁定是一种永久性设置，可帮助您防止对象在固定时间内或无限期内被删除或覆盖。

+

CAUTION: 一旦为存储桶启用 S3 对象锁定设置，就无法禁用它。任何拥有正确权限的人都可以将对象添加到此存储桶中，并且不能更改。您可能无法删除这些对象或存储桶本身。

+
如果您为存储桶启用 S3 对象锁定，则存储桶版本控制将自动启用。

. 如果您选择了“启用 S3 对象锁定”，则可以选择为此存储桶启用“默认保留”。
+

NOTE: 您的网格管理员必须授予您以下权限link:../tenant/using-s3-object-lock.html["使用 S3 Object Lock 的特定功能"]。

+
当启用*默认保留*时，添加到存储桶的新对象将自动受到保护，免遭删除或覆盖。*默认保留*设置不适用于具有自己的保留期的对象。

+
.. 如果启用了*默认保留*，请为存储桶指定*默认保留模式*。
+
[cols="1a,2a"]
|===
| 默认保留模式 | 描述 


 a| 
治理
 a| 
*** 用户 `s3:BypassGovernanceRetention`许可可以使用 `x-amz-bypass-governance-retention: true`请求标头以绕过保留设置。
*** 这些用户可以在达到保留截止日期之前删除对象版本。
*** 这些用户可以增加、减少或删除对象的保留期限。




 a| 
Compliance
 a| 
*** 在达到保留截止日期之前，无法删除该对象。
*** 对象的保留截止日期可以增加，但不能减少。
*** 在达到该日期之前，不能删除对象的保留截止日期。


*注意*：您的电网管理员必须允许您使用合规模式。

|===
.. 如果启用了*默认保留*，请指定存储桶的*默认保留期*。
+
*默认保留期*表示从提取新对象开始，添加到此存储桶的新对象应保留多长时间。指定一个小于或等于网格管理员设置的租户最大保留期的值。

+
网格管理员创建租户时会设置最大保留期，其值可以是 1 天到 100 年。当您设置_默认_保留期时，它不能超过为最大保留期设置的值。如果需要，请您的网格管理员增加或减少最长保留期。



. [[capacity-limit]]可选，选择*启用容量限制*。
+
容量限制是此存储桶中对象可用的最大容量。该值代表逻辑量（对象大小），而不是物理量（磁盘上的大小）。

+
如果没有设置限制，则该存储桶的容量是无限的。请参阅link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage["容量限制使用情况"]了解更多信息。

. 选择*创建存储桶*。
+
存储桶已创建并添加到“存储桶”页面上的表中。

. 或者，选择“转到存储桶详细信息页面”link:viewing-s3-bucket-details.html["查看存储桶详细信息"]并执行额外的配置。

