---
permalink: tenant/creating-your-own-s3-access-keys.html 
sidebar: sidebar 
keywords: how to create your own S3 access key 
summary: 如果您使用 S3 租户并且拥有适当的权限，则可以创建自己的 S3 访问密钥。您必须拥有访问密钥才能访问您的存储桶和对象。 
---
= 创建您自己的 S3 访问密钥
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用 S3 租户并且拥有适当的权限，则可以创建自己的 S3 访问密钥。您必须拥有访问密钥才能访问您的存储桶和对象。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 您属于具有link:tenant-management-permissions.html["管理您自己的 S3 凭证或 Root 访问权限"]。


.关于此任务
您可以创建一个或多个 S3 访问密钥，以便为您的租户帐户创建和管理存储桶。创建新的访问密钥后，使用新的访问密钥 ID 和秘密访问密钥更新应用程序。为了安全起见，请不要创建超过所需数量的密钥，并删除不使用的密钥。如果您只有一个密钥并且它即将过期，请在旧密钥过期之前创建一个新密钥，然后删除旧密钥。

每个密钥可以有特定的到期时间或者没有到期时间。请遵循以下有关到期时间的准则：

* 为您的密钥设置到期时间，以限制您在特定时间段内的访问。如果您的访问密钥 ID 和秘密访问密钥意外泄露，设置较短的到期时间可以帮助降低您的风险。过期的密钥将被自动删除。
* 如果您的环境中的安全风险较低，并且您不需要定期创建新密钥，则不必为密钥设置到期时间。如果您稍后决定创建新密钥，请手动删除旧密钥。



CAUTION: 您可以使用租户管理器中显示的您帐户的访问密钥 ID 和秘密访问密钥访问属于您帐户的 S3 存储桶和对象。因此，请像保护密码一样保护访问密钥。定期轮换访问密钥，从您的帐户中删除任何未使用的密钥，并且切勿与其他用户共享。

.步骤
. 选择*存储 (S3)* > *我的访问密钥*。
+
出现“我的访问密钥”页面并列出所有现有的访问密钥。

. 选择*创建密钥*。
. 执行以下操作之一：
+
** 选择“*不设置过期时间*”来创建不会过期的密钥。  （默认）
** 选择*设置到期时间*，并设置到期日期和时间。
+

NOTE: 到期日期最长为当前日期起五年。到期时间可以从当前时间开始至少一分钟。



. 选择*创建访问密钥*。
+
出现“下载访问密钥”对话框，其中列出您的访问密钥 ID 和秘密访问密钥。

. 将访问密钥 ID 和秘密访问密钥复制到安全位置，或选择 *下载 .csv* 以保存包含访问密钥 ID 和秘密访问密钥的电子表格文件。
+

CAUTION: 复制或下载此信息之前，请勿关闭此对话框。对话框关闭后，您无法复制或下载密钥。

. 选择*完成*。
+
新密钥列在“我的访问密钥”页面上。

. 如果您的租户帐户具有 *使用网格联合连接* 权限，则可以选择使用租户管理 API 将 S3 访问密钥从源网格上的租户手动克隆到目标网格上的租户。看link:grid-federation-clone-keys-with-api.html["使用 API 克隆 S3 访问密钥"] 。

