---
permalink: tenant/enabling-or-disabling-last-access-time-updates.html 
sidebar: sidebar 
keywords: how to enable or disable last access time updates 
summary: '当网格管理员为StorageGRID系统创建信息生命周期管理 (ILM) 规则时，他们可以选择指定使用对象的最后访问时间来确定是否将该对象移动到不同的存储位置。如果您正在使用 S3 租户，则可以通过为 S3 存储桶中的对象启用上次访问时间更新来利用此类规则。' 
---
= 启用或禁用上次访问时间更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当网格管理员为StorageGRID系统创建信息生命周期管理 (ILM) 规则时，他们可以选择指定使用对象的最后访问时间来确定是否将该对象移动到不同的存储位置。如果您正在使用 S3 租户，则可以通过为 S3 存储桶中的对象启用上次访问时间更新来利用此类规则。

这些说明仅适用于包含至少一条 ILM 规则的StorageGRID系统，该规则使用 *上次访问时间* 选项作为高级过滤器或参考时间。如果您的StorageGRID系统不包含这样的规则，您可以忽略这些说明。看link:../ilm/using-last-access-time-in-ilm-rules.html["在 ILM 规则中使用上次访问时间"]了解详情。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 您属于具有link:tenant-management-permissions.html["管理所有 bucket 或 Root 访问权限"]。这些权限将覆盖组或存储桶策略中的权限设置。


.关于此任务
*上次访问时间*是 ILM 规则的*参考时间*放置指令可用的选项之一。将规则的参考时间设置为上次访问时间，可让网格管理员根据上次检索（读取或查看）对象的时间来指定将对象放置在特定的存储位置。

例如，为了确保最近查看的对象保留在更快的存储中，网格管理员可以创建 ILM 规则，指定以下内容：

* 过去一个月检索到的对象应保留在本地存储节点上。
* 过去一个月内未被取回的物品应被移至异地。


默认情况下，上次访问时间的更新是禁用的。如果您的StorageGRID系统包含使用 *上次访问时间* 选项的 ILM 规则，并且您希望此选项应用于此存储桶中的对象，则必须启用对该规则中指定的 S3 存储桶的上次访问时间更新。


CAUTION: 检索对象时更新最后访问时间可能会降低StorageGRID性能，尤其是对于小对象。

上次访问时间更新会对性能产生影响，因为StorageGRID每次检索对象时都必须执行以下额外步骤：

* 使用新的时间戳更新对象
* 将对象添加到 ILM 队列，以便可以根据当前 ILM 规则和策略重新评估它们


该表总结了当上次访问时间被禁用或启用时应用于存储桶中所有对象的行为。

[cols="1a,1a,1a,1a,1a"]
|===


.2+| 请求类型 2+| 上次访问时间禁用时的行为（默认） 2+| 启用上次访问时间时的行为 


| 上次访问时间已更新？ | 对象已添加到 ILM 评估队列？ | 上次访问时间已更新？ | 对象已添加到 ILM 评估队列？ 


 a| 
请求检索对象、其访问控制列表或其元数据
 a| 
否
 a| 
否
 a| 
是
 a| 
是



 a| 
请求更新对象的元数据
 a| 
是
 a| 
是
 a| 
是
 a| 
是



 a| 
请求列出对象或对象版本
 a| 
否
 a| 
否
 a| 
否
 a| 
否



 a| 
请求将对象从一个存储桶复制到另一个存储桶
 a| 
* 不，对于源副本
* 是的，对于目标副本

 a| 
* 不，对于源副本
* 是的，对于目标副本

 a| 
* 是的，对于源副本
* 是的，对于目标副本

 a| 
* 是的，对于源副本
* 是的，对于目标副本




 a| 
请求完成分段上传
 a| 
是的，对于组装好的物体
 a| 
是的，对于组装好的物体
 a| 
是的，对于组装好的物体
 a| 
是的，对于组装好的物体

|===
.步骤
. 从仪表板中选择 *查看存储桶*，或选择 *存储（S3）* > *存储桶*。
. 从表中选择存储桶名称。
+
出现存储桶详细信息页面。

. 从*Bucket options*选项卡中，选择*Last access time updates*折叠面板。
. 启用或禁用上次访问时间更新。
. 选择“保存更改”。

