---
permalink: tenant/index.html 
sidebar: sidebar 
keywords: use tenant account 
summary: '租户帐户允许您使用简单存储服务 (S3) REST API 或 Swift REST API 在StorageGRID系统中存储和检索对象。' 
---
= 使用租户帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租户帐户允许您使用简单存储服务 (S3) REST API 或 Swift REST API 在StorageGRID系统中存储和检索对象。



== 什么是租户帐户？

每个租户帐户都有自己的联合或本地组、用户、S3 存储桶或 Swift 容器和对象。

租户帐户可用于按不同实体隔离存储的对象。例如，多个租户帐户可用于以下任一用例：

* *企业用例：*如果在企业内部使用StorageGRID系统，则网格的对象存储可能会由组织内的不同部门隔离。例如，可能有市场营销部门、客户支持部门、人力资源部门等的租户帐户。
+

NOTE: 如果您使用 S3 客户端协议，您还可以使用 S3 存储桶和存储桶策略在企业各部门之间隔离对象。您不需要创建单独的租户帐户。请参阅实施说明link:../s3/bucket-and-group-access-policies.html["S3 存储桶和存储桶策略"]了解更多信息。

* *服务提供商用例：*如果服务提供商正在使用StorageGRID系统，则网格的对象存储可能会由租用存储的不同实体隔离。例如，可能有公司 A、公司 B、公司 C 等的租户帐户。




== 如何创建租户帐户

租户帐户由link:../admin/managing-tenants.html["使用网格管理器的StorageGRID网格管理员"]。创建租户帐户时，网格管理员指定以下内容：

* 基本信息包括租户名称、客户端类型（S3）和可选存储配额。
* 租户帐户的权限，例如租户帐户是否可以使用 S3 平台服务、配置自己的身份源、使用 S3 Select 或使用网格联合连接。
* 租户的初始根访问权限，取决于StorageGRID系统是否使用本地组和用户、身份联合或单点登录 (SSO)。


此外，如果 S3 租户账户需要遵守监管要求，网格管理员可以为StorageGRID系统启用 S3 对象锁定设置。启用 S3 对象锁定后，所有 S3 租户帐户都可以创建和管理兼容的存储桶。



=== 配置 S3 租户

经过link:../admin/creating-tenant-account.html["S3 租户帐户已创建"]，您可以访问租户管理器来执行以下任务：

* 设置身份联合（除非身份源与网格共享）
* 管理群组和用户
* 使用网格联合进行帐户克隆和跨网格复制
* 管理 S3 访问密钥
* 创建和管理 S3 存储桶
* 使用 S3 平台服务
* 使用 S3 Select
* 监控存储使用情况



TIP: 虽然您可以使用租户管理器创建和管理 S3 存储桶，但您必须使用link:../s3/index.html["S3 客户端"]或者link:use-s3-console.html["S3 控制台"]摄取和管理对象。
