---
permalink: tenant/manage-bucket-consistency.html 
sidebar: sidebar 
keywords: how to manage bucket consistency, how to change bucket consistency, read after new write, read-after-new-write, strong site, strong-site, strong global, strong-global 
summary: 一致性值可用于指定存储桶设置更改的可用性，以及在存储桶内的对象的可用性与不同存储节点和站点之间的对象的一致性之间提供平衡。您可以将一致性值更改为不同于默认值，以便客户端应用程序能够满足其操作需求。 
---
= 管理存储桶一致性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一致性值可用于指定存储桶设置更改的可用性，以及在存储桶内的对象的可用性与不同存储节点和站点之间的对象的一致性之间提供平衡。您可以将一致性值更改为不同于默认值，以便客户端应用程序能够满足其操作需求。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 您属于具有link:tenant-management-permissions.html["管理所有 bucket 或 Root 访问权限"]。这些权限将覆盖组或存储桶策略中的权限设置。




== 桶一致性指南

存储桶一致性用于确定影响该 S3 存储桶内对象的客户端应用程序的一致性。一般来说，您应该对存储桶使用“Read-after-new-write”一致性。



== [[change-bucket-consistency]]更改存储桶一致性

如果“Read-after-new-write”一致性不符合客户端应用程序的要求，您可以通过设置存储桶一致性或使用 `Consistency-Control`标头。这 `Consistency-Control`标头覆盖了存储桶一致性。


NOTE: 当您更改存储桶的一致性时，只有在更改后提取的对象才保证满足修改后的设置。

.步骤
. 从仪表板中选择 *查看存储桶*，或选择 *存储（S3）* > *存储桶*。
. 从表中选择存储桶名称。
+
出现存储桶详细信息页面。

. 从“Bucket options”选项卡中，选择“手风琴”。
. 选择对此存储桶中的对象执行的操作的一致性。
+
** *全部*：提供最高级别的一致性。所有节点立即接收数据，否则请求将失败。
** *强全局*：保证所有站点上所有客户端请求的读写一致性。
** *强站点*：保证站点内所有客户端请求的读写一致性。
** *Read-after-new-write*（默认）：为新对象提供读后写一致性，并为对象更新提供最终一致性。提供高可用性和数据保护保证。在大多数情况下推荐使用。
** *可用*：为新对象和对象更新提供最终一致性。对于 S3 存储桶，仅在需要时使用（例如，对于包含很少读取的日志值的存储桶，或者对于不存在的键的 HEAD 或 GET 操作）。不支持 S3 FabricPool存储桶。


. 选择“保存更改”。




== 更改存储桶设置时会发生什么情况

存储桶具有多个设置，这些设置会影响存储桶及其内的对象的行为。

以下存储桶设置默认使用*强*一致性。如果任何站点内没有两个或多个存储节点可用，或者某个站点不可用，则对这些设置的任何更改都可能无法使用。

* link:deleting-s3-bucket-objects.html["后台空桶删除"]
* link:enabling-or-disabling-last-access-time-updates.html["上次访问时间"]
* link:../s3/create-s3-lifecycle-configuration.html["存储桶生命周期"]
* link:../s3/bucket-and-group-access-policies.html["存储桶策略"]
* link:../s3/operations-on-buckets.html["桶标记"]
* link:changing-bucket-versioning.html["存储桶版本控制"]
* link:using-s3-object-lock.html["S3 对象锁"]
* link:../admin/reviewing-storagegrid-encryption-methods.html#bucket-encryption-table["存储桶加密"]



NOTE: 存储桶版本控制、S3 对象锁定和存储桶加密的一致性值不能设置为不强一致的值。

以下存储桶设置不使用强一致性，并且对更改具有更高的可用性。这些设置的更改可能需要一些时间才能生效。

* link:considerations-for-platform-services.html["平台服务配置：通知、复制或搜索集成"]
* link:configuring-cross-origin-resource-sharing-cors.html["CORS 配置"]
* <<change-bucket-consistency,更改存储桶一致性>>



TIP: 如果更改存储桶设置时使用的默认一致性不符合客户端应用程序的要求，则可以使用 `Consistency-Control`标题为link:../s3/put-bucket-consistency-request.html["S3 REST API"]或者使用 `reducedConsistency`或者 `force`选项link:understanding-tenant-management-api.html["租户管理 API"]。
