---
permalink: tenant/tenant-management-permissions.html 
sidebar: sidebar 
keywords: tenant management permissions 
summary: 在创建租户组之前，请考虑要分配给该组哪些权限。租户管理权限决定用户可以使用租户管理器或租户管理 API 执行哪些任务。一个用户可以属于一个或多个组。如果用户属于多个组，则权限是累积的。 
---
= 租户管理权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建租户组之前，请考虑要分配给该组哪些权限。租户管理权限决定用户可以使用租户管理器或租户管理 API 执行哪些任务。一个用户可以属于一个或多个组。如果用户属于多个组，则权限是累积的。

要登录租户管理器或使用租户管理 API，用户必须属于具有至少一个权限的组。所有可以登录的用户都可以执行以下任务：

* 查看仪表板
* 更改自己的密码（针对本地用户）


对于所有权限，组的访问模式设置决定用户是否可以更改设置和执行操作，或者是否只能查看相关设置和功能。


NOTE: 如果用户属于多个组，并且任何组设置为只读，则该用户将对所有选定的设置和功能具有只读访问权限。

您可以为组分配以下权限。请注意，S3 租户和 Swift 租户具有不同的组权限。

[cols="1a,3a,3a"]
|===
| 权限 | 描述 | 详细信息 


 a| 
Root 访问权限
 a| 
提供对租户管理器和租户管理 API 的完全访问权限。
 a| 
Swift 用户必须具有 Root 访问权限才能登录租户帐户。



 a| 
管理员
 a| 
仅限 Swift 租户。提供此租户帐户的 Swift 容器和对象的完全访问权限
 a| 
Swift 用户必须具有 Swift 管理员权限才能使用 Swift REST API 执行任何操作。



 a| 
管理您自己的 S3 凭证
 a| 
允许用户创建和删除自己的 S3 访问密钥。
 a| 
没有此权限的用户看不到 *存储 (S3)* > *我的 S3 访问密钥* 菜单选项。



 a| 
查看所有存储桶
 a| 
*S3 租户*：允许用户查看所有存储桶和存储桶配置。

*Swift 租户*：允许 Swift 用户使用租户管理 API 查看所有容器和容器配置。
 a| 
没有查看所有存储桶或管理所有存储桶权限的用户看不到*存储桶*菜单选项。

此权限已被“管理所有存储桶”权限取代。它不会影响 S3 客户端或 S3 控制台使用的 S3 存储桶或组策略。

您只能从租户管理 API 将此权限分配给 Swift 组。您不能使用租户管理器将此权限分配给 Swift 组。



 a| 
管理所有存储桶
 a| 
*S3 租户*：允许用户使用租户管理器和租户管理 API 创建和删除 S3 存储桶，并管理租户帐户中所有 S3 存储桶的设置，而无需考虑 S3 存储桶或组策略。

*Swift 租户*：允许 Swift 用户使用租户管理 API 控制 Swift 容器的一致性。
 a| 
没有查看所有存储桶或管理所有存储桶权限的用户看不到*存储桶*菜单选项。

此权限取代了查看所有存储桶的权限。它不会影响 S3 客户端或 S3 控制台使用的 S3 存储桶或组策略。

您只能从租户管理 API 将此权限分配给 Swift 组。您不能使用租户管理器将此权限分配给 Swift 组。



 a| 
管理端点
 a| 
允许用户使用租户管理器或租户管理 API 创建或编辑平台服务端点，这些端点用作StorageGRID平台服务的目标。
 a| 
没有此权限的用户看不到*平台服务端点*菜单选项。



 a| 
使用 S3 控制台选项卡
 a| 
与查看所有存储桶或管理所有存储桶权限结合使用时，允许用户从存储桶详细信息页面上的 S3 控制台选项卡查看和管理对象。
 a| 

|===