---
permalink: tenant/understanding-search-integration-service.html 
sidebar: sidebar 
keywords: how to understand search integration service 
summary: 如果您想对对象元数据使用外部搜索和数据分析服务，则可以为 S3 存储桶启用搜索集成。 
---
= 了解搜索集成服务
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想对对象元数据使用外部搜索和数据分析服务，则可以为 S3 存储桶启用搜索集成。

搜索集成服务是一种自定义StorageGRID服务，每当创建或删除对象，或者更新其元数据或标签时，它都会自动且异步地将 S3 对象元数据发送到目标端点。然后，您可以使用目标服务提供的复杂搜索、数据分析、可视化或机器学习工具来搜索、分析和洞察对象数据。

例如，您可以配置存储桶以将 S3 对象元数据发送到远程 Elasticsearch 服务。然后，您可以使用 Elasticsearch 跨存储桶执行搜索，并对对象元数据中存在的模式执行复杂的分析。

尽管可以在启用了 S3 对象锁定的存储桶上配置 Elasticsearch 集成，但对象的 S3 对象锁定元数据（包括保留截止日期和合法保留状态）将不会包含在发送到 Elasticsearch 的元数据中。


NOTE: 由于搜索集成服务会导致对象元数据被发送到目的地，因此其配置 XML 被称为“_metadata_通知配置 XML”。此配置 XML 与用于启用_事件_通知的“通知配置 XML”不同。



== 搜索集成和 S3 存储桶

您可以为任何版本化或未版本化的存储桶启用搜索集成服务。通过将元数据通知配置 XML 与指定要操作的对象以及对象元数据的目的地的存储桶关联起来，可以配置搜索集成。

元数据通知以 JSON 文档的形式生成，该文档以存储桶名称、对象名称和版本 ID（如果有）命名。每个元数据通知除了包含对象的所有标签和用户元数据之外，还包含该对象的一组标准系统元数据。


NOTE: 对于标签和用户元数据， StorageGRID将日期和数字作为字符串或 S3 事件通知传递给 Elasticsearch。要配置 Elasticsearch 将这些字符串解释为日期或数字，请按照 Elasticsearch 的动态字段映射和映射日期格式的说明进行操作。在配置搜索集成服务之前，您必须在索引上启用动态字段映射。文档被索引后，您无法在索引中编辑文档的字段类型。



== 搜索通知

每当出现以下情况时，就会生成元数据通知并排队等待传送：

* 已创建一个对象。
* 对象被删除，包括由于网格的 ILM 策略操作而删除对象的情况。
* 添加、更新或删除对象元数据或标签。更新时总是会发送完整的元数据和标签集——而不仅仅是更改的值。


将元数据通知配置 XML 添加到存储桶后，系统会为您创建的任何新对象以及通过更新其数据、用户元数据或标签而修改的任何对象发送通知。但是，不会针对存储桶中已经存在的任何对象发送通知。为了确保存储桶中所有对象的对象元数据都发送到目标，您应该执行以下操作之一：

* 在创建存储桶之后和添加任何对象之前立即配置搜索集成服务。
* 对存储桶中已有的所有对象执行操作，该操作将触发元数据通知消息发送到目标。




== 搜索集成服务和 Elasticsearch

StorageGRID搜索集成服务支持 Elasticsearch 集群作为目标。与其他平台服务一样，目的地在端点中指定，该端点的 URN 用于服务的配置 XML。使用 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^]确定支持的 Elasticsearch 版本。
