---
permalink: vmware/collecting-information-about-your-deployment-environment.html 
sidebar: sidebar 
keywords: how to collect information about your deployment environment 
summary: 在部署网格节点之前，您必须收集有关网络配置和 VMware 环境的信息。 
---
= 收集有关部署环境的信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在部署网格节点之前，您必须收集有关网络配置和 VMware 环境的信息。


NOTE: 对所有节点执行一次安装比现在安装一些节点、稍后安装一些节点更有效率。



== VMware 信息

您必须访问部署环境并收集有关 VMware 环境的信息；为网格、管理和客户端网络创建的网络；以及您计划用于存储节点的存储卷类型。

您必须收集有关 VMware 环境的信息，包括以下内容：

* 具有适当权限以完成部署的 VMware vSphere 帐户的用户名和密码。
* 每个StorageGRID节点虚拟机的主机、数据存储和网络配置信息。



NOTE: VMware live vMotion 会导致虚拟机时钟时间跳跃，并且不支持任何类型的网格节点。虽然很少见，但不正确的时钟时间可能会导致数据丢失或配置更新。



== 电网信息

您必须收集有关为StorageGRID网格网络创建的 VMware 网络的信息（必需），包括：

* 网络名称。
* 用于分配 IP 地址的方法，静态或 DHCP。
+
** 如果您使用静态 IP 地址，则每个网格节点所需的网络详细信息（IP 地址、网关、网络掩码）。
** 如果您使用 DHCP，则为网格网络上主管理节点的 IP 地址。看link:how-grid-nodes-discover-primary-admin-node.html["网格节点如何发现主管理节点"]了解更多信息。






== 管理网络信息

对于将连接到可选StorageGRID管理网络的节点，您必须收集有关为此网络创建的 VMware 网络的信息，包括：

* 网络名称。
* 用于分配 IP 地址的方法，静态或 DHCP。
+
** 如果您使用静态 IP 地址，则每个网格节点所需的网络详细信息（IP 地址、网关、网络掩码）。
** 如果您使用 DHCP，则为网格网络上主管理节点的 IP 地址。看link:how-grid-nodes-discover-primary-admin-node.html["网格节点如何发现主管理节点"]了解更多信息。


* 管理网络的外部子网列表 (ESL)。




== 客户网络信息

对于将连接到可选StorageGRID客户端网络的节点，您必须收集有关为此网络创建的 VMware 网络的信息，包括：

* 网络名称。
* 用于分配 IP 地址的方法，静态或 DHCP。
* 如果您使用静态 IP 地址，则每个网格节点所需的网络详细信息（IP 地址、网关、网络掩码）。




== 有关附加接口的信息

安装节点后，您可以选择在 vCenter 中向 VM 添加中继或访问接口。例如，您可能想要向管理节点或网关节点添加中继接口，以便可以使用 VLAN 接口来隔离属于不同应用程序或租户的流量。或者，您可能想要添加一个访问接口以在高可用性 (HA) 组中使用。

您添加的接口显示在网格管理器中的 VLAN 接口页面和 HA 组页面上。

* 如果添加中继接口，请为每个新的父接口配置一个或多个 VLAN 接口。看link:../admin/configure-vlan-interfaces.html["配置 VLAN 接口"] 。
* 如果添加访问接口，则必须将其直接添加到 HA 组。看link:../admin/configure-high-availability-group.html["配置高可用性组"] 。




== 虚拟存储节点的存储卷

您必须收集基于虚拟机的存储节点的以下信息：

* 您计划添加的存储卷（存储 LUN）的数量和大小。请参阅link:storage-and-performance-requirements.html["存储和性能要求"]。




== 电网配置信息

您必须收集信息来配置您的电网：

* 电网许可证
* 网络时间协议 (NTP) 服务器 IP 地址
* DNS 服务器 IP 地址

