---
permalink: vmware/downloading-and-extracting-storagegrid-installation-files.html 
sidebar: sidebar 
keywords: how to download vmware installation files 
summary: 您必须下载StorageGRID安装档案并提取文件。或者，您可以手动验证安装包中的文件。 
---
= 下载并解压StorageGRID安装文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须下载StorageGRID安装档案并提取文件。或者，您可以手动验证安装包中的文件。

.步骤
. 前往 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp StorageGRID下载页面"^]。
. 选择下载最新版本的按钮，或从下拉菜单中选择另一个版本并选择*Go*。
. 使用您的NetApp帐户的用户名和密码Sign in。
. 如果出现“警告/必读”声明，请阅读并选中复选框。
+

CAUTION: 安装StorageGRID版本后，您必须应用任何所需的修补程序。有关详细信息，请参阅link:../maintain/storagegrid-hotfix-procedure.html["恢复和维护说明中的修补程序"]

. 阅读最终用户许可协议，选中复选框，然后选择*接受并继续*。
. 在 *安装StorageGRID* 列中，选择 VMware 的 .tgz 或 .zip 安装存档。
+

NOTE: 使用 `.zip`如果您在服务笔记本电脑上运行 Windows，则该文件。

. 保存安装档案。
. [[vmware-download-verification-package]]如果您需要验证安装存档：
+
.. 下载StorageGRID代码签名验证包。此包的文件名使用以下格式 `StorageGRID_<version-number>_Code_Signature_Verification_Package.tar.gz`， 在哪里 `<version-number>`是StorageGRID软件版本。
.. 按照步骤link:../vmware/download-files-verify.html["手动验证安装文件"]。


. 从安装档案中提取文件。
. 选择您需要的文件。
+
您所需的文件取决于您计划的网格拓扑以及您将如何部署StorageGRID系统。




NOTE: 表中列出的路径是相对于提取的安装档案所安装的顶级目录的。

[cols="1a,1a"]
|===
| 路径和文件名 | 描述 


| ./vsphere/README  a| 
描述StorageGRID下载文件中包含的所有文件的文本文件。



| ./vsphere/NLF000000.txt  a| 
免费许可证不提供任何产品支持权利。



| NetApp版本-SHA.vmdk  a| 
用作创建网格节点虚拟机的模板的虚拟机磁盘文件。



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
开放虚拟化格式模板文件(`.ovf`) 和清单文件(`.mf`) 用于部署主管理节点。



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
模板文件(`.ovf`) 和清单文件(`.mf`) 用于部署非主管理节点。



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
模板文件(`.ovf`) 和清单文件(`.mf`) 用于部署网关节点。



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
模板文件(`.ovf`) 和清单文件(`.mf`) 用于部署基于虚拟机的存储节点。



| 部署脚本工具 | 描述 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
用于自动部署虚拟网格节点的 Bash shell 脚本。



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
与以下文件一起使用的示例配置文件 `deploy-vsphere-ovftool.sh`脚本。



| ./vsphere/configure-storagegrid.py  a| 
用于自动配置StorageGRID系统的 Python 脚本。



| ./vsphere/configure-sga.py  a| 
用于自动配置StorageGRID设备的 Python 脚本。



| ./vsphere/storagegrid-ssoauth.py  a| 
启用单点登录 (SSO) 后，您可以使用该示例 Python 脚本登录到网格管理 API。您还可以使用此脚本进行 Ping Federate 集成。



| ./vsphere/configure-storagegrid.sample.json  a| 
与以下文件一起使用的示例配置文件 `configure-storagegrid.py`脚本。



| ./vsphere/configure-storagegrid.blank.json  a| 
用于 `configure-storagegrid.py`脚本。



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
当使用 Active Directory 或 Ping Federate 启用单点登录 (SSO) 时，您可以使用该示例 Python 脚本登录到网格管理 API。



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
同伴调用的辅助脚本 `storagegrid-ssoauth-azure.py`用于与 Azure 执行 SSO 交互的 Python 脚本。



| ./vsphere/extras/api-schemas  a| 
StorageGRID的 API 模式。

*注意*：在执行升级之前，如果您没有非生产StorageGRID环境进行升级兼容性测试，则可以使用这些模式来确认您编写的任何使用StorageGRID管理 API 的代码是否与新的StorageGRID版本兼容。

|===