---
permalink: rhel/configuring-host-storage.html 
sidebar: sidebar 
keywords: how to configure host storage 
summary: 您必须为每个主机分配块存储卷。 
---
= 配置主机存储
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须为每个主机分配块存储卷。

.开始之前
您已阅读了以下主题，它们提供了完成此任务所需的信息：

* link:storage-and-performance-requirements.html["存储和性能要求"]
* link:node-container-migration-requirements.html["节点容器迁移要求"]


.关于此任务
将块存储卷 (LUN) 分配给主机时，请使用“存储要求”中的表格确定以下内容：

* 每个主机所需的卷数（基于将在该主机上部署的节点数量和类型）
* 每个卷的存储类别（即系统数据或对象数据）
* 每卷大小


在主机上部署StorageGRID节点时，您将使用此信息以及 Linux 分配给每个物理卷的持久名称。


NOTE: 您不需要对任何这些卷进行分区、格式化或挂载；您只需要确保它们对主机可见。


NOTE: 仅元数据存储节点只需要一个对象数据 LUN。

避免使用“原始”特殊设备文件(`/dev/sdb`（例如）在编写卷名列表时。这些文件可能会在主机重启后发生变化，这会影响系统的正常运行。如果您正在使用 iSCSI LUN 和设备映射器多路径，请考虑在 `/dev/mapper`目录，特别是当您的 SAN 拓扑包括到共享存储的冗余网络路径时。或者，您可以使用系统创建的软链接 `/dev/disk/by-path/`用于您的持久设备名称。

例如：

[listing]
----
ls -l
$ ls -l /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:00:07.1-ata-2 -> ../../sr0
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:1:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:2:0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Sep 19 18:53 pci-0000:03:00.0-scsi-0:0:3:0 -> ../../sdd
----
每次安装的结果都会有所不同。

为每个块存储卷分配友好名称，以简化初始StorageGRID安装和未来的维护程序。如果您使用设备映射器多路径驱动程序对共享存储卷进行冗余访问，则可以使用 `alias`你的领域 `/etc/multipath.conf`文件。

例如：

[listing]
----
multipaths {
     multipath {
          wwid 3600a09800059d6df00005df2573c2c30
          alias docker-storage-volume-hostA
     }
     multipath {
          wwid 3600a09800059d6df00005df3573c2c30
          alias sgws-adm1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df4573c2c30
          alias sgws-adm1-audit-logs
     }
     multipath {
          wwid 3600a09800059d6df00005df5573c2c30
          alias sgws-adm1-tables
     }
     multipath {
          wwid 3600a09800059d6df00005df6573c2c30
          alias sgws-gw1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-var-local
     }
     multipath {
          wwid 3600a09800059d6df00005df7573c2c30
          alias sgws-sn1-rangedb-0
     }
     …
----
以这种方式使用别名字段会导致别名在 `/dev/mapper`主机上的目录，允许您在配置或维护操作需要指定块存储卷时指定一个友好且易于验证的名称。


NOTE: 如果您要设置共享存储以支持StorageGRID节点迁移并使用设备映射器多路径，则可以创建并安装通用 `/etc/multipath.conf`在所有同地主机上。只需确保在每个主机上使用不同的容器引擎存储卷。使用别名并在每个容器引擎存储卷 LUN 的别名中包含目标主机名将使其易于记忆，因此建议这样做。


NOTE: 不再支持将 Docker 作为纯软件部署的容器引擎。Docker 将在未来的版本中被另一个容器引擎取代。

.相关信息
link:configuring-docker-storage-volume.html["配置容器引擎存储卷"]
