---
permalink: admin/admin-group-permissions.html 
sidebar: sidebar 
keywords: admin group permissions 
summary: 创建管理员用户组时，您可以选择一个或多个权限来控制对网格管理器特定功能的访问。然后，您可以将每个用户分配到一个或多个管理组，以确定该用户可以执行哪些任务。 
---
= 管理员组权限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
创建管理员用户组时，您可以选择一个或多个权限来控制对网格管理器特定功能的访问。然后，您可以将每个用户分配到一个或多个管理组，以确定该用户可以执行哪些任务。

您必须为每个组分配至少一个权限；否则，属于该组的用户将无法登录网格管理器或网格管理 API。

默认情况下，属于具有至少一个权限的组的任何用户都可以执行以下任务：

* Sign in网格管理器
* 查看仪表板
* 查看节点页面
* 查看当前和已解决的警报
* 更改自己的密码（仅限本地用户）
* 查看配置和维护页面上提供的某些信息




== 权限与访问模式的交互

对于所有权限，组的*访问模式*设置决定用户是否可以更改设置和执行操作，或者是否只能查看相关设置和功能。如果用户属于多个组，并且任何组设置为*只读*，则该用户将对所有选定的设置和功能具有只读访问权限。

以下部分描述了创建或编辑管理员组时可以分配的权限。任何未明确提及的功能都需要*Root 访问*权限。



== Root 访问权限

此权限提供对所有网格管理功能的访问。



== 更改租户 root 密码

此权限提供对租户页面上的*更改 root 密码*选项的访问权限，允许您控制谁可以更改租户本地 root 用户的密码。当启用 S3 密钥导入功能时，此权限也用于迁移 S3 密钥。没有此权限的用户无法看到*更改 root 密码*选项。


NOTE: 要授予对包含“更改根密码”选项的“租户”页面的访问权限，还需分配“租户帐户”权限。



== 电网拓扑页面配置

此权限提供对 *SUPPORT* > *Tools* > *Grid topology* 页面上的配置选项卡的访问权限。


NOTE: 网格拓扑页面已被弃用，并将在未来版本中删除。



== ILM

此权限提供对以下 *ILM* 菜单选项的访问：

* 规则
* 策略
* 策略标签
* 存储池
* 存储等级
* 区域
* 对象元数据查找



NOTE: 用户必须具备*其他电网配置*和*电网拓扑页面配置*权限才能管理存储等级。



== 维护

用户必须具有维护权限才能使用这些选项：

* *配置* > *访问控制*：
+
** 电网密码


* *配置* > *网络*：
+
** S3 端点域名


* *维护* > *任务*：
+
** 退役
** 扩展
** 对象存在性检查
** 恢复


* *维护* > *系统*：
+
** 恢复包
** 软件更新


* *支持* > *工具*：
+
** 日志




没有维护权限的用户可以查看但不能编辑以下页面：

* *维护* > *网络*：
+
** DNS 服务器
** 网格网络
** NTP 服务器


* *维护* > *系统*：
+
** 许可证


* *配置* > *网络*：
+
** S3 端点域名


* *配置* > *安全*：
+
** 证书


* *配置* > *监控*：
+
** 审计和系统日志服务器






== 管理警报

此权限提供对管理警报选项的访问。用户必须拥有此权限才能管理静默、警报通知和警报规则。



== 指标查询

此权限提供以下访问权限：

* *支持* > *工具* > *指标*页面
* 使用网格管理 API 的 *Metrics* 部分自定义 Prometheus 指标查询
* 包含指标的网格管理器仪表板卡




== 对象元数据查找

此权限提供对 *ILM* > *对象元数据查找* 页面的访问权限。



== 其他电网配置

此权限提供对其他网格配置选项的访问。


TIP: 要查看这些附加选项，用户还必须具有*网格拓扑页面配置*权限。

* 工业光魔（ILM）：
+
** 存储等级


* *配置* > *系统*：
* *支持* > *其他*：
+
** 链路成本






== 存储设备管理员

此权限提供：

* 通过网格管理器访问存储设备上的 E 系列SANtricity系统管理器。
* 能够在支持这些操作的设备的“管理驱动器”选项卡上执行故障排除和维护任务。




== 租户帐户

此权限提供以下功能：

* 访问租户页面，您可以在其中创建、编辑和删除租户帐户
* 查看现有的流量分类策略
* 查看包含租户详细信息的网格管理器仪表板卡

