---
permalink: admin/change-node-console-password.html 
sidebar: sidebar 
keywords: node console password, console password, change password, password 
summary: 网格中的每个节点都有一个唯一的节点控制台密码，您需要该密码才能登录该节点。按照以下步骤更改网格中每个节点的节点控制台密码。密码存储在恢复包中。 
---
= 更改节点控制台密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
网格中的每个节点都有一个唯一的节点控制台密码，您需要该密码才能登录该节点。使用这些步骤来更改网格中每个节点的每个唯一节点控制台密码。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:admin-group-permissions.html["维护或 Root 访问权限"]。
* 您拥有当前的配置密码。


.关于此任务
使用节点控制台密码通过 SSH 以“管理员”身份登录节点，或通过 VM/物理控制台连接以 root 用户身份登录。更改节点控制台密码过程会为网格中的每个节点创建新密码，并将密码存储在更新的 `Passwords.txt`恢复包中的文件。密码列在 Passwords.txt 文件的密码列中。


NOTE: 节点间通信使用的 SSH 密钥有单独的 SSH 访问密码。此过程不会更改 SSH 访问密码。



== 访问向导

.步骤
. 选择*配置* > *访问控制* > *电网密码*。
. 在*更改节点控制台密码*下，选择*进行更改*。




== 输入配置密码

.步骤
. 输入您的网格的配置密码。
. 选择*继续*。




== [[download-current]]下载当前恢复包

在更改节点控制台密码之前，请下载当前的恢复包。如果任何节点的密码更改过程失败，您可以使用此文件中的密码。

.步骤
. 选择*下载恢复包*。
. 复制恢复包文件(`.zip`）到两个安全、可靠且独立的位置。
+

CAUTION: 恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。

. 选择*继续*。
. 当确认对话框出现时，如果您准备好开始更改节点控制台密码，请选择*是*。
+
一旦该过程开始，您就无法取消。





== 更改节点控制台密码

当节点控制台密码进程启动时，将生成一个包含新密码的新恢复包。然后，在每个节点上更新密码。

.步骤
. 等待新的恢复包生成，这可能需要几分钟。
. 选择*下载新的恢复包*。
. 下载完成后：
+
.. 打开 `.zip`文件。
.. 确认您可以访问内容，包括 `Passwords.txt`文件，其中包含新的节点控制台密码。
.. 复制新的恢复包文件(`.zip`）到两个安全、可靠且独立的地点。
+

CAUTION: 不要覆盖旧的恢复包。

+
恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。



. 选中复选框表示您已下载新的恢复包并验证了内容。
. 选择*更改节点控制台密码*并等待所有节点更新新密码。这可能需要几分钟。
+
如果所有节点的密码都已更改，则会出现绿色的成功横幅。转至下一步。

+
如果更新过程中出现错误，横幅消息会列出密码更改失败的节点数。系统将自动在密码更改失败的任何节点上重试该过程。如果该过程结束时某些节点仍未更改密码，则会出现“重试”按钮。

+
如果一个或多个节点的密码更新失败：

+
.. 查看表中列出的错误消息。
.. 解决问题。
.. 选择*重试*。
+

NOTE: 重试仅更改在前一次密码更改尝试中失败的节点上的节点控制台密码。



. 更改所有节点的节点控制台密码后，删除<<download-current,您下载的第一个恢复包>>。
. 或者，使用*恢复包*链接下载新恢复包的附加副本。

