---
permalink: admin/changing-browser-session-timeout-interface.html 
sidebar: sidebar 
keywords: security, browser inactivity timeout, management API stack track 
summary: 通过界面安全设置，您可以控制当用户处于非活动状态的时间超过指定时间时是否将其注销，以及是否在 API 错误响应中包含堆栈跟踪。 
---
= 更改接口安全设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过界面安全设置，您可以控制当用户处于非活动状态的时间超过指定时间时是否将其注销，以及是否在 API 错误响应中包含堆栈跟踪。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:admin-group-permissions.html["Root访问权限"]。


.关于此任务
*安全设置*页面包括*浏览器不活动超时*和*管理 API 堆栈跟踪*设置。

浏览器不活动超时:: 指示用户注销之前浏览器可以处于非活动状态的时间。默认值为 15 分钟。
+
--
浏览器不活动超时也受以下因素控制：

* 一个单独的、不可配置的StorageGRID计时器，用于系统安全。每个用户的身份验证令牌在用户登录 16 小时后过期。当用户的身份验证过期时，该用户将自动注销，即使浏览器不活动超时已禁用或尚未达到浏览器超时值。要更新令牌，用户必须重新登录。
* 身份提供者的超时设置，假设为StorageGRID启用了单点登录 (SSO)。
+
如果启用了 SSO 并且用户的浏览器超时，则用户必须重新输入其 SSO 凭据才能再次访问StorageGRID 。看link:configuring-sso.html["配置单点登录"] 。



--
管理 API 堆栈跟踪:: 控制是否在网格管理器和租户管理器 API 错误响应中返回堆栈跟踪。
+
--
默认情况下此选项是禁用的，但您可能希望为测试环境启用此功能。一般来说，您应该在生产环境中禁用堆栈跟踪，以避免在发生 API 错误时泄露内部软件详细信息。

--


.步骤
. 选择*配置* > *安全* > *安全设置*。
. 选择“*接口*”选项卡。
. 要更改浏览器不活动超时设置：
+
.. 展开手风琴。
.. 要更改超时期限，请指定 60 秒到 7 天之间的值。默认超时时间为 15 分钟。
.. 要禁用此功能，请取消选中该复选框。
.. 选择*保存*。
+
新设置不会影响当前已登录的用户。用户必须重新登录或刷新浏览器才能使新的超时设置生效。



. 要更改管理 API 堆栈跟踪的设置：
+
.. 展开手风琴。
.. 选中该复选框以在网格管理器和租户管理器 API 错误响应中返回堆栈跟踪。
+

CAUTION: 在生产环境中禁用堆栈跟踪，以避免在发生 API 错误时泄露内部软件详细信息。

.. 选择*保存*。



