---
permalink: admin/change-ssh-access-passwords.html 
sidebar: sidebar 
keywords: ssh access keys, change ssh access keys 
summary: 更改管理节点的 SSH 访问密码还会更新网格中每个节点的唯一内部 SSH 密钥集。主管理节点使用这些 SSH 密钥通过安全、无密码的身份验证访问节点。 
---
= 更改管理节点的 SSH 访问密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更改管理节点的 SSH 访问密码还会更新网格中每个节点的唯一内部 SSH 密钥集。主管理节点使用这些 SSH 密钥通过安全、无密码的身份验证访问节点。

使用 SSH 密钥以以下身份登录节点 `admin`或者虚拟机或物理控制台连接上的 root 用户。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:admin-group-permissions.html["维护或 Root 访问权限"]。
* 您拥有当前的配置密码。


.关于此任务
管理节点的新访问密码和每个节点的新内部密钥存储在 `Passwords.txt`恢复包中的文件。密钥列在该文件中的密码列中。

节点间通信使用的 SSH 密钥有单独的 SSH 访问密码。这些不会因该过程而改变。



== 访问向导

.步骤
. 选择*配置* > *访问控制* > *电网密码*。
. 在*更改 SSH 密钥*下，选择*进行更改*。




== [[download-current]]下载当前恢复包

在更改 SSH 访问密钥之前，请下载当前的恢复包。如果任何节点的密钥更改过程失败，您可以使用此文件中的密钥。

.步骤
. 输入您的网格的配置密码。
. 选择*下载恢复包*。
. 复制恢复包文件(`.zip`）到两个安全、可靠且独立的位置。
+

CAUTION: 恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。

. 选择*继续*。
. 当确认对话框出现时，如果您准备好开始更改 SSH 访问密钥，请选择“是”。
+

CAUTION: 一旦该过程开始，您就无法取消。





== 更改 SSH 访问密钥

当更改 SSH 访问密钥过程开始时，将生成一个包含新密钥的新恢复包。然后，在每个节点上更新密钥。

.步骤
. 等待新的恢复包生成，这可能需要几分钟。
. 当“下载新的恢复包”按钮启用时，选择“*下载新的恢复包*”并保存新的恢复包文件(`.zip`）到两个安全、可靠且独立的位置。
. 下载完成后：
+
.. 打开 `.zip`文件。
.. 确认您可以访问内容，包括 `Passwords.txt`文件，其中包含新的 SSH 访问密钥。
.. 复制新的恢复包文件(`.zip`）到两个安全、可靠且独立的地点。
+

CAUTION: 不要覆盖旧的恢复包。

+
恢复包文件必须是安全的，因为它包含可用于从StorageGRID系统获取数据的加密密钥和密码。



. 等待密钥在每个节点上更新，这可能需要几分钟。
+
如果所有节点的密钥都发生了更改，则会出现绿色的成功横幅。

+
如果更新过程中出现错误，横幅消息会列出未能更改密钥的节点数。系统将自动在密钥更改失败的任何节点上重试该过程。如果该过程结束时某些节点仍未更改密钥，则会出现“重试”按钮。

+
如果一个或多个节点的密钥更新失败：

+
.. 查看表中列出的错误消息。
.. 解决问题。
.. 选择*重试*。
+
重试只会更改之前密钥更改尝试期间失败的节点上的 SSH 访问密钥。



. 在所有节点的 SSH 访问密钥更改后，删除<<download-current,您下载的第一个恢复包>>。
. 或者，选择 *维护* > *系统* > *恢复包* 来下载新恢复包的额外副本。

