---
permalink: admin/creating-tenant-account.html 
sidebar: sidebar 
keywords: create tenant, tenant account 
summary: 您必须创建至少一个租户帐户来控制对StorageGRID系统中存储的访问。 
---
= 创建租户帐户
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须创建至少一个租户帐户来控制对StorageGRID系统中存储的访问。

创建租户帐户的步骤取决于link:using-identity-federation.html["身份联合"]和link:configuring-sso.html["单点登录"]是否配置，以及用于创建租户帐户的网格管理器帐户是否属于具有 Root 访问权限的管理员组。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:admin-group-permissions.html["根访问权限或租户帐户权限"]。
* 如果租户帐户将使用为网格管理器配置的身份源，并且您想要将租户帐户的 Root 访问权限授予联合组，则您已将该联合组导入网格管理器。您不需要为该管理组分配任何网格管理器权限。看link:managing-admin-groups.html["管理管理员组"] 。
* 如果您希望允许 S3 租户克隆帐户数据并使用网格联合连接将存储桶对象复制到另一个网格：
+
** 你有link:grid-federation-create-connection.html["配置电网联合连接"]。
** 连接状态为*已连接*。
** 您拥有 Root 访问权限。
** 您已查看了以下注意事项link:grid-federation-manage-tenants.html["管理电网联合的允许租户"]。
** 如果租户帐户将使用为网格管理器配置的身份源，则您已将相同的联合组导入两个网格上的网格管理器。
+
当您创建租户时，您将选择此组以拥有源和目标租户帐户的初始 Root 访问权限。

+

TIP: 如果在创建租户之前两个网格上都不存在此管理组，则该租户不会被复制到目标。







== 访问向导

.步骤
. 选择*租户*。
. 选择“*创建*”。




== 输入详细信息

.步骤
. 输入租户的详细信息。
+
[cols="1a,3a"]
|===
| 字段 | 描述 


 a| 
名称
 a| 
租户帐户的名称。租户名称不需要是唯一的。创建租户帐户时，它会收到一个唯一的 20 位帐户 ID。



 a| 
描述（可选）
 a| 
帮助识别租户的描述。

如果您正在创建将使用网格联合连接的租户，则可以选择使用此字段来帮助识别哪个是源租户，哪个是目标租户。例如，在网格 1 上创建的租户的描述也会出现在复制到网格 2 的租户中：“此租户是在网格 1 上创建的。”



 a| 
客户端类型
 a| 
此租户将使用的客户端协议类型，*S3* 或 *Swift*。

*注意*：对 Swift 客户端应用程序的支持已被弃用，并将在未来的版本中删除。



 a| 
存储配额（可选）
 a| 
如果您希望该租户拥有存储配额，请为配额和单位指定一个数值。

|===
. 选择*继续*。




== [[admin-tenant-select-permissions]]选择权限

.步骤
. 或者，选择您希望此租户拥有的基本权限。
+

NOTE: 其中一些权限有额外的要求。有关详细信息，请选择每个权限的帮助图标。

+
[cols="1a,3a"]
|===
| 权限 | 如果选择... 


 a| 
允许平台服务
 a| 
租户可以使用CloudMirror等S3平台服务。看link:../admin/manage-platform-services-for-tenants.html["管理 S3 租户帐户的平台服务"] 。



 a| 
使用自己的身份源
 a| 
租户可以为联合组和用户配置和管理自己的身份源。如果您有以下情况，则此选项被禁用link:../admin/configuring-sso.html["配置 SSO"]适用于您的StorageGRID系统。



 a| 
允许 S3 选择
 a| 
租户可以发出 S3 SelectObjectContent API 请求来过滤和检索对象数据。看link:../admin/manage-s3-select-for-tenant-accounts.html["管理租户帐户的 S3 Select"] 。

*重要*：SelectObjectContent 请求可能会降低所有 S3 客户端和所有租户的负载均衡器性能。仅在需要时且仅对受信任的租户启用此功能。

|===
. 或者，选择您希望此租户拥有的高级权限。
+
[cols="1a,3a"]
|===
| 权限 | 如果选择... 


 a| 
电网联合连接
 a| 
租户可以使用电网联合连接，它可以：

** 导致此租户以及添加到帐户的所有租户组和用户从此网格（_源网格_）克隆到所选连接中的另一个网格（_目标网格_）。
** 允许此租户在每个网格上的相应存储桶之间配置跨网格复制。


看link:../admin/grid-federation-manage-tenants.html["管理电网联合的允许租户"] 。



 a| 
S3 对象锁
 a| 
允许租户使用 S3 Object Lock 的特定功能：

** *设置最长保留期* 定义从提取新对象开始，添加到此存储桶的新对象应保留多长时间。
** *允许合规模式*可防止用户在保留期内覆盖或删除受保护的对象版本。


|===
. 选择*继续*。




== 定义根访问权限并创建租户

.步骤
. 根据您的StorageGRID系统是否使用身份联合、单点登录 (SSO) 或两者，定义租户帐户的根访问权限。
+
[cols="1a,2a"]
|===
| 选项 | 执行此操作 


 a| 
如果未启用身份联合
 a| 
指定以本地 root 用户身份登录租户时使用的密码。



 a| 
如果启用了身份联合
 a| 
.. 选择一个现有的联合组，为租户提供 Root 访问权限。
.. 或者，指定以本地 root 用户身份登录租户时使用的密码。




 a| 
如果同时启用身份联合和单点登录 (SSO)
 a| 
选择一个现有的联合组，为租户提供 Root 访问权限。没有本地用户可以登录。

|===
. 选择*创建租户*。
+
出现成功消息，并且新租户列在“租户”页面上。要了解如何查看租户详细信息和监控租户活动，请参阅link:../monitor/monitoring-tenant-activity.html["监控租户活动"]。

+

NOTE: 根据网络连接、节点状态和 Cassandra 操作，在整个网格中应用租户设置可能需要 15 分钟或更长时间。

. 如果您为租户选择了“使用网格联合连接”权限：
+
.. 确认相同的租户已复制到连接中的另一个网格。两个网格上的租户将具有相同的 20 位帐户 ID、名称、描述、配额和权限。
+

NOTE: 如果您看到错误消息“创建租户时没有克隆”，请参阅link:grid-federation-troubleshoot.html["解决网格联合错误"]。

.. 如果您在定义 root 访问权限时提供了本地 root 用户密码，link:changing-password-for-tenant-local-root-user.html["更改本地 root 用户的密码"]对于复制的租户。
+

TIP: 本地 root 用户在密码更改之前无法登录目标网格上的租户管理器。







== Sign in租户（可选）

根据需要，您可以立即登录新租户以完成配置，也可以稍后登录租户。登录步骤取决于您是否使用默认端口（443）或受限端口登录到网格管理器。看link:controlling-access-through-firewalls.html["控制外部防火墙的访问"] 。



=== 立即Sign in

[cols="1a,3a"]
|===
| 条件 | 操作 


 a| 
端口 443 并为本地 root 用户设置密码
 a| 
. 选择*以 rootSign in*。
+
当您登录时，会出现用于配置存储桶、身份联合、组和用户的链接。

. 选择链接来配置租户帐户。
+
每个链接都会打开租户管理器中的相应页面。要完成该页面，请参阅link:../tenant/index.html["租户帐户使用说明"]。





 a| 
端口 443 并且您没有为本地 root 用户设置密码
 a| 
选择*Sign in*，然后输入根访问联合组中用户的凭据。



 a| 
受限端口
 a| 
. 选择“完成”
. 在租户表中选择“*受限*”以了解有关访问此租户帐户的更多信息。
+
租户管理器的 URL 格式如下：

+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_`是管理节点的完全限定域名或 IP 地址
** `_port_`是仅限租户的端口
** `_20-digit-account-id_`是租户的唯一帐户ID




|===


=== 稍后Sign in

[cols="1a,3a"]
|===
| 条件 | 做其中之一... 


 a| 
端口 443
 a| 
* 从网格管理器中，选择 *TENANTS*，然后选择租户名称右侧的 *Sign in*。
* 在 Web 浏览器中输入租户的 URL：
+
`https://_FQDN_or_Admin_Node_IP_/?accountId=_20-digit-account-id_/`

+
** `_FQDN_or_Admin_Node_IP_`是管理节点的完全限定域名或 IP 地址
** `_20-digit-account-id_`是租户的唯一帐户ID






 a| 
受限端口
 a| 
* 从网格管理器中，选择*TENANTS*，然后选择*Restricted*。
* 在 Web 浏览器中输入租户的 URL：
+
`https://_FQDN_or_Admin_Node_IP:port_/?accountId=_20-digit-account-id_`

+
** `_FQDN_or_Admin_Node_IP_`是管理节点的完全限定域名或 IP 地址
** `_port_`是仅限租户的限制端口
** `_20-digit-account-id_`是租户的唯一帐户ID




|===


== 配置租户

按照link:../tenant/index.html["使用租户帐户"]管理租户组和用户、S3 访问密钥、存储桶、平台服务以及帐户克隆和跨网格复制。
