---
permalink: admin/creating-traffic-classification-policies.html 
sidebar: sidebar 
keywords: traffic classification, network traffic, traffic limits, policy 
summary: 如果您想要通过存储桶、租户、IP 子网或负载均衡器端点监控并选择性地限制网络流量，则可以创建流量分类策略。或者，您可以根据带宽、并发请求数或请求率设置策略限制。 
---
= 创建流量分类策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要监控，则可以创建流量分类策略，并选择性地通过存储桶、存储桶正则表达式、CIDR、负载均衡器端点或租户限制网络流量。或者，您可以根据带宽、并发请求数或请求率设置策略限制。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:admin-group-permissions.html["Root访问权限"]。
* 您已创建想要匹配的任何负载均衡器端点。
* 您已创建任何想要匹配的租户。


.步骤
. 选择*配置* > *网络* > *流量分类*。
. 选择“*创建*”。
. 输入策略的名称和描述（可选），然后选择*继续*。
+
例如，描述此流量分类策略适用于什么以及它将限制什么。

. 选择*添加规则*并指定以下详细信息以为策略创建一个或多个匹配规则。您创建的任何策略都应至少有一条匹配规则。选择*继续*。
+
[cols="1a,3a"]
|===
| 字段 | 描述 


 a| 
类型
 a| 
选择匹配规则适用的流量类型。流量类型包括存储桶、存储桶正则表达式、CIDR、负载均衡器端点和租户。



 a| 
匹配值
 a| 
输入与所选类型匹配的值。

** 存储桶：输入一个或多个存储桶名称。
** Bucket regex：输入一个或多个用于匹配一组 bucket 名称的正则表达式。
+
正则表达式未锚定。使用 ^ 锚点在 bucket 名称的开头进行匹配，使用 $ 锚点在名称的结尾进行匹配。正则表达式匹配支持 PCRE（Perl 兼容正则表达式）语法的子集。

** CIDR：以 CIDR 表示法输入与所需子网匹配的一个或多个 IPv4 子网。
** 负载均衡器端点：选择端点名称。这些是您在link:../admin/configuring-load-balancer-endpoints.html["配置负载均衡器端点"]。
** 租户：租户匹配使用访问密钥ID。如果请求中不包含访问密钥ID（例如匿名访问），则使用所访问的存储桶的所有权来确定租户。




 a| 
反向匹配
 a| 
如果您想要匹配除刚刚定义的类型和匹配值一致的流量之外的所有网络流量，请选中“*反向匹配*”复选框。否则，请清除该复选框。

例如，如果您希望此策略应用于除一个负载均衡器端点之外的所有端点，请指定要排除的负载均衡器端点，然后选择*反向匹配*。

对于包含多个匹配器（其中至少有一个是逆匹配器）的策略，请注意不要创建匹配所有请求的策略。

|===
. 或者，选择*添加限制*并选择以下详细信息以添加一个或多个限制来控制规则匹配的网络流量。
+

NOTE: 即使您不添加任何限制， StorageGRID也会收集指标，因此您可以了解流量趋势。

+
[cols="1a,3a"]
|===
| 字段 | 描述 


 a| 
类型
 a| 
您想要对规则匹配的网络流量应用的限制类型。例如，您可以限制带宽或请求速率。

*注意*：您可以创建策略来限制总带宽或限制每个请求的带宽。但是， StorageGRID不能同时限制两种类型的带宽。当聚合带宽正在使用时，每个请求的带宽不可用。相反，当每个请求的带宽都在使用中时，聚合带宽不可用。总带宽限制可能会对不受限制的流量造成额外的轻微性能影响。

对于带宽限制， StorageGRID应用与限制集类型最匹配的策略。例如，如果您有一个仅限制一个方向流量的策略，那么相反方向的流量将不受限制，即使存在符合具有带宽限制的其他策略的流量。  StorageGRID按以下顺序实现带宽限制的“最佳”匹配：

** 精确的 IP 地址（/32 掩码）
** 确切的存储桶名称
** 桶正则表达式
** Tenant（租户）
** 端点
** 非精确 CIDR 匹配（非 /32）
** 反向匹配




 a| 
适用于
 a| 
此限制是否适用于客户端读取请求（GET 或 HEAD）或写入请求（PUT、POST 或 DELETE）。



 a| 
值
 a| 
根据您选择的单位，网络流量将被限制的值。例如输入10并选择MiB/s，则该规则匹配的网络流量不能超过10MiB/s。

*注意*：根据单位设置，可用的单位将是二进制（例如，GiB）或十进制（例如，GB）。要更改单位设置，请选择网格管理器右上角的用户下拉菜单，然后选择*用户首选项*。



 a| 
单元
 a| 
描述您输入的值的单位。

|===
+
例如，如果您想为 SLA 层创建 40 GB/s 的带宽限制，请创建两个聚合带宽限制：GET/HEAD 为 40 GB/s，PUT/POST/DELETE 为 40 GB/s。

. 选择*继续*。
. 阅读并审查流量分类政策。使用“*上一步*”按钮返回并根据需要进行更改。当您对政策满意时，选择*保存并继续*。
+
S3 客户端流量现在根据流量分类策略进行处理。



.完成后
link:viewing-network-traffic-metrics.html["查看网络流量指标"]验证政策是否正在执行您期望的流量限制。
