---
permalink: admin/deactivate-features-from-api.html 
sidebar: sidebar 
keywords: deactivate features from api 
summary: 您可以使用网格管理 API 完全停用StorageGRID系统中的某些功能。当某项功能被停用时，任何人都无法被分配执行与该功能相关的任务的权限。 
---
= 使用 API 停用功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用网格管理 API 完全停用StorageGRID系统中的某些功能。当某项功能被停用时，任何人都无法被分配执行与该功能相关的任务的权限。

.关于此任务
停用功能系统允许您阻止访问StorageGRID系统中的某些功能。停用某项功能是阻止根用户或具有 *Root 访问* 权限的管理组用户使用该功能的唯一方法。

要了解此功能如何有用，请考虑以下场景：

_公司 A 是一家服务提供商，通过创建租户账户来租赁其StorageGRID系统的存储容量。为了保护其租赁对象的安全，A 公司希望确保其员工在部署帐户后永远无法访问任何租户帐户。

_公司 A 可以通过使用网格管理 API 中的停用功能系统来实现这一目标。通过在网格管理器（UI 和 API）中完全停用“更改租户根密码”功能，公司 A 确保管理员用户（包括根用户和属于具有“根访问”权限的组的用户）无法更改任何租户帐户的根用户的密码。

.步骤
. 访问网格管理 API 的 Swagger 文档。看link:using-grid-management-api.html["使用网格管理 API"] 。
. 找到停用功能端点。
. 要停用某项功能（例如更改租户根密码），请向 API 发送如下正文：
+
`{ "grid": {"changeTenantRootPassword": true} }`

+
请求完成后，更改租户 root 密码功能将被禁用。  *更改租户根密码*管理权限不再出现在用户界面中，并且任何尝试更改租户根密码的 API 请求都将失败并显示“403 禁止”。





== 重新激活已停用的功能

默认情况下，您可以使用网格管理 API 重新激活已停用的功能。但是，如果您想防止已停用的功能被重新激活，您可以停用 *activateFeatures* 功能本身。


CAUTION: *activateFeatures* 功能无法重新激活。如果您决定停用此功能，请注意，您将永久失去重新激活任何其他已停用功能的能力。您必须联系技术支持来恢复任何丢失的功能。

.步骤
. 访问网格管理 API 的 Swagger 文档。
. 找到停用功能端点。
. 要重新激活所有功能，请向 API 发送如下正文：
+
`{ "grid": null }`

+
当此请求完成后，所有功能（包括更改租户根密码功能）都将重新激活。  *更改租户根密码*管理权限现在出现在用户界面中，并且任何尝试更改租户根密码的 API 请求都将成功，假设用户具有*根访问权限*或*更改租户根密码*管理权限。




TIP: 前面的示例导致所有已停用的功能被重新激活。如果其他功能已被停用且应保持停用状态，则必须在 PUT 请求中明确指定它们。例如，要重新激活更改租户 root 密码功能并继续停用 storageAdmin 管理权限，请发送此 PUT 请求：+
`{ "grid": {"storageAdmin": true} }`
