---
permalink: admin/grid-federation-compare-cgr-to-cloudmirror.html 
sidebar: sidebar 
keywords: cross-grid replication, cloudmirror replication 
summary: 当您开始使用网格联合时，请查看跨网格复制和StorageGRID CloudMirror 复制服务之间的异同。 
---
= 比较跨网格复制和 CloudMirror 复制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当你开始使用网格联合时，回顾一下link:grid-federation-what-is-cross-grid-replication.html["跨网格复制"]以及link:../tenant/understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror 复制服务"]。

[cols="1a,3a,3a"]
|===
|  | 跨网格复制 | CloudMirror复制服务 


 a| 
主要目的是什么？
 a| 
一个StorageGRID系统充当灾难恢复系统。存储桶中的对象可以在网格之间单向或双向复制。
 a| 
使租户能够自动将对象从StorageGRID （源）中的存储桶复制到外部 S3 存储桶（目标）。

CloudMirror 复制在独立的 S3 基础架构中创建对象的独立副本。此独立副本不用作备份，但通常在云中进一步处理。



 a| 
如何設置？
 a| 
. 配置两个网格之间的网格联合连接。
. 添加新的租户帐户，这些帐户会自动克隆到另一个网格。
. 添加新的租户组和用户，也进行克隆。
. 在每个网格上创建相应的存储桶，并启用跨网格复制以在一个方向或两个方向上进行。

 a| 
. 租户用户通过使用租户管理器或 S3 API 定义 CloudMirror 端点（IP 地址、凭据等）来配置 CloudMirror 复制。
. 该租户帐户拥有的任何存储桶都可以配置为指向 CloudMirror 端点。




 a| 
谁负责设置它？
 a| 
* 网格管理员配置连接和租户。
* 租户用户配置组、用户、密钥和存储桶。

 a| 
通常是租户用户。



 a| 
目的地是哪里？
 a| 
网格联合连接中另一个StorageGRID系统上对应且相同的 S3 存储桶。
 a| 
* 任何兼容的 S3 基础设施（包括 Amazon S3）。
* 谷歌云平台（GCP）




 a| 
是否需要对象版本控制？
 a| 
是的，源存储桶和目标存储桶都必须启用对象版本控制。
 a| 
不，CloudMirror 复制支持源和目标上任意组合的非版本化和版本化存储桶。



 a| 
什么原因导致物体移动到目的地？
 a| 
当对象被添加到启用了跨网格复制的存储桶时，它们会自动复制。
 a| 
当对象被添加到已配置 CloudMirror 端点的存储桶时，对象会自动复制。在使用 CloudMirror 端点配置存储桶之前，源存储桶中存在的对象不会被复制，除非它们被修改。



 a| 
对象是如何复制的？
 a| 
跨网格复制创建版本化对象，并将版本 ID 从源存储桶复制到目标存储桶。这允许在两个网格中维护版本顺序。
 a| 
CloudMirror 复制不需要启用版本控制的存储桶，因此 CloudMirror 只能维护站点内密钥的排序。无法保证对不同站点的对象请求的顺序能够保持不变。



 a| 
如果一个对象无法被复制怎么办？
 a| 
该对象正在排队等待复制，但受到元数据存储限制。
 a| 
该对象正在排队等待复制，但受平台服务限制（请参阅link:manage-platform-services-for-tenants.html["使用平台服务的建议"]）。



 a| 
对象的系统元数据是否被复制？
 a| 
是的，当一个对象被复制到另一个网格时，它的系统元数据也会被复制。两个网格上的元数据将是相同的。
 a| 
不会，当对象被复制到外部存储桶时，其系统元数据会被更新。元数据在不同位置会有所不同，具体取决于摄取时间和独立 S3 基础设施的行为。



 a| 
如何检索对象？
 a| 
应用程序可以通过向任一网格上的存储桶发出请求来检索或读取对象。
 a| 
应用程序可以通过向StorageGRID或 S3 目标发出请求来检索或读取对象。例如，假设您使用 CloudMirror 复制将对象镜像到合作伙伴组织。合作伙伴可以使用自己的应用程序直接从 S3 目标读取或更新对象。不需要使用StorageGRID 。



 a| 
如果删除对象会发生什么？
 a| 
* 包含版本 ID 的删除请求永远不会复制到目标网格。
* 不包含版本 ID 的删除请求会向源存储桶添加删除标记，可以选择将其复制到目标网格。
* 如果跨网格复制仅配置为一个方向，则可以删除目标存储桶中的对象而不会影响源。

 a| 
结果将根据源存储桶和目标存储桶的版本状态而有所不同（它们不需要相同）：

* 如果两个存储桶都已版本化，则删除请求将在两个位置添加删除标记。
* 如果仅对源存储桶进行版本控制，则删除请求将向源添加删除标记，但不会向目标添加删除标记。
* 如果两个存储桶都没有版本控制，则删除请求将从源中删除对象，但不会从目标中删除。


同样，可以删除目标存储桶中的对象，而不会影响源。

|===