---
permalink: admin/how-ha-groups-are-used.html 
sidebar: sidebar 
keywords: ha groups, high availability group 
summary: '您可以使用高可用性 (HA) 组为对象数据和管理用途提供与StorageGRID的高可用性连接。' 
---
= HA 组如何使用？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用高可用性 (HA) 组为对象数据和管理用途提供与StorageGRID的高可用性连接。

* HA 组可以为网格管理器或租户管理器提供高可用性管理连接。
* HA 组可以为 S3 客户端提供高可用性数据连接。
* 仅包含一个接口的 HA 组允许您提供多个 VIP 地址并明确设置 IPv6 地址。


只有当组中包含的所有节点都提供相同的服务时，HA 组才能提供高可用性。创建 HA 组时，从提供所需服务的节点类型中添加接口。

* *管理节点*：包括负载均衡器服务并启用对网格管理器或租户管理器的访问。
* *网关节点*：包括负载均衡器服务。


[cols="1a,2a"]
|===
| HA 组的目的 | 将此类型的节点添加到 HA 组 


 a| 
访问网格管理器
 a| 
* 主管理节点（*主*）
* 非主管理节点


*注意：*主管理节点必须是主接口。某些维护程序只能从主管理节点执行。



 a| 
仅限租户经理访问
 a| 
* 主要或非主要管理节点




 a| 
S3 客户端访问——负载均衡器服务
 a| 
* 管理节点
* 网关节点




 a| 
S3 客户端访问link:../admin/manage-s3-select-for-tenant-accounts.html["S3 选择"]
 a| 
* 服务设备
* 基于 VMware 的软件节点


*注意*：使用 S3 Select 时建议使用 HA 组，但这不是必需的。

|===


== 使用 HA 组与 Grid Manager 或 Tenant Manager 的限制

如果网格管理器或租户管理器服务出现故障，则不会触发 HA 组故障转移。

如果在发生故障转移时您已登录到网格管理器或租户管理器，则您将被注销，并且必须再次登录才能恢复您的任务。

当主管理节点不可用时，某些维护程序无法执行。在故障转移期间，您可以使用网格管理器来监控您的StorageGRID系统。
