---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: '租户帐户允许您使用简单存储服务 \(S3\) REST API 在StorageGRID系统中存储和检索对象。' 
---
= 什么是租户账户？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
租户帐户允许您使用简单存储服务 (S3) REST API 在StorageGRID系统中存储和检索对象。


TIP: 此版本的文档站点已删除 Swift 详细信息。看 https://docs.netapp.com/us-en/storagegrid-118/admin/managing-tenants.html["StorageGRID 11.8：管理租户"^]。

作为网格管理员，您可以创建和管理 S3 客户端用于存储和检索对象的租户帐户。

每个租户帐户都有联合或本地组、用户、S3 存储桶和对象。

租户帐户可用于按不同实体隔离存储的对象。例如，多个租户帐户可用于以下任一用例：

* *企业用例：*如果您在企业应用程序中管理StorageGRID系统，您可能希望按组织中的不同部门隔离网格的对象存储。在这种情况下，您可以为市场营销部门、客户支持部门、人力资源部门等创建租户帐户。
+

NOTE: 如果您使用 S3 客户端协议，则可以使用 S3 存储桶和存储桶策略在企业各部门之间隔离对象。您不需要使用租户帐户。请参阅实施说明link:../s3/bucket-and-group-access-policies.html["S3 存储桶和存储桶策略"]了解更多信息。

* *服务提供商用例：*如果您作为服务提供商管理StorageGRID系统，则可以通过租用网格存储的不同实体来隔离网格的对象存储。在这种情况下，您将为公司 A、公司 B、公司 C 等创建租户帐户。


有关更多信息，请参阅link:../tenant/index.html["使用租户帐户"] 。



== 如何创建租户帐户？

使用网格管理器创建租户帐户。创建租户帐户时，请指定以下信息：

* 基本信息包括租户名称、客户端类型（S3）和可选存储配额。
* 租户帐户的权限，例如租户帐户是否可以使用 S3 平台服务、配置自己的身份源、使用 S3 Select 或使用网格联合连接。
* 租户的初始根访问权限，取决于StorageGRID系统是否使用本地组和用户、身份联合或单点登录 (SSO)。


此外，如果 S3 租户账户需要遵守监管要求，您可以为StorageGRID系统启用 S3 对象锁定设置。启用 S3 对象锁定后，所有 S3 租户帐户都可以创建和管理兼容的存储桶。



== 租户管理器有什么用途？

创建租户帐户后，租户用户可以登录租户管理器执行以下任务：

* 设置身份联合（除非身份源与网格共享）
* 管理群组和用户
* 使用网格联合进行帐户克隆和跨网格复制
* 管理 S3 访问密钥
* 创建和管理 S3 存储桶
* 使用 S3 平台服务
* 使用 S3 Select
* 监控存储使用情况



TIP: 虽然 S3 租户用户可以使用租户管理器创建和管理 S3 访问密钥和存储桶，但他们必须使用 S3 客户端应用程序来提取和管理对象。看link:../s3/index.html["使用 S3 REST API"]了解详情。
