---
permalink: admin/managing-traffic-classification-policies.html 
sidebar: sidebar 
keywords: QoS, quality of service, traffic classification, best practices, limit traffic, monitor traffic 
summary: '流量分类策略允许您识别和监控不同类型的网络流量。这些策略可以帮助限制和监控流量，以增强您的服务质量 (QoS)。' 
---
= 什么是流量分类策略？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
流量分类策略允许您识别和监控不同类型的网络流量。这些策略可以帮助限制和监控流量，以增强您的服务质量 (QoS)。

流量分类策略应用于网关节点和管理节点的StorageGRID负载均衡器服务上的端点。要创建流量分类策略，您必须已经创建负载均衡器端点。



== 匹配规则

每个流量分类策略包含一个或多个匹配规则，用于识别与以下一个或多个实体相关的网络流量：

* 存储分段
* 子网
* Tenant（租户）
* 负载均衡器端点


StorageGRID根据规则的目标监控与策略内任何规则匹配的流量。任何与策略规则匹配的流量都由该策略处理。相反，您可以设置规则来匹配除指定实体之外的所有流量。



== 限流

您可以选择将以下限制类型添加到策略中：

* 总带宽
* 每个请求的带宽
* 并发请求
* 请求率


限制值是根据每个负载均衡器强制执行的。如果流量同时分布在多个负载均衡器之间，则总最大速率是您指定的速率限制的倍数。


NOTE: 您可以创建策略来限制总带宽或限制每个请求的带宽。但是， StorageGRID不能同时限制两种类型的带宽。总带宽限制可能会对不受限制的流量造成额外的轻微性能影响。

对于聚合或每个请求的带宽限制，请求以您设置的速率流入或流出。 StorageGRID只能强制执行一种速度，因此根据匹配器类型，最具体的策略匹配就是强制执行的策略。该请求消耗的带宽不会计入包含聚合带宽限制策略的其他不太具体的匹配策略。对于所有其他限制类型，客户端请求将延迟 250 毫秒，并且对于超出任何匹配策略限制的请求，将收到 503 Slow Down 响应。

在网格管理器中，您可以查看流量图表并验证策略是否正在执行您期望的流量限制。



== 将流量分类策略与 SLA 结合使用

您可以将流量分类策略与容量限制和数据保护结合使用，以强制执行提供容量、数据保护和性能细节的服务级别协议 (SLA)。

以下示例显示了 SLA 的三个层级。您可以创建流量分类策略来实现每个 SLA 层的性能目标。

[cols="1a,1a,1a,1a,1a"]
|===
| 服务级别层 | 容量 | 数据保护 | 允许的最大性能 | 成本 


 a| 
金子
 a| 
允许 1 PB 存储空间
 a| 
3 份 ILM 规则
 a| 
25K 个请求/秒

5 GB/秒（40 Gbps）带宽
 a| 
$$$ 每月



 a| 
银
 a| 
允许 250 TB 存储空间
 a| 
2 份 ILM 规则
 a| 
每秒 10 K 个请求

1.25 GB/秒（10 Gbps）带宽
 a| 
每月$$



 a| 
青铜
 a| 
允许 100 TB 存储空间
 a| 
2 份 ILM 规则
 a| 
5K 个请求/秒

1 GB/秒（8 Gbps）带宽
 a| 
$ 每月

|===