---
permalink: admin/manage-s3-select-for-tenant-accounts.html 
sidebar: sidebar 
keywords: s3 select, selectobjectcontent, best practices, object format, s3 select requirements 
summary: 您可以允许某些 S3 租户使用 S3 Select 对单个对象发出 SelectObjectContent 请求。 
---
= 管理租户帐户的 S3 Select
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以允许某些 S3 租户使用 S3 Select 对单个对象发出 SelectObjectContent 请求。

S3 Select 提供了一种有效的方法来搜索大量数据，而无需部署数据库和相关资源来实现搜索。它还降低了检索数据的成本和延迟。



== 什么是 S3 Select？

S3 Select 允许 S3 客户端使用 SelectObjectContent 请求来过滤和检索对象所需的数据。  S3 Select 的StorageGRID实现包括 S3 Select 命令和功能的子集。



== 使用 S3 Select 的注意事项和要求



=== 电网管理要求

网格管理员必须授予租户 S3 Select 能力。选择“允许 S3 选择”link:creating-tenant-account.html["创建租户"]或者link:editing-tenant-account.html["编辑租户"]。



=== 对象格式要求

您要查询的对象必须采用以下格式之一：

* *CSV*。可以按原样使用或压缩为 GZIP 或 BZIP2 档案。
* *镶木地板*。  Parquet 对象的附加要求：
+
** S3 Select 仅支持使用 GZIP 或 Snappy 进行列压缩。  S3 Select 不支持 Parquet 对象的整个对象压缩。
** S3 Select 不支持 Parquet 输出。您必须将输出格式指定为 CSV 或 JSON。
** 未压缩的行组最大大小为 512 MB。
** 您必须使用对象模式中指定的数据类型。
** 您不能使用 INTERVAL、JSON、LIST、TIME 或 UUID 逻辑类型。






=== 端点要求

SelectObjectContent 请求必须发送到link:configuring-load-balancer-endpoints.html["StorageGRID负载均衡器端点"]。

端点使用的管理节点和网关节点必须是以下之一：

* 服务设备节点
* 基于 VMware 的软件节点
* 运行启用了 cgroup v2 的内核的裸机节点




=== 一般注意事项

查询不能直接发送到存储节点。


CAUTION: SelectObjectContent 请求可能会降低所有 S3 客户端和所有租户的负载均衡器性能。仅在需要时且仅对受信任的租户启用此功能。

查看link:../s3/use-s3-select.html["S3 Select 使用说明"]。

查看link:../monitor/reviewing-support-metrics.html["Grafana 图表"]对于 S3 选择随时间推移的操作，在网格管理器中选择 *SUPPORT* > *Tools* > *Metrics*。
