---
permalink: admin/summary-ip-addresses-and-ports-for-client-connections.html 
sidebar: sidebar 
keywords: ip addresses for client, how to connect to storagegrid, ports, vip 
summary: '为了存储或检索对象，S3 客户端应用程序连接到所有管理节点和网关节点上包含的负载均衡器服务，或连接到所有存储节点上包含的本地分发路由器 (LDR) 服务。' 
---
= 摘要：客户端连接的 IP 地址和端口
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为了存储或检索对象，S3 客户端应用程序连接到所有管理节点和网关节点上包含的负载均衡器服务，或连接到所有存储节点上包含的本地分发路由器 (LDR) 服务。

客户端应用程序可以使用网格节点的 IP 地址和该节点上的服务的端口号连接到StorageGRID 。或者，您可以创建负载平衡节点的高可用性 (HA) 组，以提供使用虚拟 IP (VIP) 地址的高可用性连接。如果您想使用完全限定域名 (FQDN) 而不是 IP 或 VIP 地址连接到StorageGRID ，您可以配置 DNS 条目。

该表总结了客户端连接到StorageGRID 的不同方式以及用于每种连接类型的 IP 地址和端口。如果您已创建负载均衡器端点和高可用性 (HA) 组，请参阅<<在哪里查找 IP 地址>>在网格管理器中定位这些值。

[cols="1a,1a,1a,1a"]
|===
| 连接地点 | 客户端连接的服务 | IP 地址 | 端口 


 a| 
HA组
 a| 
负载均衡器
 a| 
HA组的虚拟IP地址
 a| 
分配给负载均衡器端点的端口



 a| 
管理节点
 a| 
负载均衡器
 a| 
管理节点的 IP 地址
 a| 
分配给负载均衡器端点的端口



 a| 
网关节点
 a| 
负载均衡器
 a| 
网关节点的IP地址
 a| 
分配给负载均衡器端点的端口



 a| 
存储节点
 a| 
LDR
 a| 
存储节点IP地址
 a| 
默认 S3 端口：

* HTTPS：18082
* HTTP：18084


|===


== 示例 URL

要将客户端应用程序连接到网关节点 HA 组的负载均衡器端点，请使用如下所示结构的 URL：

`https://_VIP-of-HA-group:LB-endpoint-port_`

例如，如果 HA 组的虚拟 IP 地址为 192.0.2.5，负载均衡器端点的端口号为 10443，则应用程序可以使用以下 URL 连接到StorageGRID：

`\https://192.0.2.5:10443`



== 在哪里查找 IP 地址

. Sign inlink:../admin/web-browser-requirements.html["支持的网络浏览器"]。
. 要查找网格节点的 IP 地址：
+
.. 选择*NODES*。
.. 选择要连接的管理节点、网关节点或存储节点。
.. 选择“*概览*”选项卡。
.. 在节点信息部分中，记下节点的 IP 地址。
.. 选择*显示更多*以查看 IPv6 地址和接口映射。
+
您可以从客户端应用程序与列表中的任何 IP 地址建立连接：

+
*** *eth0:* 网格网络
*** *eth1：*管理网络（可选）
*** *eth2：*客户端网络（可选）
+

NOTE: 如果您正在查看管理节点或网关节点，并且它是高可用性组中的活动节点，则 HA 组的虚拟 IP 地址将显示在 eth2 上。





. 要查找高可用性组的虚拟 IP 地址：
+
.. 选择 *配置* > *网络* > *高可用性组*。
.. 在表中，记下 HA 组的虚拟 IP 地址。


. 要查找负载均衡器端点的端口号：
+
.. 选择 *配置* > *网络* > *负载均衡器端点*。
.. 记下您要使用的端点的端口号。
+

NOTE: 如果端口号是 80 或 443，则端点仅在网关节点上配置，因为这些端口在管理节点上保留。所有其他端口均在网关节点和管理节点上配置。

.. 从表中选择端点的名称。
.. 确认*客户端类型*（S3）与将使用端点的客户端应用程序匹配。



