---
permalink: admin/troubleshooting-autosupport-messages.html 
sidebar: sidebar 
keywords: troubleshoot autosupport, asup package 
summary: 如果尝试发送AutoSupport包失败， StorageGRID系统将根据AutoSupport包的类型采取不同的操作。您可以通过选择支持 > 工具 > AutoSupport > 结果来检查AutoSupport包的状态。 
---
= 排除AutoSupport软件包故障
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果尝试发送AutoSupport包失败， StorageGRID系统将根据AutoSupport包的类型采取不同的操作。您可以通过选择 *SUPPORT* > *Tools* > * AutoSupport * > *Results* 来检查AutoSupport包的状态。

当AutoSupport包发送失败时， AutoSupport页面的“结果”选项卡上将显示“失败”。


NOTE: 如果您配置了代理服务器以将AutoSupport软件包转发到NetApp，则应该link:configuring-admin-proxy-settings.html["验证代理服务器配置设置是否正确"]。



== 每周AutoSupport包失败

如果每周AutoSupport包发送失败， StorageGRID系统将采取以下措施：

. 将最新结果属性更新为重试。
. 尝试每四分钟重新发送AutoSupport包 15 次，持续一小时。
. 发送失败一小时后，将“最新结果”属性更新为“失败”。
. 尝试在下一个计划时间再次发送AutoSupport包。
. 如果由于 NMS 服务不可用而导致软件包失败，并且软件包在七天之内发送，则维持常规AutoSupport计划。
. 当 NMS 服务再次可用时，如果七天或更长时间未发送包，则立即发送AutoSupport包。




== 用户触发或事件触发的AutoSupport包故障

如果用户触发或事件触发的AutoSupport包发送失败， StorageGRID系统将采取以下措施：

. 如果已知错误，则显示错误消息。例如，如果用户选择 SMTP 协议而没有提供正确的电子邮件配置设置，则会显示以下错误： `AutoSupport packages cannot be sent using SMTP protocol due to incorrect settings on the E-mail Server page.`
. 不再尝试发送包裹。
. 将错误记录在 `nms.log`。


如果发生故障并且 SMTP 是选定的协议，请验证StorageGRID系统的电子邮件服务器是否正确配置以及您的电子邮件服务器是否正在运行（*支持* > *警报（旧版）* > *旧版电子邮件设置*）。AutoSupport页面上可能会出现以下错误消息： `AutoSupport packages cannot be sent using SMTP protocol due to incorrect settings on the E-mail Server page.`

了解如何link:../monitor/email-alert-notifications.html["配置电子邮件服务器设置"] 。



== 纠正AutoSupport包故障

如果发生故障并且 SMTP 是选定的协议，请验证StorageGRID系统的电子邮件服务器是否正确配置以及您的电子邮件服务器是否正在运行。AutoSupport页面上可能会出现以下错误消息： `AutoSupport packages cannot be sent using SMTP protocol due to incorrect settings on the E-mail Server page.`
