---
permalink: admin/viewing-network-traffic-metrics.html 
sidebar: sidebar 
keywords: network traffic, traffic classification policy, monitor traffic 
summary: 您可以通过查看“流量分类策略”页面提供的图表来监控网络流量。 
---
= 查看网络流量指标
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过查看“流量分类策略”页面提供的图表来监控网络流量。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:admin-group-permissions.html["根访问权限或租户帐户权限"]。


.关于此任务
对于任何现有的流量分类策略，您可以查看负载均衡器服务的指标，以确定该策略是否成功限制了整个网络的流量。图表中的数据可以帮助您确定是否需要调整策略。

即使没有为流量分类策略设置限制，也会收集指标，并且图表可以提供有用的信息来了解流量趋势。

.步骤
. 选择*配置* > *网络* > *流量分类*。
+
出现“流量分类策略”页面，并在表中列出现有策略。

. 选择要查看其指标的流量分类策略名称。
. 选择“*Metrics*”选项卡。
+
出现流量分类策略图。图表仅显示与所选策略匹配的流量的指标。

+
该页面包含以下图表。

+
** 请求率：此图表提供所有负载均衡器处理的符合此策略的带宽量。接收到的数据包括所有请求的请求标头以及包含正文数据的响应的正文数据大小。已发送包括所有请求的响应标头以及响应中包含正文数据的请求的响应正文数据大小。
+

NOTE: 当请求完成时，此图表仅显示带宽使用情况。对于缓慢或较大的对象请求，实际瞬时带宽可能与此图中报告的值不同。

** 错误响应率：此图表提供与此策略匹配的请求向客户端返回错误（HTTP 状态代码 >= 400）的大致速率。
** 平均请求持续时间（非错误）：此图表提供符合此策略的成功请求的平均持续时间。
** 策略带宽使用情况：此图表提供所有负载均衡器处理的与此策略匹配的带宽量。接收到的数据包括所有请求的请求标头以及包含正文数据的响应的正文数据大小。已发送包括所有请求的响应标头以及响应中包含正文数据的请求的响应正文数据大小。


. 将光标放在折线图上即可查看图表特定部分的弹出值。
. 选择“Metrics”标题正下方的“Grafana dashboard”来查看策略的所有图表。除了“*Metrics*”选项卡中的四个图表之外，您还可以查看另外两个图表：
+
** 按对象大小的写入请求率：符合此策略的 PUT/POST/DELETE 请求的速率。单个单元格上的定位显示每秒的速率。悬停视图中显示的速率将被截断为整数计数，并且当存储桶中有非零请求时可能会报告 0。
** 按对象大小读取请求率：符合此策略的 GET/HEAD 请求的速率。单个单元格上的定位显示每秒的速率。悬停视图中显示的速率将被截断为整数计数，并且当存储桶中有非零请求时可能会报告 0。


. 或者，从*SUPPORT*菜单访问图表。
+
.. 选择*支持* > *工具* > *指标*。
.. 从 *Grafana* 部分选择 *流量分类策略*。
.. 从页面左上角的菜单中选择策略。
.. 将光标放在图表上即可看到弹出窗口，其中显示样本的日期和时间、聚合到计数中的对象大小以及该时间段内每秒的请求数。
+
流量分类策略通过其 ID 来识别。策略 ID 列在流量分类策略页面上。



. 分析图表以确定策略限制流量的频率以及是否需要调整策略。

