---
permalink: s3/deprecated-put-bucket-compliance-request.html 
sidebar: sidebar 
keywords: S3 REST API, S3 operations, PUT deprecated compliance requests 
summary: PUT Bucket 合规性请求已被弃用。但是，您可以继续使用此请求来修改现有旧版合规存储桶的合规性设置。 
---
= 已弃用：PUT Bucket 合规性请求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PUT Bucket 合规性请求已被弃用。但是，您可以继续使用此请求来修改现有旧版合规存储桶的合规性设置。例如，您可以将现有存储桶置于合法保留状态或延长其保留期。

[NOTE]
====
以前版本的StorageGRID中提供的StorageGRID合规性功能已被弃用，并已被 S3 对象锁取代。请参阅以下内容以了解更多详细信息：

* link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 配置 S3 对象锁"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知识库：如何在StorageGRID 11.5 中管理旧版兼容存储桶"^]


====
您必须拥有 s3:PutBucketCompliance 权限，或者成为账户根，才能完成此操作。

发出 PUT Bucket 合规性请求时，必须为合规性设置的每个字段指定一个值。



== 请求示例

此示例请求修改名为 `mybucket`。在这个例子中，对象 `mybucket`从对象被纳入电网时起，将保留两年（1,051,200 分钟），而不是一年。此存储桶不存在合法保留。每个对象将在两年后自动删除。

[listing, subs="specialcharacters,quotes"]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Date: _date_
Authorization: _authorization name_
Host: _host_
Content-Length: 152

<SGCompliance>
  <RetentionPeriodMinutes>1051200</RetentionPeriodMinutes>
  <LegalHold>false</LegalHold>
  <AutoDelete>true</AutoDelete>
</SGCompliance>
----
[cols="1a,2a"]
|===
| 名称 | 描述 


 a| 
保留期分钟
 a| 
添加到此存储桶的对象的保留期限长度（以分钟为单位）。保留期从对象被纳入电网时开始。

*重要* 为 RetentionPeriodMinutes 指定新值时，必须指定等于或大于存储桶当前保留期的值。设置存储桶的保留期后，您无法减少该值；您只能增加它。



 a| 
法律保留
 a| 
* 真：此存储桶目前处于合法保留状态。在解除合法保留之前，此存储桶中的对象无法被删除，即使其保留期已过期。
* 错误：此存储桶当前未处于合法保留之下。当保留期到期时，可以删除此存储桶中的对象。




 a| 
自动删除
 a| 
* True：除非存储桶处于合法保留状态，否则当保留期到期时，此存储桶中的对象将被自动删除。
* False：保留期到期后，此存储桶中的对象不会被自动删除。如果需要删除这些对象，则必须手动删除它们。


|===


== 合规性设置的一致性

当您使用 PUT Bucket 合规性请求更新 S3 存储桶的合规性设置时， StorageGRID会尝试在整个网格中更新存储桶的元数据。默认情况下， StorageGRID使用 *强全局* 一致性来保证所有数据中心站点和所有包含存储桶元数据的存储节点对于更改的合规性设置具有读写一致性。

如果StorageGRID由于数据中心站点或站点上的多个存储节点不可用而无法实现 *强全局* 一致性，则响应的 HTTP 状态代码为 `503 Service Unavailable.`

如果收到此回复，则必须联系网格管理员，以确保尽快提供所需的存储服务。如果网格管理员无法在每个站点提供足够的存储节点，技术支持可能会指导您通过强制*强站点*一致性来重试失败的请求。


CAUTION: 切勿强制使用 *Strong-site* 一致性来遵守 PUT bucket 规定，除非技术支持指示您这样做，并且您了解使用此级别的潜在后果。

当一致性降低到*强站点*时， StorageGRID保证更新后的合规性设置仅对站点内的客户端请求具有读写一致性。这意味着StorageGRID系统可能会暂时对该存储桶具有多个不一致的设置，直到所有站点和存储节点都可用。不一致的设置可能会导致意外和不良的行为。例如，如果您将存储桶置于合法保留之下并强制降低一致性，则存储桶以前的合规性设置（即合法保留）可能会在某些数据中心站点继续有效。因此，您认为处于合法保留状态的对象可能会在保留期到期时被用户或自动删除功能（如果启用）删除。

要强制使用 *Strong-site* 一致性，请重新发出 PUT Bucket 合规性请求，并包含 `Consistency-Control`HTTP请求头，如下：

[listing]
----
PUT /mybucket/?x-ntap-sg-compliance HTTP/1.1
Consistency-Control: strong-site
----


== 错误响应

* 如果存储桶的创建不符合要求，则响应的 HTTP 状态代码为 `404 Not Found`。
* 如果 `RetentionPeriodMinutes`如果请求小于存储桶的当前保留期，则 HTTP 状态代码为 `400 Bad Request`。


.相关信息
link:deprecated-put-bucket-request-modifications-for-compliance.html["已弃用：PUT Bucket 请求修改以实现合规性"]
