---
permalink: s3/object-versioning.html 
sidebar: sidebar 
keywords: object version, object versioning 
summary: 如果您想要保留对象的多个版本，可以设置存储桶的版本控制状态。启用存储桶的版本控制有助于防止意外删除对象，并使您能够检索和恢复对象的早期版本。 
---
= 对象版本控制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要保留每个对象的多个版本，您可以设置存储桶的版本控制状态。启用存储桶的版本控制有助于防止意外删除对象，并使您能够检索和恢复对象的早期版本。

StorageGRID系统实现了版本控制，支持大多数功能，但也有一些限制。  StorageGRID支持每个对象最多 10,000 个版本。

对象版本控制可以与StorageGRID信息生命周期管理 (ILM) 或 S3 存储桶生命周期配置相结合。您必须明确启用每个存储桶的版本控制。当为存储桶启用版本控制时，添加到存储桶的每个对象都会被分配一个版本 ID，该 ID 由StorageGRID系统生成。

不支持使用 MFA（多因素身份验证）删除。


NOTE: 仅可在使用StorageGRID版本 10.3 或更高版本创建的存储桶上启用版本控制。



== ILM 和版本控制

ILM 策略适用于对象的每个版本。 ILM 扫描过程会持续扫描所有对象并根据当前 ILM 策略重新评估它们。您对 ILM 策略所做的任何更改都将应用于所有先前摄取的对象。如果启用了版本控制，这包括以前摄取的版本。  ILM 扫描将新的 ILM 更改应用于先前摄取的对象。

对于启用版本控制的存储桶中的 S3 对象，版本控制支持允许您创建使用“非当前时间”作为参考时间的 ILM 规则（对于“仅将此规则应用于较旧的对象版本？”问题，选择“是”link:../ilm/create-ilm-rule-enter-details.html["创建 ILM 规则向导的第 1 步"] ）。当对象更新时，其先前版本将变为非当前版本。使用“非当前时间”过滤器允许您创建减少对象先前版本存储影响的策略。


NOTE: 当您使用分段上传操作上传对象的新版本时，对象原始版本的非当前时间反映的是新版本的分段上传的创建时间，而不是分段上传的完成时间。在有限的情况下，原始版本的非当前时间可能比当前版本的时间早几小时或几天。

.相关信息
* link:../ilm/how-objects-are-deleted.html#delete-s3-versioned-objects["如何删除 S3 版本控制对象"]
* link:../ilm/example-4-ilm-rules-and-policy-for-s3-versioned-objects.html["S3 版本化对象的 ILM 规则和策略（示例 4）"] 。

