---
permalink: monitor/configuring-snmp-agent.html 
sidebar: sidebar 
keywords: snmp agent, mib, trap, inform 
summary: 您可以配置StorageGRID SNMP 代理以使用第三方 SNMP 管理系统进行只读 MIB 访问和通知。 
---
= 配置 SNMP 代理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以配置StorageGRID SNMP 代理以使用第三方 SNMP 管理系统进行只读 MIB 访问和通知。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:../admin/admin-group-permissions.html["Root访问权限"]。


.关于此任务
StorageGRID SNMP 代理支持 SNMPv1、SNMPv2c 和 SNMPv3。您可以为一个或多个版本配置代理。对于 SNMPv3，仅支持用户安全模型 (USM) 身份验证。

网格中的所有节点都使用相同的 SNMP 配置。



== 指定基本配置

第一步，启用StorageGRID SMNP 代理并提供基本信息。

.步骤
. 选择 *配置* > *监控* > *SNMP 代理*。
+
出现 SNMP 代理页面。

. 要在所有网格节点上启用 SNMP 代理，请选中“启用 SNMP”复选框。
. 在基本配置部分输入以下信息。
+
[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
系统联系人
 a| 
可选。StorageGRID系统的主要联系人，在 SNMP 消息中以 sysContact 的形式返回。

系统联系人通常是一个电子邮件地址。此值适用于StorageGRID系统中的所有节点。  *系统联系人*最多可包含 255 个字符。



 a| 
系统位置
 a| 
可选。StorageGRID系统的位置，在 SNMP 消息中以 sysLocation 的形式返回。

系统位置可以是任何有助于识别StorageGRID系统所在位置的信息。例如，您可以使用设施的街道地址。此值适用于StorageGRID系统中的所有节点。  *系统位置*最多可包含 255 个字符。



 a| 
启用 SNMP 代理通知
 a| 
** 如果选择此选项， StorageGRID SNMP 代理将发送陷阱和通知。
** 如果未选择，SNMP 代理支持只读 MIB 访问，但不会发送任何 SNMP 通知。




 a| 
启用身份验证陷阱
 a| 
如果选择此选项， StorageGRID SNMP 代理将在收到未正确验证的协议消息时发送身份验证陷阱。

|===




== 输入社区字符串

如果您使用 SNMPv1 或 SNMPv2c，请完成社区字符串部分。

当管理系统查询StorageGRID MIB 时，它会发送一个社区字符串。如果社区字符串与此处指定的某个值匹配，则 SNMP 代理会向管理系统发送响应。

.步骤
. 对于*只读社区*，可选择输入社区字符串以允许在 IPv4 和 IPv6 代理地址上进行只读 MIB 访问。
+

TIP: 为了确保StorageGRID系统的安全，请不要使用“public”作为社区字符串。如果将此字段留空，SNMP 代理将使用StorageGRID系统的网格 ID 作为社区字符串。

+
每个社区字符串最多可以有 32 个字符，并且不能包含空格字符。

. 选择*添加另一个社区字符串*来添加其他字符串。
+
最多允许五个字符串。





== [[select_trap_destination]]创建陷阱目的地

使用“其他配置”部分中的“陷阱目标”选项卡来定义StorageGRID陷阱或通知通知的一个或多个目标。当您启用 SNMP 代理并选择 *保存* 时， StorageGRID会在触发警报时向每个定义的目的地发送通知。还会为支持的 MIB-II 实体（例如，ifDown 和 coldStart）发送标准通知。

.步骤
. 对于 *默认陷阱社区* 字段，可选择输入要用于 SNMPv1 或 SNMPv2 陷阱目标的默认社区字符串。
+
根据需要，您可以在定义特定的陷阱目标时提供不同的（“自定义”）社区字符串。

+
*默认陷阱社区*最多可以包含 32 个字符，并且不能包含空格字符。

. 要添加陷阱目标，请选择*创建*。
. 选择将用于此陷阱目标的 SNMP 版本。
. 完成您所选版本的“创建陷阱目标”表单。
+
[role="tabbed-block"]
====
.SNMPv1
--
如果您选择 SNMPv1 作为版本，请填写这些字段。

[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
类型
 a| 
对于 SNMPv1 来说必须是 Trap。



 a| 
主机
 a| 
用于接收陷阱的 IPv4 或 IPv6 地址或完全限定域名 (FQDN)。



 a| 
端口
 a| 
使用 162，这是 SNMP 陷阱的标准端口，除非您必须使用其他值。



 a| 
协议
 a| 
使用 UDP，它是标准 SNMP 陷阱协议，除非您需要使用 TCP。



 a| 
社区字符串
 a| 
如果指定了，则使用默认陷阱社区，或者为此陷阱目标输入自定义社区字符串。

自定义社区字符串最多可以有 32 个字符，并且不能包含空格。

|===
--
.SNMPv2c
--
如果您选择 SNMPv2c 作为版本，请填写这些字段。

[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
类型
 a| 
目的地是否用于陷阱或通知。



 a| 
主机
 a| 
用于接收陷阱的 IPv4 或 IPv6 地址或 FQDN。



 a| 
端口
 a| 
使用 162，这是 SNMP 陷阱的标准端口，除非您必须使用其他值。



 a| 
协议
 a| 
使用 UDP，它是标准 SNMP 陷阱协议，除非您需要使用 TCP。



 a| 
社区字符串
 a| 
如果指定了，则使用默认陷阱社区，或者为此陷阱目标输入自定义社区字符串。

自定义社区字符串最多可以有 32 个字符，并且不能包含空格。

|===
--
.SNMPv3
--
如果您选择 SNMPv3 作为版本，请填写这些字段。

[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
类型
 a| 
目的地是否用于陷阱或通知。



 a| 
主机
 a| 
用于接收陷阱的 IPv4 或 IPv6 地址或 FQDN。



 a| 
端口
 a| 
使用 162，这是 SNMP 陷阱的标准端口，除非您必须使用其他值。



 a| 
协议
 a| 
使用 UDP，它是标准 SNMP 陷阱协议，除非您需要使用 TCP。



 a| 
USM 用户
 a| 
将用于身份验证的 USM 用户。

** 如果您选择了 *Trap*，则仅显示没有权威引擎 ID 的 USM 用户。
** 如果您选择了*通知*，则仅显示具有权威引擎 ID 的 USM 用户。
** 如果没有显示用户：
+
... 创建并保存陷阱目的地。
... 前往<<create-usm-users,创建 USM 用户>>并创建用户。
... 返回到“陷阱目标”选项卡，从表中选择已保存的目标，然后选择“*编辑*”。
... 选择用户。




|===
--
====
. 选择“*创建*”。
+
陷阱目标已创建并添加到表中。





== 创建代理地址

或者，使用其他配置部分中的代理地址选项卡指定一个或多个“监听地址”。这些是 SNMP 代理可以接收查询的StorageGRID地址。

如果您未配置代理地址，则所有StorageGRID网络上的默认监听地址均为 UDP 端口 161。

.步骤
. 选择“*创建*”。
. 输入以下信息。
+
[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
互联网协议
 a| 
此地址是否使用 IPv4 或 IPv6。

默认情况下，SNMP 使用 IPv4。



 a| 
传输协议
 a| 
此地址是否使用 UDP 或 TCP。

默认情况下，SNMP 使用 UDP。



 a| 
StorageGRID网络
 a| 
代理将监听哪个StorageGRID网络。

** 网格、管理和客户端网络：SNMP 代理将监听所有三个网络上的查询。
** 网格网络
** 管理网络
** 客户端网络
+
*注意*：如果您使用客户端网络传输不安全的数据，并为客户端网络创建代理地址，请注意 SNMP 流量也将不安全。





 a| 
端口
 a| 
可选，SNMP 代理应监听的端口号。

SNMP 代理的默认 UDP 端口是 161，但您可以输入任何未使用的端口号。

*注意*：当您保存 SNMP 代理时， StorageGRID会自动在内部防火墙上打开代理地址端口。您必须确保任何外部防火墙都允许访问这些端口。

|===
. 选择“*创建*”。
+
代理地址已创建并添加到表中。





== [[create-usm-users]]创建 USM 用户

如果您使用的是 SNMPv3，请使用其他配置部分中的 USM 用户选项卡来定义有权查询 MIB 或接收陷阱和通知的 USM 用户。


NOTE: SNMPv3 _inform_ 目的地必须具有带有引擎 ID 的用户。  SNMPv3 _trap_ 目标不能拥有具有引擎 ID 的用户。

如果您仅使用 SNMPv1 或 SNMPv2c，则这些步骤不适用。

.步骤
. 选择“*创建*”。
. 输入以下信息。
+
[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
用户名
 a| 
此 USM 用户的唯一名称。

用户名最多可以有 32 个字符，并且不能包含空格字符。用户创建后，用户名不能更改。



 a| 
只读 MIB 访问
 a| 
如果选择，该用户应该具有 MIB 的只读访问权限。



 a| 
权威引擎ID
 a| 
如果此用户将在通知目的地中使用，则为该用户的权威引擎 ID。

输入 10 到 64 个十六进制字符（5 到 32 个字节），中间不带空格。对于将在陷阱目的地中选择以进行通知的 USM 用户，此值是必需的。对于将在陷阱目标中选择的 USM 用户，不允许使用此值。

*注意*：如果您选择了*只读 MIB 访问*，则不会显示此字段，因为具有只读 MIB 访问权限的 USM 用户不能拥有引擎 ID。



 a| 
安全级别
 a| 
USM 用户的安全级别：

** *authPriv*：此用户通过身份验证和隐私（加密）进行通信。您必须指定身份验证协议和密码以及隐私协议和密码。
** *authNoPriv*：此用户通过身份验证进行通信，但不进行隐私（无加密）。您必须指定身份验证协议和密码。




 a| 
身份验证协议
 a| 
始终设置为 SHA，这是唯一支持的协议（HMAC-SHA-96）。



 a| 
密码
 a| 
该用户将用于身份验证的密码。



 a| 
隐私协议
 a| 
仅当您选择 *authPriv* 并始终设置为 AES（这是唯一支持的隐私协议）时才显示。



 a| 
密码
 a| 
仅当您选择 *authPriv* 时才显示。该用户将使用的密码以保护隐私。

|===
. 选择“*创建*”。
+
USM 用户已创建并添加到表中。

. 完成 SNMP 代理配置后，选择*保存*。
+
新的 SNMP 代理配置将生效。


