---
permalink: monitor/monitoring-load-balancing-operations.html 
sidebar: sidebar 
keywords: load balancing, monitoring 
summary: 如果您使用负载平衡器来管理与StorageGRID 的客户端连接，则应在初始配置系统后以及进行任何配置更改或执行扩展后监控负载平衡操作。 
---
= 监控负载平衡操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用负载平衡器来管理与StorageGRID 的客户端连接，则应在初始配置系统后以及进行任何配置更改或执行扩展后监控负载平衡操作。

.关于此任务
您可以使用管理节点或网关节点上的负载均衡器服务或外部第三方负载均衡器在多个存储节点之间分配客户端请求。

配置负载平衡后，您应该确认对象提取和检索操作在存储节点之间均匀分布。均匀分布的请求可确保StorageGRID在负载下仍然能够响应客户端请求，并有助于维持客户端性能。

如果您以主动-备份模式配置了网关节点或管理节点的高可用性 (HA) 组，则组中只有一个节点主动分发客户端请求。

有关更多信息，请参阅link:../admin/configuring-client-connections.html["配置 S3 客户端连接"] 。

.步骤
. 如果 S3 客户端使用负载均衡器服务进行连接，请检查管理节点或网关节点是否按预期主动分配流量：
+
.. 选择*NODES*。
.. 选择网关节点或管理节点。
.. 在“*概述*”选项卡上，检查节点接口是否位于 HA 组中，以及节点接口是否具有主接口角色。
+
具有主角色的节点和不属于 HA 组的节点应该主动向客户端分发请求。

.. 对于应该主动分发客户端请求的每个节点，选择link:viewing-load-balancer-tab.html["负载均衡器选项卡"]。
.. 查看过去一周的负载均衡器请求流量图表，以确保节点一直在主动分发请求。
+
主动-备份 HA 组中的节点可能不时承担备份角色。在此期间，节点不会分发客户端请求。

.. 查看上周负载均衡器传入请求率图表，以查看节点的对象吞吐量。
.. 对StorageGRID系统中的每个管理节点或网关节点重复这些步骤。
.. 或者，使用流量分类策略来查看负载均衡器服务所服务的流量的更详细分析。


. 验证这些请求是否均匀分布到存储节点。
+
.. 选择 *_Storage Node_* > *LDR* > *HTTP*。
.. 查看*当前已建立的传入会话*的数量。
.. 对网格中的每个存储节点重复此操作。
+
所有存储节点的会话数量应大致相等。




