---
permalink: monitor/monitoring-information-lifecycle-management.html 
sidebar: sidebar 
keywords: lifecycle management, lifecycle, monitoring, ILM, information lifecycle management 
summary: 信息生命周期管理（ILM）系统为网格上存储的所有对象提供数据管理。您必须监控 ILM 操作以了解网格是否可以处理当前负载，或者是否需要更多资源。 
---
= 监控信息生命周期管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
信息生命周期管理（ILM）系统为电网上存储的所有对象提供数据管理。您必须监控 ILM 操作以了解网格是否可以处理当前负载，或者是否需要更多资源。

.关于此任务
StorageGRID系统通过应用活动的 ILM 策略来管理对象。  ILM 策略和相关的 ILM 规则决定了要制作多少份副本、创建的副本类型、副本的放置位置以及每个副本的保留时间长度。

对象摄取和其他对象相关活动可能超过StorageGRID评估 ILM 的速度，导致系统将无法近乎实时地完成 ILM 放置指令的对象排队。您应该监控StorageGRID是否跟上客户端的操作。



== 使用网格管理器仪表板选项卡

.步骤
使用网格管理器仪表板上的 ILM 选项卡来监视 ILM 操作：

. Sign in到网格管理器。
. 从仪表板中，选择 ILM 选项卡并记下 ILM 队列（对象）卡和 ILM 评估率卡上的值。
+
预计仪表板上的 ILM 队列（对象）卡会出现暂时的峰值。但是，如果队列持续增加并且不减少，则网格需要更多资源才能有效运行：要么是更多存储节点，要么是更多网络带宽（如果 ILM 策略将对象放置在远程位置）。





== 使用 NODES 页面

.步骤
此外，使用 *NODES* 页面调查 ILM 队列：


NOTE: 在未来的StorageGRID版本中，*NODES* 页面上的图表将被相应的仪表板卡取代。

. 选择*NODES*。
. 选择*_grid name_* > *ILM*。
. 将光标放在 ILM 队列图上，查看给定时间点的以下属性的值：
+
** *排队的对象（来自客户端操作）*：由于客户端操作（例如，摄取）而等待 ILM 评估的对象总数。
** *排队的对象（来自所有操作）*：等待 ILM 评估的对象总数。
** *扫描速率（对象/秒）*：扫描网格中的对象并将其排队等待 ILM 的速率。
** *评估率（对象/秒）*：当前根据网格中的 ILM 策略评估对象的速率。


. 在 ILM 队列部分，查看以下属性。
+

NOTE: ILM 队列部分仅包含在网格中。此信息不会显示在站点或存储节点的 ILM 选项卡上。

+
** *扫描周期 - 估计*：完成所有对象的完整 ILM 扫描的估计时间。
+

NOTE: 全面扫描并不能保证 ILM 已应用于所有对象。

** *尝试修复*：已尝试的复制数据的对象修复操作总数。每次存储节点尝试修复高风险对象时，此计数都会增加。如果电网变得繁忙，则优先进行高风险的 ILM 修复。
+

NOTE: 如果修复后复制失败，则同一对象修复可能会再次增加。



+
当您监控存储节点卷恢复的进度时，这些属性非常有用。如果尝试修复的次数停止增加并且完整扫描已完成，则修复可能已完成。


