---
permalink: monitor/updating-snmp-agent.html 
sidebar: sidebar 
keywords: how to update the SNMP agent 
summary: 您可以禁用 SNMP 通知、更新社区字符串，或者添加或删除代理地址、USM 用户和陷阱目的地。 
---
= 更新 SNMP 代理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以禁用 SNMP 通知、更新社区字符串，或者添加或删除代理地址、USM 用户和陷阱目的地。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:../admin/admin-group-permissions.html["Root访问权限"]。


.关于此任务
看link:configuring-snmp-agent.html["配置 SNMP 代理"]有关 SNMP 代理页面上每个字段的详细信息。您必须选择页面底部的“*保存*”才能提交在每个选项卡上所做的任何更改。

.步骤
. 选择 *配置* > *监控* > *SNMP 代理*。
+
出现 SNMP 代理页面。

. 要禁用所有网格节点上的 SNMP 代理，请清除 *启用 SNMP* 复选框，然后选择 *保存*。
+
如果重新启用 SNMP 代理，则任何以前的 SNMP 配置设置都会保留。

. 或者，更新基本配置部分中的信息：
+
.. 根据需要，更新*系统联系人*和*系统位置*。
.. 或者，选中或清除“启用 SNMP 代理通知”复选框来控制StorageGRID SNMP 代理是否发送陷阱和通知通知。
+
清除此复选框后，SNMP 代理支持只读 MIB 访问，但不发送 SNMP 通知。

.. 或者，选中或清除“启用身份验证陷阱”复选框，以控制StorageGRID SNMP 代理在收到未正确验证的协议消息时是否发送身份验证陷阱。


. 如果您使用 SNMPv1 或 SNMPv2c，则可以选择在社区字符串部分更新或添加 *只读社区*。
. 要更新陷阱目标，请选择“其他配置”部分中的“陷阱目标”选项卡。
+
使用此选项卡可以定义StorageGRID陷阱或通知通知的一个或多个目标。当您启用 SNMP 代理并选择 *保存* 时， StorageGRID会在触发警报时向每个定义的目的地发送通知。还会为支持的 MIB-II 实体（例如，ifDown 和 coldStart）发送标准通知。

+
有关输入内容的详细信息，请参阅link:../monitor/configuring-snmp-agent.html#create-trap-destinations["创建陷阱目的地"]。

+
** 或者，更新或删除默认陷阱社区。
+
如果删除默认陷阱社区，则必须首先确保任何现有的陷阱目标都使用自定义社区字符串。

** 要添加陷阱目标，请选择*创建*。
** 要编辑陷阱目标，请选择单选按钮，然后选择*编辑*。
** 要删除陷阱目标，请选择单选按钮，然后选择*删除*。
** 要提交您的更改，请选择页面底部的“*保存*”。


. 要更新代理地址，请选择其他配置部分中的代理地址选项卡。
+
使用此选项卡可以指定一个或多个“监听地址”。这些是 SNMP 代理可以接收查询的StorageGRID地址。

+
有关输入内容的详细信息，请参阅link:../monitor/configuring-snmp-agent.html#create-agent-addresses["创建代理地址"]。

+
** 要添加代理地址，请选择*创建*。
** 要编辑代理地址，请选择单选按钮，然后选择*编辑*。
** 要删除代理地址，请选择单选按钮，然后选择*删除*。
** 要提交您的更改，请选择页面底部的“*保存*”。


. 要更新 USM 用户，请选择“其他配置”部分中的“USM 用户”选项卡。
+
使用此选项卡定义有权查询 MIB 或接收陷阱和通知的 USM 用户。

+
有关输入内容的详细信息，请参阅link:../monitor/configuring-snmp-agent.html#create-usm-users["创建 USM 用户"]。

+
** 要添加 USM 用户，请选择 *创建*。
** 要编辑 USM 用户，请选择单选按钮，然后选择 *编辑*。
+
现有 USM 用户的用户名无法更改。如果您需要更改用户名，则必须删除该用户并创建一个新用户。

+

NOTE: 如果您添加或删除用户的权威引擎 ID，并且该用户当前被选为目标，则必须编辑或删除该目标。否则，保存 SNMP 代理配置时会出现验证错误。

** 要删除 USM 用户，请选择单选按钮，然后选择 *删除*。
+

NOTE: 如果您删除的用户当前被选为陷阱目标，则必须编辑或删除该目标。否则，保存 SNMP 代理配置时会出现验证错误。

** 要提交您的更改，请选择页面底部的“*保存*”。


. 更新 SNMP 代理配置后，选择*保存*。

