---
permalink: maintain/configuring-ip-addresses.html 
sidebar: sidebar 
keywords: configure ip address, change IP tool, ethernet, dhcp, ha group 
summary: 您可以使用更改 IP 工具为网格节点配置 IP 地址来执行网络配置。 
---
= IP 地址指南
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用更改 IP 工具为网格节点配置 IP 地址来执行网络配置。

您必须使用更改 IP 工具对网格部署期间最初设置的网络配置进行大部分更改。使用标准 Linux 网络命令和文件进行的手动更改可能不会传播到所有StorageGRID服务，并且可能不会在升级、重启或节点恢复过程中持续存在。


NOTE: IP 更改过程可能是一个破坏性的过程。在应用新配置之前，部分网格可能不可用。


NOTE: 如果您仅对网格网络子网列表进行更改，请使用网格管理器添加或更改网络配置。否则，如果由于网络配置问题而无法访问网格管理器，或者您同时执行网格网络路由更改和其他网络更改，请使用更改 IP 工具。


TIP: 如果要更改网格中所有节点的网格网络 IP 地址，请使用link:changing-ip-addresses-and-mtu-values-for-all-nodes-in-grid.html["电网范围变更的特殊程序"]。



== 以太网接口

分配给 eth0 的 IP 地址始终是网格节点的网格网络 IP 地址。分配给 eth1 的 IP 地址始终是网格节点的管理网络 IP 地址。分配给 eth2 的 IP 地址始终是网格节点的客户端网络 IP 地址。

请注意，在某些平台（例如StorageGRID设备）上，eth0、eth1 和 eth2 可能是由从属网桥或物理或 VLAN 接口的绑定组成的聚合接口。在这些平台上，*SSM* > *资源* 选项卡可能显示除 eth0、eth1 或 eth2 之外分配给其他接口的网格、管理和客户端网络 IP 地址。



== DHCP

您只能在部署阶段设置 DHCP。您无法在配置期间设置 DHCP。如果要更改网格节点的 IP 地址、子网掩码和默认网关，则必须使用 IP 地址更改程序。使用更改 IP 工具将导致 DHCP 地址变为静态。



== 高可用性 (HA) 组

* 如果客户端网络接口包含在 HA 组中，则不能将该接口的客户端网络 IP 地址更改为该 HA 组配置的子网之外的地址。
* 您不能将客户端网络 IP 地址更改为分配给客户端网络接口上配置的 HA 组的现有虚拟 IP 地址的值。
* 如果 Grid 网络接口包含在 HA 组中，则不能将该接口的 Grid 网络 IP 地址更改为 HA 组配置的子网之外的地址。
* 您不能将网格网络 IP 地址更改为分配给网格网络接口上配置的 HA 组的现有虚拟 IP 地址的值。

