---
permalink: maintain/configuring-ntp-servers.html 
sidebar: sidebar 
keywords: storagegrid, ntp, ntp server, configure ntp, configuring ntp 
summary: '您可以添加、更新或删除网络时间协议 (NTP) 服务器，以确保StorageGRID系统中的网格节点之间数据准确同步。' 
---
= 管理 NTP 服务器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以添加、更新或删除网络时间协议 (NTP) 服务器，以确保StorageGRID系统中的网格节点之间数据准确同步。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:../admin/admin-group-permissions.html["维护或 Root 访问权限"]。
* 您有配置密码。
* 您需要配置 NTP 服务器的 IPv4 地址。




== StorageGRID如何使用 NTP

StorageGRID系统使用网络时间协议 (NTP) 来同步网格中所有网格节点之间的时间。

在每个站点， StorageGRID系统中至少有两个节点被分配主要 NTP 角色。它们与建议的最少四个、最多六个外部时间源同步，并且彼此之间也同步。  StorageGRID系统中每个非主 NTP 节点都充当 NTP 客户端并与这些主 NTP 节点同步。

外部 NTP 服务器连接到您之前分配了主要 NTP 角色的节点。因此，建议指定至少两个具有主要 NTP 角色的节点。



== NTP 服务器指南

请遵循以下准则来防止出现时序问题：

* 外部 NTP 服务器连接到您之前分配了主要 NTP 角色的节点。因此，建议指定至少两个具有主要 NTP 角色的节点。
* 确保每个站点至少有两个节点可以访问至少四个外部 NTP 源。如果站点中只有一个节点可以访问 NTP 源，则当该节点发生故障时就会出现计时问题。此外，如果站点与电网的其余部分隔离，则为每个站点指定两个节点作为主要 NTP 源可确保准确的计时。
* 指定的外部 NTP 服务器必须使用 NTP 协议。您必须指定 Stratum 3 或更高级别的 NTP 服务器参考，以防止出现时间漂移问题。



NOTE: 为生产级StorageGRID安装指定外部 NTP 源时，请勿在早于 Windows Server 2016 的 Windows 版本上使用 Windows 时间 (W32Time) 服务。早期版本的 Windows 上的时间服务不够准确，并且 Microsoft 不支持在高精度环境（包括StorageGRID）中使用。有关详细信息，请参阅 https://support.microsoft.com/en-us/help/939322/support-boundary-to-configure-the-windows-time-service-for-high-accura["支持边界以配置 Windows 时间服务以实现高精度环境"^]。



== 配置 NTP 服务器

按照以下步骤添加、更新或删除 NTP 服务器。

.步骤
. 选择 *维护* > *网络* > *NTP 服务器*。
. 在服务器部分，根据需要添加、更新或删除 NTP 服务器条目。
+
您应该至少包含四个 NTP 服务器，并且最多可以指定六个服务器。

. 输入您的StorageGRID系统的配置密码，然后选择*保存*。
+
该页面将被禁用，直到配置更新完成。

+

NOTE: 如果在保存新的 NTP 服务器后所有 NTP 服务器均未通过连接测试，请不要继续。请联系技术支持。





== 解决 NTP 服务器问题

如果您在安装期间最初指定的 NTP 服务器的稳定性或可用性方面遇到问题，则可以通过添加其他服务器或更新或删除现有服务器来更新StorageGRID系统使用的外部 NTP 源列表。
