---
permalink: maintain/considerations-for-decommissioning-storage-nodes.html 
sidebar: sidebar 
keywords: storage node decommission, considerations, appliance node clone 
summary: 在退役存储节点之前，请考虑是否可以克隆该节点。然后，如果您决定退役该节点，请查看StorageGRID在退役过程中如何管理对象和元数据。 
---
= 退役存储节点的注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在退役存储节点之前，请考虑是否可以克隆该节点。然后，如果您决定退役该节点，请查看StorageGRID在退役过程中如何管理对象和元数据。



== 何时克隆节点而不是停用它

如果您想用更新或更大的设备替换旧设备存储节点，请考虑克隆设备节点，而不是在扩展中添加新设备，然后停用旧设备。

通过设备节点克隆，您可以轻松地在同一StorageGRID站点用兼容设备替换现有设备节点。克隆过程将所有数据传输到新设备，使新设备投入使用，并使旧设备处于预安装状态。

如果需要，您可以克隆设备节点：

* 更换已达到使用寿命的设备。
* 升级现有节点以利用改进的设备技术。
* 无需改变StorageGRID系统中的存储节点数量即可增加网格存储容量。
* 提高存储效率，例如通过更改 RAID 模式。


看 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["设备节点克隆"^]了解详情。



== 连接存储节点的注意事项

查看有关停用已连接存储节点的注意事项。

* 在单个退役节点过程中，您不应退役超过 10 个存储节点。
* 系统必须始终包含足够的存储节点以满足操作要求，包括link:understanding-adc-service-quorum.html["ADC 仲裁"]和活跃link:reviewing-ilm-policy-and-storage-configuration.html["ILM 策略"]。为了满足此限制，您可能需要在扩展操作中添加新的存储节点，然后才能停用现有的存储节点。
+
在包含基于软件的纯元数据节点的网格中停用存储节点时请务必小心。如果您停用所有配置为存储对象和元数据的节点，则存储对象的能力将从网格中删除。看link:../primer/what-storage-node-is.html#types-of-storage-nodes["存储节点的类型"]有关仅元数据存储节点的更多信息。

* 当您删除存储节点时，大量对象数据将通过网络传输。虽然这些传输不会影响正常的系统操作，但它们会影响StorageGRID系统消耗的网络带宽总量。
* 与存储节点退役相关的任务的优先级低于与正常系统操作相关的任务。这意味着退役不会干扰正常的StorageGRID系统操作，并且不需要安排在系统不活动期间。由于退役是在后台进行的，因此很难估计该过程需要多长时间才能完成。一般来说，当系统安静时，或者一次只删除一个存储节点时，退役会更快完成。
* 停用存储节点可能需要几天或几周的时间。相应地规划此过程。虽然退役过程不会影响系统运行，但它可能会限制其他程序。一般来说，您应该在删除网格节点之前执行任何计划的系统升级或扩展。
* 如果在移除存储节点时需要执行其他维护程序，您可以link:pausing-and-resuming-decommission-process-for-storage-nodes.html["暂停退役程序"]并在其他过程完成后恢复它。
+

NOTE: 仅当达到 ILM 评估或擦除编码数据退役阶段时才会启用 *暂停* 按钮；但是，ILM 评估（数据迁移）将继续在后台运行。

* 当退役任务正在运行时，您无法在任何网格节点上运行数据修复操作。
* 在存储节点退役期间，您不应对 ILM 策略进行任何更改。
* 要永久安全地删除数据，您必须在退役过程完成后擦除存储节点的驱动器。




== 断开连接的存储节点的注意事项

查看有关停用已断开连接的存储节点的注意事项。

* 切勿停用断开连接的节点，除非您确定它无法上线或恢复。
+

CAUTION: 如果您认为有可能从节点恢复对象数据，请不要执行此过程。相反，请联系技术支持以确定是否可以恢复节点。

* 当您退役断开连接的存储节点时， StorageGRID会使用来自其他存储节点的数据来重建断开连接的节点上的对象数据和元数据。
* 如果您停用多个断开连接的存储节点，则可能会发生数据丢失。如果没有足够的对象副本、擦除编码片段或对象元数据可用，系统可能无法重建数据。当在具有基于软件的纯元数据节点的网格中退役存储节点时，退役所有配置为存储对象和元数据的节点将从网格中删除所有对象存储。看link:../primer/what-storage-node-is.html#types-of-storage-nodes["存储节点的类型"]有关仅元数据存储节点的更多信息。
+

CAUTION: 如果您有多个无法恢复的断开连接的存储节点，请联系技术支持以确定最佳的措施。

* 当您退役已断开连接的存储节点时， StorageGRID会在退役过程结束时启动数据修复作业。这些作业尝试重建存储在断开连接的节点上的对象数据和元数据。
* 当您退役已断开连接的存储节点时，退役过程会相对较快地完成。然而，数据修复工作可能需要几天或几周的时间才能完成，并且不受退役程序的监控。您必须手动监控这些作业并根据需要重新启动它们。看link:checking-data-repair-jobs.html["检查数据修复作业"] 。
* 如果您停用包含对象唯一副本的已断开连接的存储节点，则该对象将会丢失。仅当当前连接的存储节点上存在至少一个复制副本或足够的擦除编码片段时，数据修复作业才能重建和恢复对象。

