---
permalink: maintain/copying-audit-logs-from-failed-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, audit log, copy audit log, copying audit log, non-primary admin node, non primary admin node 
summary: 如果您能够从发生故障的管理节点复制审计日志，则应保留它们以维护网格的系统活动和使用情况记录。您可以在恢复的非主管理节点启动并运行后，将保存的审计日志恢复到该节点。 
---
= 从发生故障的非主管理节点复制审计日志
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您能够从发生故障的管理节点复制审计日志，则应保留它们以维护网格的系统活动和使用情况记录。您可以在恢复的非主管理节点启动并运行后，将保存的审计日志恢复到该节点。

此过程将审计日志文件从故障的管理节点复制到单独的网格节点上的临时位置。然后可以将这些保存的审计日志复制到替换的管理节点。审计日志不会自动复制到新的管理节点。

根据故障类型，您可能无法从发生故障的管理节点复制审计日志。如果部署中只有一个管理节点，则恢复的管理节点将开始将事件记录到新的空文件中的审计日志中，并且以前记录的数据将丢失。如果部署包含多个管理节点，您可以从另一个管理节点恢复审计日志。


NOTE: 如果现在无法在发生故障的管理节点上访问审计日志，您可能稍后可以访问它们，例如，在主机恢复后。

. 如果可能，请登录到发生故障的管理节点。否则，请登录到主管理节点或另一个管理节点（如果可用）。
+
.. 输入以下命令： `ssh admin@grid_node_IP`
.. 输入 `Passwords.txt`文件。
.. 输入以下命令切换到root： `su -`
.. 输入 `Passwords.txt`文件。


+
当您以 root 身份登录时，提示符将从 `$`到 `#`。

. 停止 AMS 服务以防止其创建新的日志文件：``service ams stop``
. 导航到审计导出目录：
+
`cd /var/local/log`

. 将源 audit.log 文件重命名为唯一编号的文件名。例如，将 audit.log 文件重命名为 `2023-10-25.txt.1`。
+
[listing]
----
ls -l
mv audit.log 2023-10-25.txt.1
----
. 重新启动 AMS 服务： `service ams start`
. 创建目录以将所有审计日志文件复制到单独网格节点上的临时位置： `ssh admin@grid_node_IP mkdir -p /var/local/tmp/saved-audit-logs`
+
出现提示时，输入管理员密码。

. 将所有审计日志文件复制到临时位置： `scp -p * admin@grid_node_IP:/var/local/tmp/saved-audit-logs`
+
出现提示时，输入管理员密码。

. 以 root 身份注销： `exit`

