---
permalink: maintain/gathering-required-materials-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recovery, grid node recovery, node recovery 
summary: 在执行维护程序之前，您必须确保拥有恢复故障网格节点所需的材料。 
---
= 收集网格节点恢复所需的材料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在执行维护程序之前，您必须确保拥有恢复故障网格节点所需的材料。

[cols="1a,2a"]
|===
| 物品 | 笔记 


 a| 
StorageGRID安装存档
 a| 
如果需要恢复网格节点，则需要<<download-and-extract-install-files-recover,下载StorageGRID安装文件>>适用于您的平台。

*注意：*如果您正在恢复存储节点上发生故障的存储卷，则无需下载文件。



 a| 
维修笔记本电脑
 a| 
服务笔记本电脑必须具备以下条件：

* 网络端口
* SSH 客户端（例如，PuTTY）
* link:../admin/web-browser-requirements.html["支持的网络浏览器"]




 a| 
恢复包 `.zip`文件
 a| 
获取最新恢复包的副本 `.zip`文件：
`sgws-recovery-package-_id-revision_.zip`

的内容 `.zip`每次修改系统时都会更新文件。进行此类更改后，您需要将最新版本的恢复包存储在安全的位置。使用最新的副本来恢复电网故障。

如果主管理节点运行正常，您可以从网格管理器下载恢复包。选择*维护* > *系统* > *恢复包*。

如果您无法访问网格管理器，您可以在包含 ADC 服务的某些存储节点上找到恢复包的加密副本。在每个存储节点上，检查恢复包的此位置： `/var/local/install/sgws-recovery-package-_grid-id_-_revision_.zip.gpg`使用修订号最高的恢复包。



 a| 
`Passwords.txt`文件
 a| 
包含在命令行上访问网格节点所需的密码。包含在恢复包中。



 a| 
配置密码
 a| 
首次安装StorageGRID系统时会创建并记录密码。配置密码不在 `Passwords.txt`文件。



 a| 
您的平台的当前文档
 a| 
请访问平台供应商的网站获取文档。

有关您的平台当前支持的版本，请参阅 https://imt.netapp.com/matrix/#welcome["NetApp 互操作性表工具"^]。

|===


== 下载并解压StorageGRID安装文件

.下载并提取安装文件恢复
下载软件并解压文件，除非您link:recovering-from-storage-node-failures.html["恢复存储节点上发生故障的存储卷"]。

您必须使用当前在网格上运行的StorageGRID版本。

.步骤
. 确定当前安装的软件版本。从网格管理器的顶部，选择帮助图标并选择*关于*。
. 前往 https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab["NetApp StorageGRID下载页面"^]。
. 选择当前在网格上运行的StorageGRID版本。
+
StorageGRID软件版本具有以下格式： `11.x.y` 。

. 使用您的NetApp帐户的用户名和密码Sign in。
. 阅读最终用户许可协议，选中复选框，然后选择*接受并继续*。
. 在下载页面的“安装StorageGRID”列中，选择 `.tgz`或者 `.zip`适用于您的平台的文件。
+
安装存档文件中显示的版本必须与当前安装的软件版本相匹配。

+
使用 `.zip`如果您运行的是 Windows，请输入以下文件。

+
[cols="1a,2a"]
|===
| 平台 | 安装档案 


 a| 
Red Hat Enterprise Linux
| `StorageGRID-Webscale-_version_-RPM-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-RPM-_uniqueID_.tgz` 


 a| 
Ubuntu、Debian 或 Appliances
| `StorageGRID-Webscale-_version_-DEB-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-DEB-_uniqueID_.tgz` 


 a| 
VMware
| `StorageGRID-Webscale-_version_-VMware-_uniqueID_.zip` 
`StorageGRID-Webscale-_version_-VMware-_uniqueID_.tgz` 
|===
. 下载并解压存档文件。
. 根据您的平台和需要恢复的网格节点，按照适合您平台的步骤选择所需的文件。
+
每个平台的步骤中列出的路径都是相对于存档文件安装的顶级目录的。

. 如果你正在恢复link:../rhel/index.html["红帽企业 Linux 系统"]，选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | 描述 


| ./rpms/自述文件  a| 
描述StorageGRID下载文件中包含的所有文件的文本文件。



| ./rpms/NLF000000.txt  a| 
免费许可证不提供任何产品支持权利。



| StorageGRID  a| 
用于在 RHEL 主机上安装StorageGRID节点映像的 RPM 包。



| StorageGRID  a| 
用于在 RHEL 主机上安装StorageGRID主机服务的 RPM 包。



| 部署脚本工具 | 描述 


| ./rpms/configure-storagegrid.py  a| 
用于自动配置StorageGRID系统的 Python 脚本。



| ./rpms/configure-sga.py  a| 
用于自动配置StorageGRID设备的 Python 脚本。



| ./rpms/configure-storagegrid.sample.json  a| 
与以下文件一起使用的示例配置文件 `configure-storagegrid.py`脚本。



| ./rpms/storagegrid-ssoauth.py  a| 
启用单点登录后，您可以使用示例 Python 脚本登录网格管理 API。您还可以使用此脚本进行 Ping Federate 集成。



| ./rpms/configure-storagegrid.blank.json  a| 
用于 `configure-storagegrid.py`脚本。



| ./rpms/extras/ansible  a| 
用于配置 RHEL 主机以进行StorageGRID容器部署的示例 Ansible 角色和剧本。您可以根据需要自定义角色或剧本。



| ./rpms/storagegrid-ssoauth-azure.py  a| 
当使用 Active Directory 或 Ping Federate 启用单点登录 (SSO) 时，您可以使用该示例 Python 脚本登录到网格管理 API。



| ./rpms/storagegrid-ssoauth-azure.js  a| 
同伴调用的辅助脚本 `storagegrid-ssoauth-azure.py`用于与 Azure 执行 SSO 交互的 Python 脚本。



| ./rpms/extras/api-schemas  a| 
StorageGRID的 API 模式。

*注意*：在执行升级之前，如果您没有非生产StorageGRID环境进行升级兼容性测试，则可以使用这些模式来确认您编写的任何使用StorageGRID管理 API 的代码是否与新的StorageGRID版本兼容。

|===
. 如果你正在恢复link:../ubuntu/index.html["Ubuntu 或 Debian 系统"]，选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | 描述 


| ./debs/README  a| 
描述StorageGRID下载文件中包含的所有文件的文本文件。



| ./debs/NLF000000.txt  a| 
非生产NetApp许可证文件，可用于测试和概念验证部署。



| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装StorageGRID节点映像的 DEB 包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
文件的 MD5 校验和 `/debs/storagegrid-webscale-images-version-SHA.deb`。



| ./debs/storagegrid-webscale-service-version-SHA.deb  a| 
用于在 Ubuntu 或 Debian 主机上安装StorageGRID主机服务的 DEB 包。



| 部署脚本工具 | 描述 


| ./debs/configure-storagegrid.py  a| 
用于自动配置StorageGRID系统的 Python 脚本。



| ./debs/configure-sga.py  a| 
用于自动配置StorageGRID设备的 Python 脚本。



| ./debs/storagegrid-ssoauth.py  a| 
启用单点登录后，您可以使用示例 Python 脚本登录网格管理 API。您还可以使用此脚本进行 Ping Federate 集成。



| ./debs/configure-storagegrid.sample.json  a| 
与以下文件一起使用的示例配置文件 `configure-storagegrid.py`脚本。



| ./debs/configure-storagegrid.blank.json  a| 
用于 `configure-storagegrid.py`脚本。



| ./debs/extras/ansible  a| 
用于配置 Ubuntu 或 Debian 主机以进行StorageGRID容器部署的示例 Ansible 角色和剧本。您可以根据需要自定义角色或剧本。



| ./debs/storagegrid-ssoauth-azure.py  a| 
当使用 Active Directory 或 Ping Federate 启用单点登录 (SSO) 时，您可以使用该示例 Python 脚本登录到网格管理 API。



| ./debs/storagegrid-ssoauth-azure.js  a| 
同伴调用的辅助脚本 `storagegrid-ssoauth-azure.py`用于与 Azure 执行 SSO 交互的 Python 脚本。



| ./debs/extras/api-schemas  a| 
StorageGRID的 API 模式。

*注意*：在执行升级之前，如果您没有非生产StorageGRID环境进行升级兼容性测试，则可以使用这些模式来确认您编写的任何使用StorageGRID管理 API 的代码是否与新的StorageGRID版本兼容。

|===
. 如果你正在恢复link:../vmware/index.html["VMware 系统"]，选择相应的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | 描述 


| ./vsphere/README  a| 
描述StorageGRID下载文件中包含的所有文件的文本文件。



| ./vsphere/NLF000000.txt  a| 
免费许可证不提供任何产品支持权利。



| NetApp版本-SHA.vmdk  a| 
用作创建网格节点虚拟机的模板的虚拟机磁盘文件。



| ./vsphere/vsphere-primary-admin.ovf ./vsphere/vsphere-primary-admin.mf  a| 
开放虚拟化格式模板文件(`.ovf`) 和清单文件(`.mf`) 用于部署主管理节点。



| ./vsphere/vsphere-non-primary-admin.ovf ./vsphere/vsphere-non-primary-admin.mf  a| 
模板文件(`.ovf`) 和清单文件(`.mf`) 用于部署非主管理节点。



| ./vsphere/vsphere-gateway.ovf ./vsphere/vsphere-gateway.mf  a| 
模板文件(`.ovf`) 和清单文件(`.mf`) 用于部署网关节点。



| ./vsphere/vsphere-storage.ovf ./vsphere/vsphere-storage.mf  a| 
模板文件(`.ovf`) 和清单文件(`.mf`) 用于部署基于虚拟机的存储节点。



| 部署脚本工具 | 描述 


| ./vsphere/deploy-vsphere-ovftool.sh  a| 
用于自动部署虚拟网格节点的 Bash shell 脚本。



| ./vsphere/deploy-vsphere-ovftool-sample.ini  a| 
与以下文件一起使用的示例配置文件 `deploy-vsphere-ovftool.sh`脚本。



| ./vsphere/configure-storagegrid.py  a| 
用于自动配置StorageGRID系统的 Python 脚本。



| ./vsphere/configure-sga.py  a| 
用于自动配置StorageGRID设备的 Python 脚本。



| ./vsphere/storagegrid-ssoauth.py  a| 
启用单点登录 (SSO) 后，您可以使用该示例 Python 脚本登录到网格管理 API。您还可以使用此脚本进行 Ping Federate 集成。



| ./vsphere/configure-storagegrid.sample.json  a| 
与以下文件一起使用的示例配置文件 `configure-storagegrid.py`脚本。



| ./vsphere/configure-storagegrid.blank.json  a| 
用于 `configure-storagegrid.py`脚本。



| ./vsphere/storagegrid-ssoauth-azure.py  a| 
当使用 Active Directory 或 Ping Federate 启用单点登录 (SSO) 时，您可以使用该示例 Python 脚本登录到网格管理 API。



| ./vsphere/storagegrid-ssoauth-azure.js  a| 
同伴调用的辅助脚本 `storagegrid-ssoauth-azure.py`用于与 Azure 执行 SSO 交互的 Python 脚本。



| ./vsphere/extras/api-schemas  a| 
StorageGRID的 API 模式。

*注意*：在执行升级之前，如果您没有非生产StorageGRID环境进行升级兼容性测试，则可以使用这些模式来确认您编写的任何使用StorageGRID管理 API 的代码是否与新的StorageGRID版本兼容。

|===
. 如果您正在恢复基于StorageGRID设备的系统，请选择适当的文件。


[cols="1a,1a"]
|===
| 路径和文件名 | 描述 


| ./debs/storagegrid-webscale-images-version-SHA.deb  a| 
用于在您的设备上安装StorageGRID节点映像的 DEB 包。



| ./debs/storagegrid-webscale-images-version-SHA.deb.md5  a| 
文件的 MD5 校验和 `/debs/storagegridwebscale-
images-version-SHA.deb`。

|===

NOTE: 对于设备安装，仅当您需要避免网络流量时才需要这些文件。设备可以从主管理节点下载所需的文件。
