---
permalink: maintain/grid-node-decommissioning.html 
sidebar: sidebar 
keywords: storagegrid, decommission, remove grid node 
summary: 您可以使用节点退役程序来删除一个或多个站点上的一个或多个网格节点。您不能停用主管理节点。 
---
= 电网节点退役
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用节点退役程序来删除一个或多个站点上的一个或多个网格节点。您不能停用主管理节点。



== 何时停用节点

当以下任一情况成立时，请使用节点退役程序：

* 您在扩展中添加了一个更大的存储节点，并且想要删除一个或多个较小的存储节点，同时保留对象。
+

TIP: 如果您想用较新的电器替换旧电器，请考虑 https://docs.netapp.com/us-en/storagegrid-appliances/commonhardware/how-appliance-node-cloning-works.html["克隆设备节点"^]而不是在扩展中添加新设备，然后停用旧设备。

* 您需要的总存储空间较少。
* 您不再需要网关节点。
* 您不再需要非主要管理节点。
* 您的电网包含一个断开连接的节点，您无法恢复或重新上线。
* 您的网格包含一个存档节点。




== 如何停用节点

您可以停用已连接的网格节点或已断开连接的网格节点。

停用已连接节点:: 一般来说，只有当网格节点连接到StorageGRID系统并且所有节点都处于正常健康状态时（在 *NODES* 页面和 *Decommission Nodes* 页面上有绿色图标），才应该退役网格节点。
+
--
有关说明，请参阅link:decommissioning-connected-grid-nodes.html["退役已连接的电网节点"]。

--
停用已断开连接的节点:: 在某些情况下，您可能需要停用当前未连接到电网的电网节点（健康状况未知或管理关闭的电网节点）。
+
--
有关说明，请参阅link:decommissioning-disconnected-grid-nodes.html["退役断开连接的电网节点"]。

--




== 停用节点之前需要考虑的事项

在执行任一过程之前，请查看每种节点类型的注意事项：

* link:considerations-for-decommissioning-admin-or-gateway-nodes.html["管理员节点或网关节点停用的注意事项"]
* link:considerations-for-decommissioning-storage-nodes.html["存储节点退役的注意事项"]

