---
permalink: maintain/how-site-recovery-is-performed-by-technical-support.html 
sidebar: sidebar 
keywords: storagegrid, site recovery, technical support, tech support 
summary: 如果整个StorageGRID站点发生故障或多个存储节点发生故障，则必须联系技术支持。技术支持将评估您的状况，制定恢复计划，然后以满足您的业务目标、优化恢复时间并防止不必要的数据丢失的方式恢复故障节点或站点。 
---
= 技术支持如何恢复站点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果整个StorageGRID站点发生故障或多个存储节点发生故障，则必须联系技术支持。技术支持将评估您的状况，制定恢复计划，然后以满足您的业务目标、优化恢复时间并防止不必要的数据丢失的方式恢复故障节点或站点。


CAUTION: 站点恢复只能由技术支持执行。

StorageGRID系统能够抵御各种故障，您可以自行成功执行许多恢复和维护程序。然而，创建一个简单、通用的站点恢复程序很困难，因为详细步骤取决于特定于您情况的因素。例如：

* *您的业务目标*：在StorageGRID站点完全丢失后，您应该评估如何最好地实现您的业务目标。例如，您是否想就地重建丢失的站点？您是否想在新位置替换丢失的StorageGRID站点？每个客户的情况都不同，您的恢复计划必须根据您的优先事项进行设计。
* *故障的确切性质*：在开始站点恢复之前，确定故障站点上的任何节点是否完好无损，或者任何存储节点是否包含可恢复的对象。如果重建包含有效数据的节点或存储卷，可能会发生不必要的数据丢失。
* *活动的 ILM 策略*：网格中对象副本的数量、类型和位置由活动的 ILM 策略控制。  ILM 策略的具体内容可能会影响可恢复数据的数量以及恢复所需的具体技术。
+

CAUTION: 如果某个站点包含某个对象的唯一副本，而该站点丢失，则该对象也会丢失。

* *存储桶（或容器）一致性*：应用于存储桶（或容器）的一致性会影响StorageGRID在告知客户端对象摄取成功之前是否将对象元数据完全复制到所有节点和站点。如果一致性值允许最终一致性，则某些对象元数据可能在站点故障中丢失。这可能会影响可恢复数据的数量，甚至可能影响恢复过程的细节。
* *最近更改的历史记录*：故障发生时是否有任何维护程序正在进行，或者您的 ILM 策略是否最近进行了任何更改，都会影响您的恢复过程的详细信息。在开始站点恢复之前，技术支持必须评估您的电网的近期历史及其当前状况。



CAUTION: 站点恢复只能由技术支持执行。

这是技术支持用于恢复故障站点的过程的概述：

. 技术支援：
+
.. 对失败进行详细评估。
.. 与您一起审查您的业务目标。
.. 制定适合您情况的恢复计划。


. 如果主管理节点出现故障，技术支持将对其进行恢复。
. 技术支持将按照以下概要恢复所有存储节点：
+
.. 根据需要更换存储节点硬件或虚拟机。
.. 将对象元数据恢复到故障站点。
.. 将对象数据恢复到已恢复的存储节点。
+

CAUTION: 如果使用单个故障存储节点的恢复程序，则会发生数据丢失。

+

NOTE: 当整个站点发生故障时，技术支持使用专门的命令来成功恢复对象和对象元数据。



. 技术支持恢复其他故障节点。
+
恢复对象元数据和数据后，技术支持使用标准程序来恢复故障的网关节点或非主管理节点。



.相关信息
link:site-decommissioning.html["场地退役"]
