---
permalink: maintain/how-your-system-is-affected-when-you-apply-hotfix.html 
sidebar: sidebar 
keywords: storagegrid, hotfix 
summary: 您必须了解应用修补程序时StorageGRID系统将受到怎样的影响。 
---
= 应用修补程序后您的系统会受到怎样的影响
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须了解应用修补程序时StorageGRID系统将受到怎样的影响。



== StorageGRID修补程序不会造成中断

StorageGRID系统可以在整个修补程序过程中从客户端应用程序提取和检索数据。如果您批准对同一类型的所有节点（例如，存储节点）进行热修复，则会一次关闭一个节点，因此不会出现所有网格节点或某种类型的所有网格节点都不可用的情况。

为了实现持续可用性，请确保您的 ILM 策略包含指定存储每个对象的多个副本的规则。您还必须确保所有外部 S3 客户端都配置为将请求发送到以下之一：

* 高可用性 (HA) 组虚拟 IP 地址
* 高可用性第三方负载均衡器
* 每个客户端有多个网关节点
* 每个客户端有多个存储节点




== 客户端应用程序可能会遭遇短期中断

StorageGRID系统可以在整个修补程序过程中从客户端应用程序提取和检索数据；但是，如果修补程序需要重新启动这些节点上的服务，则客户端与各个网关节点或存储节点的连接可能会暂时中断。修复过程完成后，连接将恢复，并且各个节点上的服务将恢复。

如果短时间内失去连接是不可接受的，您可能需要安排停机时间来应用修补程序。您可以使用选择性批准来安排某些节点的更新时间。


NOTE: 您可以使用多个网关和高可用性 (HA) 组在修补程序过程中提供自动故障转移。请参阅说明link:../admin/configure-high-availability-group.html["配置高可用性组"]。



== 可能会触发警报和 SNMP 通知

当服务重新启动时以及当StorageGRID系统作为混合版本环境运行时（一些网格节点运行早期版本，而其他网格节点已升级到更高版本），可能会触发警报和 SNMP 通知。一般来说，这些警报和通知将在修补程序完成时清除。



== 配置更改受到限制

将修补程序应用于StorageGRID时：

* 在修补程序应用到所有节点之前，请勿进行任何网格配置更改（例如，指定网格网络子网或批准待处理的网格节点）。
* 在将修补程序应用到所有节点之前，请勿更新 ILM 配置。

