---
permalink: maintain/linux-migrating-grid-node-to-new-host.html 
sidebar: sidebar 
keywords: storagegrid, recover, linux, migrate node, migrating node, new host for node 
summary: 您可以将一个或多个StorageGRID节点从一个 Linux 主机迁移到另一个 Linux 主机以执行主机维护，而不会影响网格的功能或可用性。 
---
= Linux：将网格节点迁移到新主机
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以将一个或多个StorageGRID节点从一个 Linux 主机（源主机）迁移到另一个 Linux 主机（目标主机）以执行主机维护，而不会影响网格的功能或可用性。

例如，您可能想要迁移一个节点来执行操作系统修补和重新启动。

.开始之前
* 您计划将StorageGRID部署包括迁移支持。
+
** link:../rhel/node-container-migration-requirements.html["Red Hat Enterprise Linux 的节点容器迁移要求"]
** link:../ubuntu/node-container-migration-requirements.html["Ubuntu 或 Debian 的 Node 容器迁移要求"]


* 目标主机已准备好供StorageGRID使用。
* 所有节点存储卷均使用共享存储
* 网络接口在各个主机之间具有一致的名称。


[NOTE]
====
在生产部署中，不要在单个主机上运行多个存储节点。为每个存储节点使用专用主机可提供隔离的故障域。

其他类型的节点，例如管理节点或网关节点，可以部署在同一主机上。但是，如果您有多个相同类型的节点（例如两个网关节点），请不要在同一主机上安装所有实例。

====


== 从源主机导出节点

第一步，关闭网格节点并将其从源 Linux 主机导出。

在_源主机_上运行以下命令。

.步骤
. 获取源主机上当前运行的所有节点的状态。
+
`sudo storagegrid node status all`

+
示例输出：

+
[listing]
----
Name Config-State Run-State
DC1-ADM1 Configured Running
DC1-ARC1 Configured Running
DC1-GW1 Configured Running
DC1-S1 Configured Running
DC1-S2 Configured Running
DC1-S3 Configured Running
----
. 确定要迁移的节点的名称，如果其运行状态为正在运行，则停止它。
+
`sudo storagegrid node stop DC1-S3`

+
示例输出：

+
[listing]
----
Stopping node DC1-S3
Waiting up to 630 seconds for node shutdown
----
. 从源主机导出节点。
+
`sudo storagegrid node export DC1-S3`

+
示例输出：

+
[listing]
----
Finished exporting node DC1-S3 to /dev/mapper/sgws-dc1-s3-var-local.
Use 'storagegrid node import /dev/mapper/sgws-dc1-s3-var-local' if you
want to import it again.
----
. 记下 `import`输出中建议的命令。
+
您将在下一步中在目标主机上运行此命令。





== 在目标主机上导入节点

从源主机导出节点后，在目标主机上导入并验证该节点。验证确认该节点可以访问与源主机上相同的块存储和网络接口设备。

在_目标主机_上运行以下命令。

.步骤
. 在目标主机上导入节点。
+
`sudo storagegrid node import /dev/mapper/sgws-dc1-s3-var-local`

+
示例输出：

+
[listing]
----
Finished importing node DC1-S3 from /dev/mapper/sgws-dc1-s3-var-local.
You should run 'storagegrid node validate DC1-S3'
----
. 验证新主机上的节点配置。
+
`sudo storagegrid node validate DC1-S3`

+
示例输出：

+
[listing]
----
Confirming existence of node DC1-S3... PASSED
Checking configuration file /etc/storagegrid/nodes/DC1-S3.conf for node DC1-S3... PASSED
Checking for duplication of unique values... PASSED
----
. 如果发生任何验证错误，请在启动迁移节点之前解决它们。
+
有关故障排除信息，请参阅 Linux 操作系统的StorageGRID安装说明。

+
** link:../rhel/index.html["在 Red Hat Enterprise Linux 上安装StorageGRID"]
** link:../ubuntu/index.html["在 Ubuntu 或 Debian 上安装StorageGRID"]






== 启动迁移节点

验证迁移的节点后，通过在_目标主机_上运行命令来启动该节点。

.步骤
. 在新主机上启动节点。
+
`sudo storagegrid node start DC1-S3`

. Sign in网格管理器并验证节点状态为绿色且没有警报。
+

CAUTION: 验证节点的状态是否为绿色可确保迁移的节点已完全重启并重新加入网格。如果状态不是绿色，请不要迁移任何其他节点，以免多个节点停止服务。

. 如果您无法访问网格管理器，请等待 10 分钟，然后运行以下命令：
+
`sudo storagegrid node status _node-name`

+
确认迁移后的节点的运行状态为正在运行。


