---
permalink: maintain/rebooting-grid-node-from-grid-manager.html 
sidebar: sidebar 
keywords: reboot grid node, tasks tab 
summary: 您可以从“节点”页面上的“任务”选项卡重新启动单个网格节点。 
---
= 从“任务”选项卡重新启动网格节点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以从“节点”页面上的“任务”选项卡重新启动单个网格节点。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:../admin/admin-group-permissions.html["维护或 Root 访问权限"]。
* 您有配置密码。
* 如果您要重新启动主管理节点或任何存储节点，请先查看以下注意事项：
+
** 当您重新启动主管理节点时，您的浏览器将暂时失去对网格管理器的访问权限。
** 如果您在给定站点重新启动两个或更多存储节点，则您可能无法在重新启动期间访问某些对象。如果任何 ILM 规则使用 *Dual commit* 摄取选项（或者规则指定 *Balanced* 并且无法立即创建所有必需的副本），则可能会出现此问题。在这种情况下， StorageGRID会将新摄取的对象提交到同一站点上的两个存储节点，然后再评估 ILM。
** 为确保在存储节点重新启动时可以访问所有对象，请在重新启动节点之前停止在站点提取对象约一小时。




.关于此任务
当StorageGRID重新启动网格节点时，它会发出 `reboot`命令，这会导致节点关闭并重新启动。所有服务都会自动重启。

* 重新启动 VMware 节点将重新启动虚拟机。
* 重新启动 Linux 节点会重新启动容器。
* 重新启动StorageGRID Appliance 节点会重新启动计算控制器。



TIP: 如果需要重新启动多个节点，可以使用link:../maintain/rolling-reboot-procedure.html["滚动重启程序"]。

.步骤
. 选择*NODES*。
. 选择要重新启动的网格节点。
. 选择“*任务*”选项卡。
. 选择*重新启动*。
+
出现确认对话框。如果您正在重新启动主管理节点，确认对话框会提醒您，当服务停止时，您的浏览器与网格管理器的连接将暂时丢失。

. 输入配置密码，然后选择“*确定*”。
. 等待节点重新启动。
+
服务关闭可能需要一些时间。

+
当节点重新启动时，节点页面上会出现该节点的灰色（管理关闭）图标。当所有服务重新启动并且节点成功连接到电网时，“节点”页面应显示正常状态（节点名称左侧没有图标），表示没有活动警报并且节点已连接到电网。


