---
permalink: maintain/recovering-from-storage-node-failures.html 
sidebar: sidebar 
keywords: recover, storage node failure, Reaper 
summary: 恢复故障存储节点的过程取决于故障的类型和发生故障的存储节点的类型。 
---
= 从存储节点故障中恢复
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
恢复故障存储节点的过程取决于故障的类型和发生故障的存储节点的类型。

使用此表来选择故障存储节点的恢复过程。

[cols="1a,1a,1a"]
|===
| 问题描述 | 操作 | 笔记 


 a| 
* 多个存储节点发生故障。
* 在一个存储节点发生故障或恢复后不到 15 天，第二个存储节点也发生故障。
+
这包括一个存储节点发生故障而另一个存储节点的恢复仍在进行中的情况。


 a| 
请联系技术支持。
 a| 
恢复多个存储节点（或 15 天内恢复多个存储节点）可能会影响 Cassandra 数据库的完整性，从而导致数据丢失。

技术支持可以确定何时可以安全地开始恢复第二个存储节点。

*注意*：如果某个站点上包含 ADC 服务的多个存储节点发生故障，您将丢失该站点的所有待处理的平台服务请求。



 a| 
站点中多个存储节点发生故障或整个站点发生故障。
 a| 
请联系技术支持。可能需要执行站点恢复过程。
 a| 
技术支持将评估您的状况并制定恢复计划。看link:how-site-recovery-is-performed-by-technical-support.html["技术支持如何恢复站点"] 。



 a| 
设备存储节点发生故障。
 a| 
link:recovering-storagegrid-appliance-storage-node.html["恢复设备存储节点"]
 a| 
对于所有故障，设备存储节点的恢复过程都是相同的。



 a| 
一个或多个存储卷发生故障，但系统驱动器完好无损
 a| 
link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["从系统驱动器完好的存储卷故障中恢复"]
 a| 
此过程用于基于软件的存储节点。



 a| 
系统驱动器出现故障。
 a| 
link:reviewing-warnings-for-system-drive-recovery.html["从系统驱动器故障中恢复"]
 a| 
节点替换过程取决于部署平台以及是否有任何存储卷也发生故障。

|===

NOTE: 一些StorageGRID恢复程序使用 Reaper 来处理 Cassandra 修复。一旦相关或所需的服务开始，修复就会自动进行。您可能会注意到脚本输出中提到了“reaper”或“Cassandra repair”。如果您看到指示修复失败的错误消息，请运行错误消息中指示的命令。
