---
permalink: maintain/removing-port-remaps.html 
sidebar: sidebar 
keywords: storagegrid, recover, remove port remap, removing port remap, port remap 
summary: 如果要为负载均衡器服务配置端点，并且要使用已配置为端口重映射的映射到端口的端口，则必须先删除现有的端口重映射，否则端点将无效。您必须在每个具有冲突的重新映射端口的管理节点和网关节点上运行脚本，以删除该节点的所有端口重新映射。 
---
= 删除端口重新映射
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要为负载均衡器服务配置端点，并且要使用已配置为端口重映射的映射到端口的端口，则必须先删除现有的端口重映射，否则端点将无效。您必须在每个具有冲突的重新映射端口的管理节点和网关节点上运行脚本，以删除该节点的所有端口重新映射。

.关于此任务
此过程将删除所有端口重新映射。如果您需要保留一些重新映射，请联系技术支持。

有关配置负载均衡器端点的信息，请参阅link:../admin/configuring-load-balancer-endpoints.html["配置负载均衡器端点"]。


NOTE: 如果端口重新映射提供客户端访问，请重新配置客户端以使用不同的端口作为负载均衡器端点，以避免服务丢失。否则，删除端口映射将导致客户端访问丢失，应进行适当的安排。


NOTE: 此过程不适用于在裸机主机上作为容器部署的StorageGRID系统。请参阅说明link:removing-port-remaps-on-bare-metal-hosts.html["删除裸机主机上的端口重新映射"]。

.步骤
. 登录节点。
+
.. 输入以下命令： `ssh -p 8022 admin@node_IP`
+
端口 8022 是基础操作系统的 SSH 端口，而端口 22 是运行StorageGRID的容器引擎的 SSH 端口。

.. 输入 `Passwords.txt`文件。
.. 输入以下命令切换到root： `su -`
.. 输入 `Passwords.txt`文件。
+
当您以 root 身份登录时，提示符将从 `$`到 `#`。



. 运行以下脚本： `remove-port-remap.sh`
. 重启节点： `reboot`
. 退出命令外壳： `exit`
. 在每个具有冲突的重新映射端口的管理节点和网关节点上重复这些步骤。

