---
permalink: maintain/rename-grid-site-node-overview.html 
sidebar: sidebar 
keywords: rename grid, rename site, rename node, display name, system name 
summary: 根据需要，您可以更改整个网格、每个站点和每个节点在网格管理器中显示的显示名称。您可以随时安全地更新显示名称。 
---
= 使用重命名过程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据需要，您可以更改整个网格、每个站点和每个节点在网格管理器中显示的显示名称。您可以随时安全地更新显示名称。



== 重命名的程序是怎样的？

最初安装StorageGRID时，您需要为网格、每个站点和每个节点指定一个名称。这些初始名称称为_系统名称_，它们是整个StorageGRID中最初显示的名称。

系统名称是内部StorageGRID操作所必需的，并且不能更改。但是，您可以使用重命名过程为网格、每个站点和每个节点定义新的_显示名称_。这些显示名称出现在各种StorageGRID位置，而不是（或在某些情况下，除了）底层系统名称。

使用重命名过程来纠正拼写错误、实施不同的命名约定或指示站点及其所有节点已被重新定位。与系统名称不同，显示名称可以在需要时更新，并且不会影响StorageGRID操作。



== 系统名称和显示名称出现在哪里？

下表总结了系统名称和显示名称在StorageGRID用户界面和StorageGRID文件中的显示位置。

[cols="2a,2a,3a"]
|===
| 位置 | 系统名称 | 显示名称 


 a| 
网格管理器页面
 a| 
除非项目被重命名，否则显示
 a| 
如果某个项目被重命名，则会在以下位置显示系统名称：

* 信息板
* 节点页面
* 高可用性组、负载均衡器端点、VLAN 接口、密钥管理服务器、网格密码和防火墙控制的配置页面
* 警报
* 存储池定义
* 对象元数据查找页面
* 与维护程序相关的页面，包括升级、修补程序、 SANtricity OS 升级、停用、扩展、恢复和对象存在性检查
* 支持页面（日志和诊断）
* 单点登录页面，位于管理节点详细信息表中管理节点主机名旁边




 a| 
*NODES* > 节点的 *Overview* 选项卡
 a| 
始终显示
 a| 
仅当项目重命名时显示



 a| 
网格管理器中的旧页面（例如，*SUPPORT* > *Grid Topology*）
 a| 
显示
 a| 
未显示



 a| 
*节点健康* API
 a| 
总是返回
 a| 
仅当项目重命名时才返回



 a| 
使用 SSH 访问节点时提示
 a| 
显示为主要名称，除非该项目已重命名：

`admin@SYSTEM-NAME: ~ $`

当项目重命名时包含在括号中：

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`
 a| 
当项目重命名时显示为主名称：

`admin@DISPLAY-NAME(SYSTEM-NAME):~ $`



 a| 
`Passwords.txt`恢复包中的文件
 a| 
显示为 `Server Name`
 a| 
显示为 `Display Name`



 a| 
`/etc/hosts`所有节点上的文件

例如：

`10.96.99.128 SYSTEM-NAME 28989c59-a2c3-4d30-bb09-6879adf2437f DISPLAY-NAME localhost-grid # storagegrid-gen-host`
 a| 
始终显示在第二列
 a| 
当项目重命名时，显示在第四列



 a| 
`topology-display-names.json`，包含在AutoSupport数据中
 a| 
不包括
 a| 
除非项目已重命名，否则为空；否则，将网格、站点和节点 ID 映射到其显示名称。

|===


== 显示名称要求

在使用此过程之前，请查看显示名称的要求。



=== 显示节点的名称

节点的显示名称必须遵循以下规则：

* 在您的StorageGRID系统中必须是唯一的。
* 不能与StorageGRID系统中任何其他项目的系统名称相同。
* 必须至少包含 1 个字符，且不超过 32 个字符。
* 可以包含数字、连字符 (-) 以及大写和小写字母。
* 可以以字母或数字开头或结尾，但不能以连字符开头或结尾。
* 不能全是数字。
* 不区分大小写。例如， `DC1-ADM`和 `dc1-adm`被视为重复。


您可以使用其他节点先前使用的显示名称重命名节点，只要重命名不会导致重复的显示名称或系统名称。



=== 网格和站点的显示名称

网格和站点的显示名称遵循相同的规则，但有以下例外：

* 可以包含空格。
* 可以包含以下特殊字符： `= - _ : , . @ !`
* 可以以特殊字符（包括连字符）开头和结尾。
* 可以是全部数字或特殊字符。




== 显示名称最佳实践

如果您计划重命名多个项目，请在使用此过程之前记录您的一般命名方案。提出一个系统，确保名称唯一、一致且一目了然。

您可以使用任何适合您的组织要求的命名约定。请考虑以下关于应包含哪些内容的基本建议：

* *站点指示器*：如果您有多个站点，请为每个节点名称添加一个站点代码。
* *节点类型*：节点名称通常指示节点的类型。您可以使用以下缩写 `s`， `adm` ， 和 `gw`（存储节点、管理节点和网关节点）。
* *节点编号*：如果站点包含多个特定类型的节点，则在每个节点的名称后添加一个唯一的编号。


在向可能随时间而改变的名称添加具体细节之前，请三思。例如，不要在节点名称中包含 IP 地址，因为这些地址可能会更改。同样，如果您移动设备或升级硬件，机架位置或设备型号可能会发生变化。



=== 显示名称示例

假设您的StorageGRID系统有三个数据中心，并且每个数据中心都有不同类型的节点。您的显示名称可能像这样简单：

* *网格*： `StorageGRID Deployment`
* *第一个站点*： `Data Center 1`
+
** `dc1-adm1`
** `dc1-s1`
** `dc1-s2`
** `dc1-s3`
** `dc1-gw1`


* *第二个站点*： `Data Center 2`
+
** `dc2-adm2`
** `dc2-s1`
** `dc2-s2`
** `dc2-s3`


* *第三个站点*： `Data Center 3`
+
** `dc3-s1`
** `dc3-s2`
** `dc3-s3`



