---
permalink: maintain/restoring-prometheus-metrics-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore metrics, restore prometheus, primary admin node 
summary: 或者，您可以保留发生故障的主管理节点上由 Prometheus 维护的历史指标。只有当您的StorageGRID系统包含另一个管理节点时，才能恢复 Prometheus 指标。 
---
= 恢复主管理节点时恢复 Prometheus 指标
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
或者，您可以保留发生故障的主管理节点上由 Prometheus 维护的历史指标。只有当您的StorageGRID系统包含另一个管理节点时，才能恢复 Prometheus 指标。

.开始之前
* 恢复的管理节点已安装并正在运行。
* StorageGRID系统至少包含两个管理节点。
* 你有 `Passwords.txt`文件。
* 您有配置密码。


.关于此任务
如果管理节点发生故障，则管理节点上的 Prometheus 数据库中维护的指标将会丢失。当您恢复管理节点时，软件安装过程会创建一个新的 Prometheus 数据库。恢复的管理节点启动后，它会记录指标，就像您执行了StorageGRID系统的全新安装一样。

如果您恢复了主管理节点，并且您的StorageGRID系统有另一个管理节点，则可以通过将 Prometheus 数据库从非主管理节点（源管理节点）复制到恢复的主管理节点来恢复历史指标。如果您的系统只有一个主管理节点，则无法恢复 Prometheus 数据库。


NOTE: 复制 Prometheus 数据库可能需要一个小时或更长时间。当源管理节点上的服务停止时，某些网格管理器功能将不可用。

.步骤
. 登录源管理节点：
+
.. 输入以下命令： `ssh admin@_grid_node_IP_`
.. 输入 `Passwords.txt`文件。
.. 输入以下命令切换到root： `su -`
.. 输入 `Passwords.txt`文件。


. 从源管理节点停止 Prometheus 服务： `service prometheus stop`
. 在恢复的管理节点上完成以下步骤：
+
.. 登录到恢复的管理节点：
+
... 输入以下命令： `ssh admin@_grid_node_IP_`
... 输入 `Passwords.txt`文件。
... 输入以下命令切换到root： `su -`
... 输入 `Passwords.txt`文件。


.. 停止 Prometheus 服务： `service prometheus stop`
.. 将 SSH 私钥添加到 SSH 代理。进入：``ssh-add``
.. 输入 `Passwords.txt`文件。
.. 将 Prometheus 数据库从源管理节点复制到恢复的管理节点： `/usr/local/prometheus/bin/prometheus-clone-db.sh Source_Admin_Node_IP`
.. 出现提示时，按 *Enter* 确认您要销毁恢复的管理节点上的新 Prometheus 数据库。
+
原始 Prometheus 数据库及其历史数据被复制到恢复的管理节点。复制操作完成后，脚本将启动恢复的管理节点。出现如下状态：

+
数据库克隆，正在启动服务

.. 当您不再需要无密码访问其他服务器时，请从 SSH 代理中删除私钥。进入：``ssh-add -D``


. 在源管理节点上重启 Prometheus 服务.`service prometheus start`

