---
permalink: maintain/restoring-admin-node-database-non-primary-admin-node.html 
sidebar: sidebar 
keywords: storagegrid, recover, restore admin node database, restore database, non-primary admin node 
summary: 如果您想要保留有关发生故障的非主管理节点的属性和警报的历史信息，您可以从主管理节点恢复管理节点数据库。 
---
= 恢复非主管理节点时恢复管理节点数据库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要保留有关发生故障的非主管理节点的属性和警报的历史信息，您可以从主管理节点恢复管理节点数据库。

.开始之前
* 恢复的管理节点已安装并正在运行。
* StorageGRID系统至少包含两个管理节点。
* 你有 `Passwords.txt`文件。
* 您有配置密码。


.关于此任务
如果管理节点发生故障，则存储在其管理节点数据库中的历史信息将会丢失。该数据库包含以下信息：

* 警报历史记录
* 历史属性数据，用于节点页面上的传统图表中


恢复管理节点时，软件安装过程会在恢复的节点上创建一个空的管理节点数据库。但是，新数据库仅包含当前属于系统一部分或后来添加的服务器和服务的信息。

如果您恢复了非主管理节点，则可以通过将管理节点数据库从主管理节点（源管理节点）复制到恢复的节点来恢复历史信息。


NOTE: 复制管理节点数据库可能需要几个小时。当源节点上的服务停止时，某些网格管理器功能将不可用。

.步骤
. 登录源管理节点：
+
.. 输入以下命令： `ssh admin@_grid_node_IP_`
.. 输入 `Passwords.txt`文件。
.. 输入以下命令切换到root： `su -`
.. 输入 `Passwords.txt`文件。


. 从源管理节点运行以下命令。然后，如果出现提示，请输入配置密码。 `recover-access-points`
. 从源管理节点停止 MI 服务： `service mi stop`
. 从源管理节点停止管理应用程序接口 (mgmt-api) 服务： `service mgmt-api stop`
. 在恢复的管理节点上完成以下步骤：
+
.. 登录到恢复的管理节点：
+
... 输入以下命令： `ssh admin@_grid_node_IP_`
... 输入 `Passwords.txt`文件。
... 输入以下命令切换到root： `su -`
... 输入 `Passwords.txt`文件。


.. 停止 MI 服务： `service mi stop`
.. 停止 mgmt-api 服务： `service mgmt-api stop`
.. 将 SSH 私钥添加到 SSH 代理。进入：``ssh-add``
.. 输入 `Passwords.txt`文件。
.. 将数据库从源管理节点复制到恢复的管理节点： `/usr/local/mi/bin/mi-clone-db.sh Source_Admin_Node_IP`
.. 出现提示时，确认您要覆盖已恢复的管理节点上的 MI 数据库。
+
数据库及其历史数据被复制到恢复的管理节点。复制操作完成后，脚本启动恢复的管理节点。

.. 当您不再需要无密码访问其他服务器时，请从 SSH 代理中删除私钥。进入：``ssh-add -D``


. 重新启动源管理节点上的服务： `service servermanager start`

