---
permalink: maintain/restoring-network-connectivity-for-isolated-nodes.html 
sidebar: sidebar 
keywords: storagegrid, recover, network connection, restore network connection, isolated node, restore isolated node connection 
summary: 在某些情况下，一组或多组节点可能无法与电网的其余部分联系。例如，站点或网格范围的 IP 地址变化可能会导致孤立的节点。 
---
= 恢复孤立节点的网络连接
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在某些情况下，一组或多组节点可能无法与电网的其余部分联系。例如，站点或网格范围的 IP 地址变化可能会导致孤立的节点。

.关于此任务
节点隔离表示为：

* 警报，例如*无法与节点通信*（*警报* > *当前*）
* 与连接相关的诊断（*支持* > *工具* > *诊断*）


存在孤立节点的一些后果包括：

* 如果多个节点被隔离，您可能无法登录或访问网格管理器。
* 如果多个节点被隔离，租户管理器仪表板上显示的存储使用情况和配额值可能已过时。当网络连接恢复时，总数将会更新。


要解决隔离问题，您需要在每个隔离节点或与网格隔离的组中的一个节点（不包含主管理节点的子网中的所有节点）上运行命令行实用程序。该实用程序为节点提供网格中非孤立节点的 IP 地址，这使得孤立节点或节点组可以再次联系整个网格。


NOTE: 如果网络中禁用了多播域名系统 (mDNS)，您可能必须在每个隔离节点上运行命令行实用程序。

.步骤
当仅部分服务离线或报告通信错误时，此程序不适用。

. 访问节点并检查 `/var/local/log/dynip.log`用于隔离消息。
+
例如：

+
[listing]
----
[2018-01-09T19:11:00.545] UpdateQueue - WARNING -- Possible isolation, no contact with other nodes.
If this warning persists, manual action might be required.
----
+
如果您正在使用 VMware 控制台，它将包含一条消息，提示该节点可能被隔离。

+
在 Linux 部署中，隔离消息将出现在 `/var/log/storagegrid/node/<nodename>.log`文件。

. 如果隔离消息重复出现且持续存在，请运行以下命令：
+
`add_node_ip.py <address>`

+
在哪里 `<address>`是连接到电网的远程节点的 IP 地址。

+
[listing]
----
# /usr/sbin/add_node_ip.py  10.224.4.210

Retrieving local host information
Validating remote node at address 10.224.4.210
Sending node IP hint for 10.224.4.210 to local node
Local node found on remote node. Update complete.
----
. 对之前隔离的每个节点进行以下验证：
+
** 节点的服务已启动。
** 运行后，动态 IP 服务的状态为“正在运行” `storagegrid-status`命令。
** 在“节点”页面上，该节点不再显示与网格其余部分断开连接。





NOTE: 如果运行 `add_node_ip.py`命令不能解决问题，可能还有其他网络问题需要解决。
