---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, system drive warning, storage node 
summary: 在恢复存储节点的故障系统驱动器之前，请查看网格节点恢复的一般警告和注意事项以及以下具体警告。 
---
= 存储节点系统驱动器恢复警告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在恢复存储节点的故障系统驱动器之前，请查看常规link:warnings-and-considerations-for-grid-node-recovery.html["网格节点恢复的警告和注意事项"]以及以下具体警告。

存储节点有一个包含对象元数据的 Cassandra 数据库。在以下情况下可能会重建 Cassandra 数据库：

* 存储节点离线超过 15 天后将重新上线。
* 存储卷发生故障并已恢复。
* 系统驱动器和一个或多个存储卷发生故障并已恢复。


当 Cassandra 重建时，系统使用来自其他存储节点的信息。如果太多存储节点处于离线状态，某些 Cassandra 数据可能不可用。如果 Cassandra 最近重建，Cassandra 数据可能在整个网格中尚不一致。如果在太多存储节点离线时重建 Cassandra，或者在 15 天内重建两个或多个存储节点，则可能会发生数据丢失。


CAUTION: 如果多个存储节点出现故障（或离线），请联系技术支持。不要执行以下恢复过程。可能会发生数据丢失。


CAUTION: 如果这是存储节点故障或恢复后 15 天内第二次发生存储节点故障，请联系技术支持。在 15 天内在两个或更多存储节点上重建 Cassandra 可能会导致数据丢失。


NOTE: 如果站点上的多个存储节点发生故障，则可能需要站点恢复过程。看link:how-site-recovery-is-performed-by-technical-support.html["技术支持如何恢复站点"] 。


CAUTION: 如果此存储节点处于只读维护模式，以允许另一个具有故障存储卷的存储节点检索对象，则在恢复此故障存储节点之前，先恢复具有故障存储卷的存储节点上的卷。请参阅说明link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html["从系统驱动器完好的存储卷故障中恢复"]。


CAUTION: 如果 ILM 规则配置为仅存储一个复制副本，并且该副本存在于发生故障的存储卷上，则您将无法恢复该对象。
