---
permalink: maintain/step-3-revise-ilm-policy.html 
sidebar: sidebar 
keywords: storagegrid, recover, revise ilm policies 
summary: 从退役站点向导的步骤 3（修改 ILM 策略）中，您可以确定该站点是否被任何 ILM 策略引用。 
---
= 步骤 3：修改 ILM 政策
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
从退役站点向导的步骤 3（修改 ILM 策略）中，您可以确定该站点是否被任何 ILM 策略引用。

.开始之前
你对如何link:../ilm/index.html["使用 ILM 管理对象"]。您熟悉如何创建存储池和 ILM 规则以及如何模拟和激活 ILM 策略。

.关于此任务
如果任何策略（活动或非活动）中的任何 ILM 规则引用该站点，则StorageGRID无法停用该站点。

如果任何 ILM 策略引用了您想要停用的站点，则必须删除这些策略或编辑它们，以使它们满足以下要求：

* 全面保护所有对象数据。
* 不要提及您正在关闭的站点。
* 不要使用引用站点的存储池或使用“所有站点”选项。
* 不要使用引用该站点的擦除编码配置文件。
* 请勿使用StorageGRID 11.6 或更早版本安装中的 Make 2 Copies 规则。



CAUTION: 切勿创建单一副本 ILM 规则来适应站点的删除。任何时间段内仅创建一个复制副本的 ILM 规则会使数据面临永久丢失的风险。如果某个对象的副本只有一个，则当存储节点发生故障或出现重大错误时，该对象将会丢失。在升级等维护过程中，您还会暂时失去对该对象的访问权限。


TIP: 如果您正在执行_连接站点退役_，则必须考虑StorageGRID应如何管理当前要删除的站点上的对象数据。根据您的数据保护要求，新规则可以将现有对象数据移动到不同的站点，或者可以删除不再需要的任何额外对象副本。

如果您需要帮助设计新政策，请联系技术支持。

.步骤
. 从步骤 3（修改 ILM 政策）开始，确定是否有任何 ILM 政策涉及您选择退役的站点。
. 如果没有列出任何政策，请选择“下一步”转到link:step-4-remove-ilm-references.html["步骤 4：删除 ILM 引用"]。
. 如果列出了一个或多个_active_ ILM 策略，请克隆每个现有策略或创建不引用正在退役的站点的新策略：
+
.. 在策略名称列中选择该策略的链接。
+
该策略的 ILM 策略详细信息页面出现在新浏览器选项卡中。退役站点页面将在另一个选项卡上保持打开状态。

.. 根据需要遵循以下指南和说明：
+
*** 使用 ILM 规则：
+
**** link:../ilm/creating-storage-pool.html["创建一个或多个存储池"]不涉及该网站。
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html["编辑或替换规则"]引用该网站。
+

NOTE: 不要选择 *Make 2 Copies* 规则，因为该规则使用 *All Storage Nodes* 存储池，这是不允许的。



*** 使用 ILM 策略：
+
**** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#clone-ilm-policy["克隆现有的 ILM 策略"]或者link:../ilm/creating-ilm-policy.html["创建新的 ILM 策略"]。
**** 确保默认规则和其他规则不引用该站点。
+

CAUTION: 您必须确认 ILM 规则的顺序正确。当策略被激活时，新的和现有的对象将按照列出的顺序从顶部开始由规则进行评估。





.. 摄取测试对象并模拟策略以确保应用正确的规则。
+

CAUTION: ILM 策略中的错误可能会导致无法恢复的数据丢失。在激活该策略之前，请仔细检查并模拟该策略，以确认其能够按预期发挥作用。

+

CAUTION: 当您激活新的 ILM 策略时， StorageGRID会使用它来管理所有对象，包括现有对象和新摄取的对象。在激活新的 ILM 策略之前，请检查对现有复制和擦除编码对象的位置的任何更改。在评估和实施新位置时，更改现有对象的位置可能会导致临时资源问题。

.. 激活新策略并确保旧策略现在处于非活动状态。
+
如果您想激活多个策略，link:../ilm/creating-ilm-policy.html#activate-ilm-policy["按照步骤创建 ILM 策略标签"] 。

+
如果您正在执行已连接站点的退役， StorageGRID会在您激活新的 ILM 策略后立即开始从选定站点中删除对象数据。移动或删除所有对象副本可能需要数周时间。尽管您可以在对象数据仍然存在于站点时安全地启动站点退役，但是如果您允许在开始实际退役程序之前将数据从站点移出（通过在向导的第 5 步中选择 *开始退役*），则退役程序将更快完成，中断和性能影响更少。



. 对于每个_非活动_策略，通过首先选择每个策略的链接来编辑或删除它，如前面的步骤所述。
+
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#edit-ilm-policy["编辑策略"]所以它并不是指要退役的场地。
** link:../ilm/working-with-ilm-rules-and-ilm-policies.html#remove-ilm-policy["删除策略"] 。


. 当您完成对 ILM 规则和策略的更改时，步骤 3（修改 ILM 策略）中应该不再列出任何策略。选择“下一步”。
+
出现步骤 4（删除 ILM 引用）。


