---
permalink: maintain/warnings-and-considerations-for-grid-node-recovery.html 
sidebar: sidebar 
keywords: storagegrid, recover, warning 
summary: 如果网格节点发生故障，您必须尽快恢复它。在开始之前，您必须查看节点恢复的所有警告和注意事项。 
---
= 网格节点恢复的警告和注意事项
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果网格节点发生故障，您必须尽快恢复它。在开始之前，您必须查看节点恢复的所有警告和注意事项。


CAUTION: StorageGRID是一个由多个相互协作的节点组成的分布式系统。不要使用磁盘快照来恢复网格节点。相反，请参考每种节点类型的恢复和维护程序。


NOTE: 如果整个StorageGRID站点出现故障，请联系技术支持。技术支持将与您合作制定并执行站点恢复计划，以最大限度地恢复数据量并满足您的业务目标。看link:how-site-recovery-is-performed-by-technical-support.html["技术支持如何恢复站点"] 。

尽快恢复故障网格节点的一些原因包括：

* 发生故障的网格节点会降低系统和对象数据的冗余度，如果另一个节点发生故障，您将面临永久性数据丢失的风险。
* 电网节点故障会影响日常运营的效率。
* 网格节点故障会降低您监控系统操作的能力。
* 如果实施了严格的 ILM 规则，则发生故障的网格节点可能会导致 500 内部服务器错误。
* 如果网格节点没有及时恢复，恢复时间可能会增加。例如，在恢复完成之前可能会出现需要清除的队列。


始终遵循您正在恢复的特定类型的网格节点的恢复程序。主或非主管理节点、网关节点、设备节点和存储节点的恢复过程各不相同。



== 恢复网格节点的先决条件

恢复网格节点时假设以下所有条件：

* 出现故障的物理或虚拟硬件已被更换和配置。
* 替换设备上的StorageGRID Appliance Installer 版本与您的StorageGRID系统的软件版本相匹配，如 https://docs.netapp.com/us-en/storagegrid-appliances/installconfig/verifying-and-upgrading-storagegrid-appliance-installer-version.html["验证并升级StorageGRID Appliance Installer 版本"^]。
* 如果您正在恢复主管理节点以外的网格节点，则正在恢复的网格节点与主管理节点之间存在连接。
* 如果要恢复设备存储节点，则必须在设备安装期间指定与原始设备相同的存储类型（组合、仅元数据或仅数据）。如果指定不同的存储类型，恢复将失败，并且需要使用指定的正确存储类型重新安装设备。




== 当托管多个网格节点的服务器发生故障时，节点恢复的顺序

如果托管多个网格节点的服务器发生故障，您可以按任意顺序恢复节点。但是，如果发生故障的服务器托管主管理节点，则必须首先恢复该节点。首先恢复主管理节点可防止其他节点恢复因等待联系主管理节点而停止。



== 已恢复节点的 IP 地址

不要尝试使用当前分配给任何其他节点的 IP 地址来恢复节点。部署新节点时，请使用故障节点的当前 IP 地址或未使用的 IP 地址。

如果您使用新的 IP 地址部署新节点，然后恢复该节点，则恢复的节点将继续使用新的 IP 地址。如果要恢复到原始 IP 地址，请在恢复完成后使用更改 IP 工具。
