---
permalink: primer/hybrid-clouds-with-storagegrid.html 
sidebar: sidebar 
keywords: hybrid cloud, cloud storage pool, platform services, fabricpool, ontap 
summary: 通过实施策略驱动的数据管理将对象存储在云存储池中、利用StorageGRID平台服务以及使用NetApp FabricPool将数据从ONTAP到StorageGRID ，在混合云配置中使用StorageGRID 。 
---
= 采用StorageGRID的混合云
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过实施策略驱动的数据管理将对象存储在云存储池中、利用StorageGRID平台服务以及使用NetApp FabricPool将数据从ONTAP到StorageGRID ，在混合云配置中使用StorageGRID 。



== 云存储池

云存储池允许您存储StorageGRID系统之外的对象。例如，您可能希望将不经常访问的对象移动到成本较低的云存储，例如 Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud 或 Microsoft Azure Blob 存储中的存档访问层。或者，您可能希望维护StorageGRID对象的云备份，可用于恢复因存储卷或存储节点故障而丢失的数据。

还支持第三方合作伙伴存储，包括磁盘和磁带存储。


NOTE: 不支持将云存储池与FabricPool一起使用，因为从云存储池目标检索对象会增加延迟。



== S3平台服务

S3 平台服务使您能够使用远程服务作为对象复制、事件通知或搜索集成的端点。平台服务独立于网格的 ILM 规则运行，并为单独的 S3 存储桶启用。支持以下服务：

* CloudMirror 复制服务自动将指定对象镜像到目标 S3 存储桶，该存储桶可以位于 Amazon S3 或第二个StorageGRID系统上。
* 事件通知服务将有关指定操作的消息发送到支持接收简单通知服务 (Amazon SNS) 事件的外部端点。
* 搜索集成服务将对象元数据发送到外部 Elasticsearch 服务，允许使用第三方工具搜索、可视化和分析元数据。


例如，您可以使用 CloudMirror 复制将特定客户记录镜像到 Amazon S3，然后利用 AWS 服务对您的数据执行分析。



== 使用FabricPool进行ONTAP数据分层

您可以使用FabricPool将数据分层到StorageGRID ，从而降低ONTAP存储的成本。  FabricPool支持将数据自动分层到低成本的对象存储层（无论是在内部还是外部）。

与手动分层解决方案不同， FabricPool通过自动化数据分层来降低存储成本，从而降低总体拥有成本。它通过分层到公共云和私有云（包括StorageGRID）来实现云经济的优势。

.相关信息
* link:../ilm/what-cloud-storage-pool-is.html["什么是云存储池？"]
* link:../tenant/what-platform-services-are.html["管理平台服务"]
* link:../fabricpool/index.html["为FabricPool配置StorageGRID"]

