---
permalink: primer/what-storage-node-is.html 
sidebar: sidebar 
keywords: what is a storage node, how many storage nodes 
summary: 存储节点管理和存储对象数据和元数据。存储节点包括在磁盘上存储、移动、验证和检索对象数据和元数据所需的服务和流程。 
---
= 什么是存储节点？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
存储节点管理和存储对象数据和元数据。存储节点包括在磁盘上存储、移动、验证和检索对象数据和元数据所需的服务和流程。

StorageGRID系统中的每个站点必须至少有三个存储节点。



== 存储节点的类型

在安装过程中，您可以选择要安装的存储节点类型。这些类型适用于基于软件的存储节点和支持该功能的基于设备的存储节点：

* 组合数据和元数据存储节点
* 仅元数据存储节点
* 纯数据存储节点


您可以在以下情况下选择存储节点类型：

* 最初安装存储节点时
* 在StorageGRID系统扩展期间添加存储节点时



NOTE: 存储节点安装完成后，您无法更改类型。

数据和元数据存储节点（组合）:: 默认情况下，所有新的存储节点都将存储对象数据和元数据。这种类型的存储节点称为组合存储节点。
仅元数据存储节点:: 如果您的网格存储了大量的小对象，那么专门使用存储节点来存储元数据是有意义的。安装专用元数据容量可以在大量小对象所需的空间和这些对象的元数据所需的空间之间实现更好的平衡。此外，高性能设备上托管的仅元数据存储节点可以提高性能。


仅元数据存储节点具有特定的硬件要求：

* 使用StorageGRID设备时，只能在具有 12 个 1.9 TB 或 12 个 3.8 TB 驱动器的 SGF6112 设备上配置仅元数据节点。
* 使用基于软件的节点时，仅元数据节点资源必须与现有的存储节点资源相匹配。例如：
+
** 如果现有StorageGRID站点使用 SG6000 或 SG6100 设备，则基于软件的仅元数据节点必须满足以下最低要求：
+
*** 128 GB 内存
*** 8核CPU
*** 8 TB SSD 或用于 Cassandra 数据库的等效存储空间（rangedb/0）


** 如果现有的StorageGRID站点使用具有 24 GB RAM、8 核 CPU 和 3 TB 或 4TB 元数据存储的虚拟存储节点，则基于软件的仅元数据节点应使用类似的资源（24 GB RAM、8 核 CPU 和 4TB 元数据存储（rangedb/0）。


* 添加新的StorageGRID站点时，新站点的总元数据容量至少应与现有StorageGRID站点相匹配，并且新站点资源应与现有StorageGRID站点的存储节点相匹配。


安装仅元数据节点时，网格还必须包含用于数据存储的最小数量的节点：

* 对于单站点网格，配置至少两个组合或仅数据的存储节点。
* 对于多站点网格，每个站点至少配置一个组合或仅数据的存储节点。



NOTE: 尽管仅元数据存储节点包含<<ldr-service,LDR 服务>>并且可以处理 S3 客户端请求， StorageGRID性能可能不会提高。

纯数据存储节点:: 如果您的存储节点具有不同的性能特征，则专门使用存储节点来存储数据是有意义的。例如，为了潜在地提高性能，您可以使用仅数据、高容量旋转磁盘存储节点以及仅元数据的高性能存储节点。


安装仅数据节点时，网格必须包含以下内容：

* 每个网格至少有两个组合或仅数据存储节点
* 每个站点至少一个组合或仅数据存储节点
* 每个站点至少有三个组合或仅元数据存储节点




== 存储节点的主要服务

下表显示了存储节点的主要服务；但是，此表并未列出所有节点服务。


NOTE: 某些服务（例如 ADC 服务和 RSM 服务）通常仅存在于每个站点的三个存储节点上。

[cols="1a,3a"]
|===
| 服务 | 按键功能 


 a| 
帐户（acct）
 a| 
管理租户帐户。



 a| 
管理域控制器 (ADC)
 a| 
维护拓扑和电网范围的配置。

*注意*：仅数据存储节点不托管 ADC 服务。

.详细信息
[%collapsible]
====
管理域控制器 (ADC) 服务对网格节点及其相互之间的连接进行验证。  ADC 服务托管在一个站点的至少三个存储节点上。

ADC 服务维护拓扑信息，包括服务的位置和可用性。当一个网格节点需要来自另一个网格节点的信息或需要另一个网格节点执行的操作时，它会联系 ADC 服务来找到最佳的网格节点来处理其请求。此外，ADC 服务保留了StorageGRID部署的配置包的副本，允许任何网格节点检索当前配置信息。

为了促进分布式和孤立操作，每个 ADC 服务都会与StorageGRID系统中的其他 ADC 服务同步证书、配置包以及有关服务和拓扑的信息。

一般来说，所有网格节点都与至少一个 ADC 服务保持连接。这确保了网格节点始终能够访问最新信息。当网格节点连接时，它们会缓存其他网格节点的证书，使得系统即使在 ADC 服务不可用时也能继续与已知的网格节点一起运行。新的网格节点只能使用 ADC 服务建立连接。

每个网格节点的连接使得 ADC 服务能够收集拓扑信息。该网格节点信息包括 CPU 负载、可用磁盘空间（如果有存储）、支持的服务以及网格节点的站点 ID。其他服务通过拓扑查询向 ADC 服务询问拓扑信息。  ADC 服务使用从StorageGRID系统收到的最新信息来响应每个查询。

====


 a| 
Cassandra
 a| 
存储和保护对象元数据。

*注意*：仅数据存储节点不托管 Cassandra 服务。



 a| 
卡桑德拉·雷珀
 a| 
执行对象元数据的自动修复。

*注意*：仅数据存储节点不托管 Cassandra Reaper 服务。



 a| 
块
 a| 
管理擦除编码数据和奇偶校验片段。



 a| 
数据移动器 (dmv)
 a| 
将数据移动到云存储池。



 a| 
分布式数据存储（DDS）
 a| 
监控对象元数据存储。

.详细信息
[%collapsible]
====
每个存储节点都包含分布式数据存储 (DDS) 服务。该服务与 Cassandra 数据库交互，对存储在StorageGRID系统中的对象元数据执行后台任务。

DDS 服务跟踪进入StorageGRID系统的对象总数以及通过系统支持的每个接口 (S3) 提取的对象总数。

====


 a| 
身份（idnt）
 a| 
联合 LDAP 和 Active Directory 的用户身份。



 a| 
[[ldr-service]]本地分发路由器 (LDR)
 a| 
处理对象存储协议请求并管理磁盘上的对象数据。

.详细信息
[%collapsible]
====
每个_组合_、_仅数据_和_仅元数据_存储节点都包括本地分发路由器 (LDR) 服务。该服务处理内容传输功能，包括数据存储、路由和请求处理。  LDR 服务通过处理数据传输负载和数据流量功能完成了StorageGRID系统的大部分艰苦工作。

LDR 服务处理以下任务：

* 查询
* 信息生命周期管理 (ILM) 活动
* 对象删除
* 对象数据存储
* 从另一个 LDR 服务（存储节点）传输对象数据
* 数据存储管理
* S3协议接口


LDR 服务还将每个 S3 对象映射到其唯一的 UUID。

对象存储:: LDR 服务的底层数据存储被划分为固定数量的对象存储（也称为存储卷）。每个对象存储都是一个单独的挂载点。
+
--
存储节点中的对象存储由从 0000 到 002F 的十六进制数标识，该数字称为卷 ID。第一个对象存储（卷 0）中保留了空间，用于存储 Cassandra 数据库中的对象元数据；该卷上的任何剩余空间都用于存储对象数据。所有其他对象存储专门用于对象数据，其中包括复制的副本和擦除编码片段。

为了确保复制副本的空间使用均匀，给定对象的对象数据将根据可用存储空间存储到一个对象存储中。当对象存储填满容量时，剩余的对象存储将继续存储对象，直到存储节点上没有更多空间。

--
元数据保护:: StorageGRID将对象元数据存储在 Cassandra 数据库中，该数据库与 LDR 服务交互。
+
--
为了确保冗余并防止丢失，每个站点都保留了三个对象元数据副本。此复制不可配置且自动执行。有关详细信息，请参阅link:../admin/managing-object-metadata-storage.html["管理对象元数据存储"] 。

--


====


 a| 
复制状态机（RSM）
 a| 
确保 S3 平台服务请求发送到各自的端点。



 a| 
服务器状态监视器（SSM）
 a| 
监控操作系统和底层硬件。

|===