---
permalink: primer/what-gateway-node-is.html 
sidebar: sidebar 
keywords: gateway nodes, api gateway 
summary: 网关节点提供专用的负载平衡接口，S3 客户端应用程序可以使用它来连接到StorageGRID。负载平衡通过在多个存储节点之间分配工作负载来最大限度地提高速度和连接容量。网关节点是可选的。 
---
= 什么是网关节点？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
网关节点提供专用的负载平衡接口，S3 客户端应用程序可以使用它来连接到StorageGRID。负载平衡通过在多个存储节点之间分配工作负载来最大限度地提高速度和连接容量。网关节点是可选的。

所有管理节点和所有网关节点均提供StorageGRID负载均衡器服务。它执行客户端请求的传输层安全性 (TLS) 终止，检查请求，并与存储节点建立新的安全连接。负载均衡器服务无缝地将客户端引导至最佳存储节点，以便节点甚至整个站点的故障都是透明的。

您可以配置一个或多个负载均衡器端点来定义传入和传出客户端请求将用于访问网关和管理节点上的负载均衡器服务的端口和网络协议（HTTPS 或 HTTP）。负载均衡器端点还定义客户端类型（S3）、绑定模式以及可选的允许或阻止租户列表。看link:../admin/managing-load-balancing.html["负载平衡的注意事项"] 。

根据需要，您可以将多个网关节点和管理节点的网络接口分组为高可用性 (HA) 组。如果 HA 组中的活动接口出现故障，则备份接口可以管理客户端应用程序工作负载。看link:../admin/managing-high-availability-groups.html["管理高可用性 (HA) 组"] 。



== 网关节点的主要服务

下表显示了网关节点的主要服务；但是，该表并未列出所有节点服务。

[cols="1a,2a"]
|===
| 服务 | 按键功能 


 a| 
高可用性
 a| 
管理管理节点和网关节点组的高可用性虚拟 IP 地址。

*注意：*此服务也可在管理节点上找到。



 a| 
负载均衡器
 a| 
提供从客户端到存储节点的 S3 流量的第 7 层负载平衡。这是推荐的负载平衡机制。

*注意：*此服务也可在管理节点上找到。



 a| 
服务器状态监视器（SSM）
 a| 
监控操作系统和底层硬件。

|===