---
permalink: primer/what-admin-node-is.html 
sidebar: sidebar 
keywords: admin nodes 
summary: 管理节点提供系统配置、监控和日志记录等管理服务。管理节点还可用于平衡 S3 客户端流量的负载。每个网格必须有一个主管理节点，并且可以有任意数量的非主管理节点以实现冗余。 
---
= 什么是管理节点？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理节点提供系统配置、监控和日志记录等管理服务。管理节点还可用于平衡 S3 客户端流量的负载。每个网格必须有一个主管理节点，并且可以有任意数量的非主管理节点以实现冗余。



== 主管理节点和非主管理节点之间的差异

当您登录到网格管理器或租户管理器时，您正在连接到管理节点。您可以连接到任何管理节点，每个管理节点都会显示StorageGRID系统的类似视图。但是，主管理节点比非主管理节点提供更多功能。例如，大多数维护程序必须从主管理节点执行。

该表总结了主管理节点和非主管理节点的功能。

[cols="2a,1a,1a"]
|===
| 功能 | 主管理节点 | 非主管理节点 


 a| 
包括<<ams,AMS>>服务
 a| 
是
 a| 
是



 a| 
包括<<cmn,厘米纳米>>服务
 a| 
是
 a| 
否



 a| 
包括<<nms,NMS>>服务
 a| 
是
 a| 
是



 a| 
包括<<prometheus,普罗米修斯>>服务
 a| 
是
 a| 
是



 a| 
包括<<ssm,萨姆>>服务
 a| 
是
 a| 
是



 a| 
包括<<load-balancer,负载均衡器>>和<<high-availability,高可用性>>服务
 a| 
是
 a| 
是



 a| 
支持<<mgmt-api,管理应用程序接口>>（管理 API）
 a| 
是
 a| 
是



 a| 
可用于所有与网络相关的维护任务，例如 IP 地址更改和更新 NTP 服务器
 a| 
是
 a| 
否



 a| 
可以在存储节点扩展后执行 EC 重新平衡
 a| 
是
 a| 
否



 a| 
可用于音量恢复程序
 a| 
是
 a| 
是



 a| 
可以从一个或多个节点收集日志文件和系统数据
 a| 
是
 a| 
否



 a| 
发送警报通知、 AutoSupport包和 SNMP 陷阱并通知
 a| 
是作为<<preferred-sender,首选发件人>>。
 a| 
是充当备用发送者。

|===


== [[preferred-sender]]首选发件人管理节点

如果您的StorageGRID部署包含多个管理节点，则主管理节点是警报通知、 AutoSupport包以及 SNMP 陷阱和通知的首选发送者。

在正常系统操作下，只有首选发送者发送通知。但是，所有其他管理节点都会监控首选发送者。如果检测到问题，其他管理节点将充当_备用发送者_。

在以下情况下可能会发送多条通知：

* 如果管理节点彼此“孤立”，则首选发送者和备用发送者都会尝试发送通知，并且可能会收到多份通知副本。
* 如果备用发送器检测到首选发送器出现问题并开始发送通知，则首选发送器可能会重新获得发送通知的能力。如果发生这种情况，可能会发送重复的通知。当备用发送器不再检测到首选发送器上的错误时，它将停止发送通知。
+

NOTE: 当您测试AutoSupport包时，所有管理节点都会发送测试。测试警报通知时，您必须登录每个管理节点以验证连接性。





== 管理节点的主要服务

下表显示了管理节点的主要服务；但是，此表并未列出所有节点服务。

[cols="1a,2a"]
|===
| 服务 | 按键功能 


 a| 
审计管理系统 (AMS)
 a| 
跟踪系统活动和事件。



 a| 
[[cmn]]配置管理节点 (CMN)
 a| 
管理整个系统配置。



 a| 
高可用性
 a| 
管理管理节点和网关节点组的高可用性虚拟 IP 地址。

*注意：*此服务也可在网关节点上找到。



 a| 
负载均衡器
 a| 
提供从客户端到存储节点的 S3 流量负载平衡。

*注意：*此服务也可在网关节点上找到。



 a| 
[[mgmt-api]]管理应用程序接口 (mgmt-api)
 a| 
处理来自网格管理 API 和租户管理 API 的请求。



 a| 
网络管理系统 (NMS)
 a| 
为网格管理器提供功能。



 a| 
普罗米修斯
 a| 
收集并存储来自所有节点上的服务的时间序列指标。



 a| 
[[ssm]]服务器状态监视器 (SSM)
 a| 
监控操作系统和底层硬件。

|===