---
permalink: expand/copying-prometheus-metrics.html 
sidebar: sidebar 
keywords: prometheus, copy metrics, Admin Node expansion 
summary: 添加新的管理节点后，您可以选择将 Prometheus 维护的历史指标从主管理节点复制到新的管理节点。复制指标可确保管理节点之间的历史指标保持一致。 
---
= 复制 Prometheus 指标
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
添加新的管理节点后，您可以选择将 Prometheus 维护的历史指标从主管理节点复制到新的管理节点。复制指标可确保管理节点之间的历史指标保持一致。

.开始之前
* 新的管理节点已安装并正在运行。
* 你有 `Passwords.txt`文件。
* 您有配置密码。


.关于此任务
当您添加管理节点时，软件安装过程会创建一个新的 Prometheus 数据库。您可以通过将 Prometheus 数据库从主管理节点（源管理节点）复制到新的管理节点来保持节点之间的历史指标一致。


NOTE: 复制 Prometheus 数据库可能需要一个小时或更长时间。当源管理节点上的服务停止时，某些网格管理器功能将不可用。

.步骤
. 登录源管理节点：
+
.. 输入以下命令： `ssh admin@_grid_node_IP_`
.. 输入 `Passwords.txt`文件。
.. 输入以下命令切换到root： `su -`
.. 输入 `Passwords.txt`文件。


. 从源管理节点停止 Prometheus 服务： `service prometheus stop`
. 在新的管理节点上完成以下步骤：
+
.. 登录到新的管理节点：
+
... 输入以下命令： `ssh admin@_grid_node_IP_`
... 输入 `Passwords.txt`文件。
... 输入以下命令切换到root： `su -`
... 输入 `Passwords.txt`文件。


.. 停止 Prometheus 服务： `service prometheus stop`
.. 将 SSH 私钥添加到 SSH 代理。进入：``ssh-add``
.. 输入 `Passwords.txt`文件。
.. 将 Prometheus 数据库从源管理节点复制到新的管理节点： `/usr/local/prometheus/bin/prometheus-clone-db.sh _Source_Admin_Node_IP_`
.. 出现提示时，按 *Enter* 确认您要销毁新管理节点上的新 Prometheus 数据库。
+
原有的Prometheus数据库及其历史数据复制到新的Admin Node。复制操作完成后，脚本将启动新的管理节点。出现如下状态：

+
`Database cloned, starting services`

.. 当您不再需要无密码访问其他服务器时，请从 SSH 代理中删除私钥。进入：
+
`ssh-add -D`



. 在源管理节点上重新启动 Prometheus 服务。
+
`service prometheus start`


