---
permalink: expand/copying-audit-logs.html 
sidebar: sidebar 
keywords: copy audit log, Admin Node expansion, 
summary: 当您通过扩展程序添加新的管理节点时，其 AMS 服务仅记录其加入系统后发生的事件和操作。根据需要，您可以将审计日志从先前安装的管理节点复制到新的扩展管理节点，以便它与StorageGRID系统的其余部分同步。 
---
= 复制审计日志
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当您通过扩展程序添加新的管理节点时，其 AMS 服务仅记录其加入系统后发生的事件和操作。根据需要，您可以将审计日志从先前安装的管理节点复制到新的扩展管理节点，以便它与StorageGRID系统的其余部分同步。

.开始之前
* 您已完成添加管理节点所需的扩展步骤。
* 你有 `Passwords.txt`文件。


.关于此任务
要使历史审计消息在新的管理节点上可用，您必须将审计日志文件从现有管理节点手动复制到扩展管理节点。

[NOTE]
====
默认情况下，审计信息会发送到管理节点上的审计日志。如果满足以下任一条件，则可以跳过这些步骤：

* 您配置了外部系统日志服务器，审计日志现在被发送到系统日志服务器而不是管理节点。
* 您明确指定审计消息应仅保存在生成它们的本地节点上。


看link:../monitor/configure-audit-messages.html["配置审计消息和日志目标"]了解详情。

====
.步骤
. 登录到主管理节点：
+
.. 输入以下命令： `ssh _admin@_primary_Admin_Node_IP_`
.. 输入 `Passwords.txt`文件。
.. 输入以下命令切换到root： `su -`
.. 输入 `Passwords.txt`文件。
+
当您以 root 身份登录时，提示符将从 `$`到 `#`。



. 停止 AMS 服务以防止其创建新文件： `service ams stop`
. 导航到审计导出目录：
+
`cd /var/local/log`

. 重命名源 `audit.log`文件以确保它不会覆盖您要将其复制到的扩展管理节点上的文件：
+
[listing]
----
ls -l
mv audit.log _new_name_.txt
----
. 将所有审计日志文件复制到扩展管理节点上的目标位置：
+
`scp -p * _IP_address_:/var/local/log`

. 如果提示输入密码 `/root/.ssh/id_rsa`，输入列出的主管理节点的 SSH 访问密码 `Passwords.txt`文件。
. 恢复原状 `audit.log`文件：
+
`mv _new_name_.txt audit.log`

. 启动 AMS 服务：
+
`service ams start`

. 从服务器注销：
+
`exit`

. 登录扩展管理节点：
+
.. 输入以下命令： `ssh admin@_expansion_Admin_Node_IP_`
.. 输入 `Passwords.txt`文件。
.. 输入以下命令切换到root： `su -`
.. 输入 `Passwords.txt`文件。
+
当您以 root 身份登录时，提示符将从 `$`到 `#`。



. 更新审计日志文件的用户和组设置：
+
`cd /var/local/log`

+
`chown ams-user:bycast *`

. 从服务器注销：
+
`exit`


