---
permalink: expand/linux-adding-direct-attached-or-san-volumes-to-storage-node.html 
sidebar: sidebar 
keywords: expansion, Linux, add storage volumes 
summary: 如果存储节点包含的存储卷少于 48 个，则可以通过添加新的块存储设备、使其对 Linux 主机可见以及将新的块设备映射添加到用于存储节点的StorageGRID配置文件来增加其容量。 
---
= Linux：向存储节点添加直接连接卷或 SAN 卷
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果存储节点包含的存储卷少于 48 个，则可以通过添加新的块存储设备、使其对 Linux 主机可见以及将新的块设备映射添加到用于存储节点的StorageGRID配置文件来增加其容量。

.开始之前
* 您可以访问为您的 Linux 平台安装StorageGRID的说明。
+
** link:../rhel/index.html["在 Red Hat Enterprise Linux 上安装StorageGRID"]
** link:../ubuntu/index.html["在 Ubuntu 或 Debian 上安装StorageGRID"]


* 你有 `Passwords.txt`文件。
* 你有link:../admin/admin-group-permissions.html["特定访问权限"]。



CAUTION: 当软件升级、恢复过程或其他扩展过程处于活动状态时，请勿尝试将存储卷添加到存储节点。

.关于此任务
添加存储卷时，存储节点短时间内不可用。您应该一次在一个存储节点上执行此过程，以避免影响面向客户端的网格服务。

.步骤
. 安装新的存储硬件。
+
有关详细信息，请参阅硬件供应商提供的文档。

. 创建所需大小的新块存储卷。
+
** 根据需要连接新驱动器并更新 RAID 控制器配置，或者在共享存储阵列上分配新的 SAN LUN 并允许 Linux 主机访问它们。
** 使用与现有存储节点上的存储卷相同的持久命名方案。
** 如果您使用StorageGRID节点迁移功能，请使新卷对作为此存储节点的迁移目标的其他 Linux 主机可见。有关更多信息，请参阅为您的 Linux 平台安装StorageGRID的说明。


. 以 root 身份或具有 sudo 权限的帐户登录支持存储节点的 Linux 主机。
. 确认新的存储卷在 Linux 主机上可见。
+
您可能需要重新扫描设备。

. 运行以下命令暂时禁用存储节点：
+
`sudo storagegrid node stop <node-name>`

. 使用 vim 或 pico 等文本编辑器，编辑存储节点的节点配置文件，该文件可在以下位置找到 `/etc/storagegrid/nodes/<node-name>.conf`。
. 找到包含现有对象存储块设备映射的节点配置文件部分。
+
在示例中， `BLOCK_DEVICE_RANGEDB_00`到 `BLOCK_DEVICE_RANGEDB_03`是现有的对象存储块设备映射。

+
[listing, subs="specialcharacters,quotes"]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/sgws-sn1-var-local
*BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/sgws-sn1-rangedb-0*
*BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/sgws-sn1-rangedb-1*
*BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/sgws-sn1-rangedb-2*
*BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/sgws-sn1-rangedb-3*
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----
. 添加与您为此存储节点添加的块存储卷相对应的新对象存储块设备映射。
+
确保从下一个 `BLOCK_DEVICE_RANGEDB_nn`。不要留下空隙。

+
** 根据上面的例子，从 `BLOCK_DEVICE_RANGEDB_04`。
** 在下面的示例中，四个新的块存储卷已添加到节点： `BLOCK_DEVICE_RANGEDB_04`到 `BLOCK_DEVICE_RANGEDB_07`。


+
[listing, subs="specialcharacters,quotes"]
----
NODE_TYPE = VM_Storage_Node
ADMIN_IP = 10.1.0.2
BLOCK_DEVICE_VAR_LOCAL = /dev/mapper/sgws-sn1-var-local
BLOCK_DEVICE_RANGEDB_00 = /dev/mapper/sgws-sn1-rangedb-0
BLOCK_DEVICE_RANGEDB_01 = /dev/mapper/sgws-sn1-rangedb-1
BLOCK_DEVICE_RANGEDB_02 = /dev/mapper/sgws-sn1-rangedb-2
BLOCK_DEVICE_RANGEDB_03 = /dev/mapper/sgws-sn1-rangedb-3
*BLOCK_DEVICE_RANGEDB_04 = /dev/mapper/sgws-sn1-rangedb-4*
*BLOCK_DEVICE_RANGEDB_05 = /dev/mapper/sgws-sn1-rangedb-5*
*BLOCK_DEVICE_RANGEDB_06 = /dev/mapper/sgws-sn1-rangedb-6*
*BLOCK_DEVICE_RANGEDB_07 = /dev/mapper/sgws-sn1-rangedb-7*
GRID_NETWORK_TARGET = bond0.1001
ADMIN_NETWORK_TARGET = bond0.1002
CLIENT_NETWORK_TARGET = bond0.1003
GRID_NETWORK_IP = 10.1.0.3
GRID_NETWORK_MASK = 255.255.255.0
GRID_NETWORK_GATEWAY = 10.1.0.1
----
. 运行以下命令来验证对存储节点的节点配置文件的更改：
+
`sudo storagegrid node validate <node-name>`

+
在继续下一步之前，请解决所有错误或警告。

+
[NOTE]
====
如果您观察到类似以下的错误，则表示节点配置文件正在尝试映射所使用的块设备 `<node-name>`为了 `<PURPOSE>`给定 `<path-name>`在 Linux 文件系统中，但该位置没有有效的块设备特殊文件（或指向块设备特殊文件的软链接）。

[listing]
----
Checking configuration file for node <node-name>…
ERROR: BLOCK_DEVICE_<PURPOSE> = <path-name>
<path-name> is not a valid block device
----
确认您输入了正确的 `<path-name>`。

====
. 运行以下命令以使用新的块设备映射重新启动节点：
+
`sudo storagegrid node start <node-name>`

. 使用列出的密码以管理员身份登录存储节点 `Passwords.txt`文件。
. 检查服务是否正确启动：
+
.. 查看服务器上所有服务的状态列表：+
`sudo storagegrid-status`
+
状态会自动更新。

.. 等到所有服务都正在运行或已验证。
.. 退出状态屏幕：
+
`Ctrl+C`



. 配置新存储以供存储节点使用：
+
.. 配置新的存储卷：
+
`sudo add_rangedbs.rb`

+
该脚本会查找任何新的存储卷并提示您对其进行格式化。

.. 输入 *y* 格式化存储卷。
.. 如果任何卷之前已被格式化，请决定是否要重新格式化它们。
+
*** 输入 *y* 重新格式化。
*** 输入 *n* 跳过重新格式化。




+
这 `setup_rangedbs.sh`脚本自动运行。

. 验证存储节点的存储状态是否为在线：
+
.. Sign inlink:../admin/web-browser-requirements.html["支持的网络浏览器"]。
.. 选择*支持* > *工具* > *网格拓扑*。
.. 选择 *_site_* > *_Storage Node_* > *LDR* > *Storage*。
.. 选择“*配置*”选项卡，然后选择“*主要*”选项卡。
.. 如果“*存储状态 - 所需*”下拉列表设置为“只读”或“离线”，请选择“*在线*”。
.. 单击“应用更改”。


. 要查看新的对象存储：
+
.. 选择 *NODES* > *_site_* > *_Storage Node_* > *Storage*。
.. 查看*对象存储*表中的详细信息。




.结果
您现在可以使用存储节点的扩展容量来保存对象数据。
