---
permalink: ilm/advantages-disadvantages-of-ingest-options.html 
sidebar: sidebar 
keywords: ingest options, balance ingest, strict ingest, dual commit ingest 
summary: 了解在摄取时保护数据的三个选项（平衡、严格或双重提交）各自的优缺点可以帮助您决定选择哪一个作为 ILM 规则。 
---
= 摄取选项的优点、缺点和局限性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解在摄取时保护数据的三个选项（平衡、严格或双重提交）各自的优缺点可以帮助您决定选择哪一个作为 ILM 规则。

有关收录选项的概述，请参阅link:data-protection-options-for-ingest.html["收录选项"]。



== 平衡和严格选项的优势

与在摄取期间创建临时副本的双重提交相比，两个同步放置选项可以提供以下优势：

* *更好的数据安全性*：对象数据按照 ILM 规则的放置指令立即受到保护，可以配置为防止各种故障情况，包括多个存储位置的故障。双重提交只能防止丢失单个本地副本。
* *更高效的网格操作*：每个对象在被摄取时只处理一次。由于StorageGRID系统不需要跟踪或删除临时副本，因此处理负载更少，消耗的数据库空间也更少。
* *(平衡)推荐*：平衡选项提供最佳的 ILM 效率。建议使用平衡选项，除非需要严格的摄取行为或网格满足使用双重提交的所有标准。
* *（严格）关于对象位置的确定性*：严格选项保证对象根据 ILM 规则中的放置说明立即存储。




== 平衡和严格选项的缺点

与双重提交相比，平衡和严格选项有一些缺点：

* *更长的客户端摄取时间*：客户端摄取延迟可能会更长。当您使用“平衡”或“严格”选项时，直到创建并存储所有擦除编码片段或复制副本后，“摄取成功”消息才会返回给客户端。然而，对象数据很可能会更快地到达其最终位置。
* *（严格）更高的摄取失败率*：使用严格选项时，只要StorageGRID无法立即制作 ILM 规则中指定的所有副本，摄取就会失败。如果所需的存储位置暂时离线或网络问题导致站点之间复制对象延迟，您可能会看到高摄取失败率。
* *（严格）S3 分段上传位置在某些情况下可能不符合预期*：使用严格设置时，您希望对象按照 ILM 规则的描述进行放置，否则摄取将失败。但是，对于 S3 分段上传，在摄取对象时会针对对象的每一部分对 ILM 进行评估，并且在分段上传完成时对整个对象进行评估。在以下情况下，这可能会导致展示位置与您预期的不同：
+
** *如果在 S3 分段上传过程中 ILM 发生变化*：由于每个部分都是根据摄取该部分时有效的规则放置的，因此在分段上传完成时，对象的某些部分可能不符合当前的 ILM 要求。在这些情况下，对象的摄取不会失败。相反，任何未正确放置的部件都会排队等待 ILM 重新评估，然后移动到正确的位置。
** *当 ILM 规则按大小过滤时*：当评估某个部分的 ILM 时， StorageGRID会按部分的大小进行过滤，而不是对象的大小。这意味着对象的各个部分可以存储在不满足对象整体的 ILM 要求的位置。例如，如果规则指定所有 10 GB 或更大的对象都存储在 DC1，而所有较小的对象都存储在 DC2，则在摄取 10 部分分段上传的每个 1 GB 部分时都存储在 DC2。当对对象进行 ILM 评估时，对象的所有部分都会移动到 DC1。


* *（严格）当对象标签或元数据更新且无法进行新要求的放置时，摄取不会失败*：使用严格，您希望对象按照 ILM 规则的描述放置，否则摄取会失败。但是，当您更新已存储在网格中的对象的元数据或标签时，该对象不会被重新摄取。这意味着更新触发的对象位置的任何更改都不会立即生效。当 ILM 由正常后台 ILM 进程重新评估时，会进行放置更改。如果无法进行所需的位置更改（例如，因为新需要的位置不可用），则更新后的对象将保留其当前位置，直到可以进行位置更改为止。




== 使用“平衡”和“严格”选项放置对象的限制

平衡或严格选项不能用于具有以下任何放置指令的 ILM 规则：

* 在第 0 天放置在云存储池中。
* 当规则以用户定义的创建时间作为参考时间时，云存储池中的位置。


存在这些限制是因为StorageGRID无法同步复制至云存储池，并且用户定义的创建时间可以解析为现在。



== ILM 规则和一致性如何相互作用以影响数据保护

您的 ILM 规则和一致性选择都会影响对象的保护方式。这些设置可以相互作用。

例如，为 ILM 规则选择的摄取行为会影响对象副本的初始位置，而存储对象时使用的一致性会影响对象元数据的初始位置。由于StorageGRID需要访问对象的数据和元数据来满足客户端请求，因此为一致性和摄取行为选择匹配的保护级别可以提供更好的初始数据保护和更可预测的系统响应。

以下是StorageGRID中可用的一致性值的简要摘要：

* *全部*：所有节点立即接收对象元数据，否则请求将失败。
* *Strong-global*：对象元数据立即分发到所有站点。保证所有站点上所有客户端请求的读写一致性。
* *强站点*：对象元数据立即分发到站点的其他节点。保证站点内所有客户端请求的读写一致性。
* *Read-after-new-write*：为新对象提供read-after-write一致性，并为对象更新提供最终一致性。提供高可用性和数据保护保证。在大多数情况下推荐使用。
* *可用*：为新对象和对象更新提供最终一致性。对于 S3 存储桶，仅在需要时使用（例如，对于包含很少读取的日志值的存储桶，或者对于不存在的键的 HEAD 或 GET 操作）。不支持 S3 FabricPool存储桶。



NOTE: 在选择一致性值之前，link:../s3/consistency-controls.html["阅读一致性的完整描述"] 。在更改默认值之前，您应该了解其优点和局限性。



== 一致性和 ILM 规则如何交互的示例

假设您有一个双站点网格，具有以下 ILM 规则和以下一致性：

* *ILM 规则*：创建两个对象副本，一个在本地站点，一个在远程站点。使用严格的摄取行为。
* *一致性*：强全局（对象元数据立即分发到所有站点）。


当客户端将对象存储到网格时， StorageGRID会复制两个对象并将元数据分发到两个站点，然后再将成功返回给客户端。

在接收成功消息时，对象将受到完全保护，不会丢失。例如，如果本地站点在摄取后不久丢失，对象数据和对象元数据的副本仍然存在于远程站点。该对象完全可检索。

如果您使用相同的 ILM 规则和强站点一致性，则客户端可能会在对象数据复制到远程站点之后但在对象元数据分发到那里之前收到成功消息。在这种情况下，对象元数据的保护级别与对象数据的保护级别不匹配。如果本地站点在摄取后不久丢失，对象元数据就会丢失。无法检索该对象。

一致性和 ILM 规则之间的相互关系可能很复杂。如果您需要帮助，请联系NetApp 。

.相关信息
link:example-5-ilm-rules-and-policy-for-strict-ingest-behavior.html["示例 5：针对严格摄取行为的 ILM 规则和策略"]
