---
permalink: ilm/editing-storage-pool.html 
sidebar: sidebar 
keywords: edit storage pool 
summary: 您可以编辑存储池以更改其名称或更新站点和存储等级。 
---
= 编辑存储池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以编辑存储池以更改其名称或更新站点和存储等级。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:../admin/admin-group-permissions.html["特定访问权限"]。
* 您已审阅link:guidelines-for-creating-storage-pools.html["创建存储池的指南"]。
* 如果您计划编辑活动 ILM 策略中的规则所使用的存储池，则您已经考虑过您的更改将如何影响对象数据的放置。


.关于此任务
如果要向活动 ILM 策略中使用的存储池添加新站点或存储等级，请注意新站点或存储等级中的存储节点将不会自动使用。要强制StorageGRID使用新站点或存储等级，您必须在保存编辑的存储池后激活新的 ILM 策略。

.步骤
. 选择 *ILM* > *存储池*。
. 选中要编辑的存储池的复选框。
+
您无法编辑所有存储节点存储池（StorageGRID 11.6 及更早版本）。

. 选择*编辑*。
. 根据需要更改存储池名称。
. 根据需要选择其他站点和存储等级。
+
如果存储池在擦除编码配置文件中使用，则您将无法更改站点或存储等级，并且更改会导致擦除编码方案无效。例如，如果擦除编码配置文件中使用的存储池当前仅包含一个站点的存储等级，则您将无法使用两个站点的存储等级，因为更改会使擦除编码方案无效。

+

CAUTION: 在现有存储池中添加或删除站点不会移动任何现有的擦除编码数据。如果要从站点移动现有数据，则必须创建一个新的存储池和 EC 配置文件来重新编码数据。

. 选择*保存*。


.完成后
如果您向活动 ILM 策略中使用的存储池添加了新的站点或存储等级，请激活新的 ILM 策略以强制StorageGRID使用新的站点或存储等级。例如，克隆现有的 ILM 策略，然后激活该克隆。看link:working-with-ilm-rules-and-ilm-policies.html["使用 ILM 规则和 ILM 策略"] 。
