---
permalink: ilm/example-7-compliant-ilm-policy-for-s3-object-lock.html 
sidebar: sidebar 
keywords: ILM policy,S3 Object Lock 
summary: 您可以使用本示例中的 S3 存储桶、ILM 规则和 ILM 策略作为起点来定义 ILM 策略，以满足启用了 S3 对象锁的存储桶中对象的对象保护和保留要求。 
---
= 示例 7：符合 S3 对象锁定的 ILM 策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用本示例中的 S3 存储桶、ILM 规则和 ILM 策略作为起点来定义 ILM 策略，以满足启用了 S3 对象锁的存储桶中对象的对象保护和保留要求。


NOTE: 如果您在以前的StorageGRID版本中使用了旧版合规性功能，则您还可以使用此示例来帮助管理启用了旧版合规性功能的任何现有存储桶。


CAUTION: 以下 ILM 规则和策略仅作为示例。配置 ILM 规则的方法有很多种。在激活新策略之前，请先进行模拟以确认它能够按预期工作以保护内容免遭丢失。

.相关信息
* link:managing-objects-with-s3-object-lock.html["使用 S3 对象锁管理对象"]
* link:creating-ilm-policy.html["创建 ILM 策略"]




== S3 对象锁定示例的存储桶和对象

在此示例中，名为 ABC 银行的 S3 租户帐户使用租户管理器创建了一个启用了 S3 对象锁的存储桶，用于存储重要的银行记录。

[cols="2a,2a"]
|===
| 桶定义 | 示例值 


 a| 
租户帐户名称
 a| 
农业银行



 a| 
存储桶名称
 a| 
银行记录



 a| 
桶区域
 a| 
us-east-1（默认）

|===
添加到银行记录存储桶的每个对象和对象版本将使用以下值 `retain-until-date`和 `legal hold`设置。

[cols="1a,2a"]
|===
| 为每个对象设置 | 示例值 


 a| 
`retain-until-date`
 a| 
“2030-12-30T23:59:59Z”（2030 年 12 月 30 日）

每个对象版本都有自己的 `retain-until-date`环境。此设置可以增加，但不能减少。



 a| 
`legal hold`
 a| 
“OFF”（无效）

在保留期内，可以随时对任何对象版本实施或解除合法保留。如果对象处于合法保留状态，则即使 `retain-until-date`已达到。

|===


== S3 对象锁定的 ILM 规则 1 示例：具有存储桶匹配的擦除编码配置文件

此示例 ILM 规则仅适用于名为 Bank of ABC 的 S3 租户帐户。它匹配 `bank-records`存储桶，然后使用擦除编码将对象存储在三个数据中心站点的存储节点上，采用 6+3 擦除编码配置文件。此规则满足启用 S3 对象锁的存储桶的要求：从第 0 天到永远，在存储节点上保留一份副本，使用摄取时间作为参考时间。

[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
规则名称
 a| 
符合规则：银行记录存储桶中的 EC 对象 - ABC 银行



 a| 
租户账户
 a| 
农业银行



 a| 
存储桶名称
 a| 
`bank-records`



 a| 
高级过滤器
 a| 
对象大小 (MB) 大于 1

*注意：*此过滤器确保 1 MB 或更小的对象不使用擦除编码。

|===
[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
参考时间
 a| 
摄取时间



 a| 
展示位置
 a| 
从第 0 天开始永久存储



 a| 
擦除编码配置文件
 a| 
* 在三个数据中心站点的存储节点上创建擦除编码副本
* 采用 6+3 擦除编码方案


|===


== S3 对象锁定的 ILM 规则 2 示例：不合规规则

此示例 ILM 规则最初在存储节点上存储两个复制的对象副本。一年后，它会将一份副本永久存储在云存储池中。由于此规则使用云存储池，因此它不合规并且不适用于启用了 S3 对象锁的存储桶中的对象。

[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
规则名称
 a| 
不合规规则：使用云存储池



 a| 
租户帐户
 a| 
未指定



 a| 
存储桶名称
 a| 
未指定，但仅适用于未启用 S3 对象锁定（或旧版合规性功能）的存储桶。



 a| 
高级过滤器
 a| 
未指定

|===
[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
参考时间
 a| 
摄取时间



 a| 
展示位置
 a| 
* 在第 0 天，在数据中心 1 和数据中心 2 的存储节点上保留两个副本，为期 365 天
* 一年后，永久保留一份副本在云存储池中


|===


== S3 对象锁定的 ILM 规则 3 示例：默认规则

此示例 ILM 规则将对象数据复制到两个数据中心的存储池。此合规规则被设计为 ILM 策略中的默认规则。它不包含任何过滤器，不使用非当前参考时间，并满足启用 S3 对象锁的存储桶的要求：从第 0 天到永远，两个对象副本都保留在存储节点上，使用 Ingest 作为参考时间。

[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
规则名称
 a| 
默认合规规则：两个副本两个数据中心



 a| 
租户帐户
 a| 
未指定



 a| 
存储桶名称
 a| 
未指定



 a| 
高级过滤器
 a| 
未指定

|===
[cols="1a,2a"]
|===
| 规则定义 | 示例值 


 a| 
参考时间
 a| 
摄取时间



 a| 
展示位置
 a| 
从第 0 天到永远，保留两个副本 - 一个在数据中心 1 的存储节点上，另一个在数据中心 2 的存储节点上。

|===


== 符合 S3 对象锁定的 ILM 策略示例

要创建能够有效保护系统中的所有对象（包括启用了 S3 对象锁的存储桶中的对象）的 ILM 策略，您必须选择满足所有对象的存储要求的 ILM 规则。然后，您必须模拟并激活该策略。



=== 向策略添加规则

在此示例中，ILM 策略包含三个 ILM 规则，顺序如下：

. 一项合规规则，使用擦除编码来保护启用了 S3 对象锁定的特定存储桶中大于 1 MB 的对象。对象从第 0 天起一直存储在存储节点上。
. 不合规的规则是在存储节点上创建两个复制的对象副本，为期一年，然后将一个对象副本永久移动到云存储池。此规则不适用于启用了 S3 对象锁定的存储桶，因为它使用云存储池。
. 默认合规规则是从第 0 天到永远在存储节点上创建两个复制对象副本。




=== 模拟策略

在向策略添加规则、选择默认兼容规则并安排其他规则后，您应该通过测试启用了 S3 对象锁定的存储桶和其他存储桶中的对象来模拟该策略。例如，当您模拟示例策略时，您会期望测试对象按如下方式进行评估：

* 第一条规则将仅匹配 ABC 银行租户的存储桶银行记录中大于 1 MB 的测试对象。
* 第二条规则将匹配所有其他租户帐户的所有不合规存储桶中的所有对象。
* 默认规则将匹配这些对象：
+
** ABC 银行租户的存储桶银行记录中 1 MB 或更小的对象。
** 为所有其他租户账户启用了 S3 对象锁的任何其他存储桶中的对象。






=== 激活策略

当您完全满意新策略按预期保护对象数据时，您可以激活它。
