---
permalink: ilm/guidelines-for-creating-storage-pools.html 
sidebar: sidebar 
keywords: storage pool guidelines 
summary: 配置和使用存储池，通过在多个站点之间分发数据来防止数据丢失。复制副本和擦除编码副本需要不同的存储池配置。 
---
= 创建存储池的指南
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置和使用存储池，通过在多个站点之间分发数据来防止数据丢失。复制副本和擦除编码副本需要不同的存储池配置。

看link:using-multiple-storage-pools-for-cross-site-replication.html["使用复制和擦除编码实现站点丢失保护的示例"] 。



== 所有存储池的指南

* 使存储池配置尽可能简单。不要创建超过需要的存储池。
* 创建具有尽可能多的节点的存储池。每个存储池应包含两个或更多节点。如果某个节点不可用，则节点不足的存储池可能会导致 ILM 积压。
* 避免创建或使用重叠的存储池（包含一个或多个相同的节点）。如果存储池重叠，则可能会在同一个节点上保存多个对象数据的副本。
* 一般来说，不要使用所有存储节点存储池（StorageGRID 11.6 及更早版本）或所有站点站点。这些项目会自动更新以包含您在扩展中添加的任何新站点，这可能不是您想要的行为。




== 用于复制副本的存储池指南

* 对于站点丢失保护，使用link:what-replication-is.html["replication"]，在link:create-ilm-rule-define-placements.html["每个 ILM 规则的放置说明"]。
+
在StorageGRID安装期间，会自动为每个站点创建一个存储池。

+
为每个站点使用一个存储池可确保复制的对象副本准确地放置在您期望的位置（例如，每个站点的每个对象都有一个副本，以防止站点丢失）。

* 如果在扩展中添加站点，请创建仅包含新站点的新存储池。然后，link:working-with-ilm-rules-and-ilm-policies.html#edit-an-ilm-rule["更新 ILM 规则"]控制哪些对象存储在新站点上。
* 如果副本数小于存储池数，系统将分配副本以平衡池之间的磁盘使用情况。
* 如果存储池重叠（包含相同的存储节点），则对象的所有副本可能仅保存在一个站点上。您必须确保所选的存储池不包含相同的存储节点。




== 用于擦除编码副本的存储池指南

* 对于站点丢失保护，使用link:what-erasure-coding-is.html["擦除编码"]，创建至少由三个站点组成的存储池。如果存储池仅包含两个站点，则不能使用该存储池进行擦除编码。对于具有两个站点的存储池，没有可用的擦除编码方案。
* 存储池中包含的存储节点和站点的数量决定了link:what-erasure-coding-schemes-are.html["擦除编码方案"]可用。
* 如果可能，存储池应包含超过您选择的擦除编码方案所需的最小存储节点数量。例如，如果您使用 6+3 擦除编码方案，则必须至少有九个存储节点。但是，建议每个站点至少有一个额外的存储节点。
* 尽可能均匀地在各个站点间分布存储节点。例如，为了支持 6+3 擦除编码方案，请配置一个包含三个站点的至少三个存储节点的存储池。
* 如果您有高吞吐量要求，并且站点之间的网络延迟大于 100 毫秒，则不建议使用包含多个站点的存储池。随着延迟的增加，由于 TCP 网络吞吐量的下降， StorageGRID创建、放置和检索对象片段的速率急剧下降。
+
吞吐量的下降会影响对象摄取和检索的最大可实现速率（当选择“平衡”或“严格”作为摄取行为时）或可能导致 ILM 队列积压（当选择“双重提交”作为摄取行为时）。看link:what-ilm-rule-is.html#ilm-rule-ingest-behavior["ILM 规则摄取行为"] 。

+

NOTE: 如果您的网格仅包含一个站点，则您将无法使用所有存储节点存储池（StorageGRID 11.6 及更早版本）或擦除编码配置文件中的所有站点站点。此行为可防止添加第二个站点时配置文件变得无效。


