---
permalink: ilm/lifecycle-of-cloud-storage-pool-object.html 
sidebar: sidebar 
keywords: lifecycle of cloud storage pool object 
summary: 在实施云存储池之前，请检查存储在每种类型的云存储池中的对象的生命周期。 
---
= 云存储池对象的生命周期
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在实施云存储池之前，请检查存储在每种类型的云存储池中的对象的生命周期。



== S3：云存储池对象的生命周期

这些步骤描述了存储在 S3 云存储池中的对象的生命周期阶段。


NOTE: “Glacier”指 Glacier 存储类和 Glacier Deep Archive 存储类，但有一个例外：Glacier Deep Archive 存储类不支持快速恢复层。仅支持批量或标准检索。


NOTE: Google Cloud Platform (GCP) 支持从长期存储中检索对象，而无需 POST 恢复操作。

. *存储在StorageGRID中的对象*
+
为了启动生命周期，客户端应用程序将对象存储在StorageGRID中。

. *对象已移至 S3 云存储池*
+
** 当对象与使用 S3 云存储池作为其放置位置的 ILM 规则匹配时， StorageGRID会将对象移动到云存储池指定的外部 S3 存储桶。
** 当对象被移动到 S3 云存储池时，客户端应用程序可以使用来自StorageGRID的 S3 GetObject 请求检索它，除非该对象已转换到 Glacier 存储。


. *对象已转换为 Glacier（不可检索状态）*
+
** 或者，可以将对象转换到 Glacier 存储。例如，外部 S3 存储桶可能使用生命周期配置立即或在几天后将对象转换到 Glacier 存储。
+

NOTE: 如果您想要转换对象，则必须为外部 S3 存储桶创建生命周期配置，并且必须使用实现 Glacier 存储类并支持 S3 RestoreObject API 的存储解决方案。

** 在转换期间，客户端应用程序可以使用 S3 HeadObject 请求来监控对象的状态。


. *从 Glacier 存储中恢复的对象*
+
如果对象已转换到 Glacier 存储，客户端应用程序可以发出 S3 RestoreObject 请求，将可检索的副本恢复到 S3 云存储池。该请求指定副本在云存储池中可用多少天以及用于恢复操作的数据访问层（加急、标准或批量）。当可检索副本的有效期到达时，副本将自动恢复为不可检索状态。

+

NOTE: 如果StorageGRID内的存储节点上也存在该对象的一个​​或多个副本，则无需通过发出 RestoreObject 请求从 Glacier 恢复该对象。相反，可以使用 GetObject 请求直接检索本地副本。

. *已检索对象*
+
一旦对象被恢复，客户端应用程序就可以发出 GetObject 请求来检索恢复的对象。





== Azure：云存储池对象的生命周期

这些步骤描述了存储在 Azure 云存储池中的对象的生命周期阶段。

. *存储在StorageGRID中的对象*
+
为了启动生命周期，客户端应用程序将对象存储在StorageGRID中。

. *对象已移至 Azure 云存储池*
+
当对象与使用 Azure 云存储池作为其放置位置的 ILM 规则匹配时， StorageGRID会将对象移动到云存储池指定的外部 Azure Blob 存储容器。

. *对象已转换至存档层（不可检索状态）*
+
将对象移动到 Azure 云存储池后， StorageGRID会立即自动将该对象转换到 Azure Blob 存储存档层。

. *从存档层恢复的对象*
+
如果对象已转换到存档层，则客户端应用程序可以发出 S3 RestoreObject 请求，将可检索的副本还原到 Azure 云存储池。

+
当StorageGRID收到 RestoreObject 时，它会将该对象暂时转换到 Azure Blob 存储 Cool 层。一旦达到 RestoreObject 请求中的到期日期， StorageGRID就会将对象转换回存档层。

+

NOTE: 如果StorageGRID内的存储节点上也存在该对象的一个​​或多个副本，则无需通过发出 RestoreObject 请求从存档访问层恢复该对象。相反，可以使用 GetObject 请求直接检索本地副本。

. *已检索对象*
+
一旦对象被恢复到 Azure 云存储池，客户端应用程序就可以发出 GetObject 请求来检索恢复的对象。



.相关信息
link:../s3/index.html["使用 S3 REST API"]
