---
permalink: ilm/managing-objects-with-s3-object-lock.html 
sidebar: sidebar 
keywords: s3 object lock, manage objects with object lock 
summary: 作为网格管理员，您可以为StorageGRID系统启用 S3 对象锁并实施兼容的 ILM 策略，以帮助确保特定 S3 存储桶中的对象在指定时间内不会被删除或覆盖。 
---
= 使用 S3 对象锁管理对象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
作为网格管理员，您可以为StorageGRID系统启用 S3 对象锁并实施兼容的 ILM 策略，以帮助确保特定 S3 存储桶中的对象在指定时间内不会被删除或覆盖。



== 什么是 S3 对象锁？

StorageGRID S3 对象锁功能是一种对象保护解决方案，相当于 Amazon Simple Storage Service (Amazon S3) 中的 S3 对象锁。

当为StorageGRID系统启用全局 S3 对象锁定设置时，S3 租户帐户可以创建启用或未启用 S3 对象锁定的存储桶。如果存储桶启用了 S3 对象锁，则需要存储桶版本控制，并且会自动启用。

*没有 S3 对象锁的存储桶*只能包含未指定保留设置的对象。任何摄取的对象都不会有保留设置。

*具有 S3 对象锁的存储桶*可以包含由 S3 客户端应用程序指定的具有或不具有保留设置的对象。一些摄取的对象将具有保留设置。

*配置了 S3 对象锁定和默认保留的存储桶*可以拥有指定了保留设置的上传对象和不带保留设置的新对象。新对象使用默认设置，因为尚未在对象级别配置保留设置。

实际上，当配置默认保留时，所有新摄取的对象都有保留设置。没有对象保留设置的现有对象不受影响。



=== 保留模式

StorageGRID S3 对象锁定功能支持两种保留模式，以对对象应用不同级别的保护。这些模式相当于 Amazon S3 保留模式。

* 在合规模式下：
+
** 在达到保留截止日期之前，无法删除该对象。
** 对象的保留截止日期可以增加，但不能减少。
** 在达到该日期之前，不能删除对象的保留截止日期。


* 在治理模式下：
+
** 具有特殊权限的用户可以在请求中使用绕过标头来修改某些保留设置。
** 这些用户可以在达到保留截止日期之前删除对象版本。
** 这些用户可以增加、减少或删除对象的保留期限。






=== 对象版本的保留设置

如果创建存储桶时启用了 S3 对象锁定，则用户可以使用 S3 客户端应用程序选择性地为添加到存储桶的每个对象指定以下保留设置：

* *保留模式*：合规或治理。
* *保留至日期*：如果对象版本的保留至日期在未来，则可以检索该对象，但不能删除它。
* *合法保留*：对对象版本应用合法保留会立即锁定该对象。例如，您可能需要对与调查或法律纠纷相关的对象实施法律保留。合法保留没有到期日，但会一直有效，直到被明确取消。合法保留与保留截止日期无关。
+

NOTE: 如果某个对象处于合法保留之下，则无论其保留模式如何，任何人都无法删除该对象。

+
有关对象设置的详细信息，请参阅link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 配置 S3 对象锁"]。





=== 存储桶的默认保留设置

如果创建存储桶时启用了 S3 对象锁定，用户可以选择为存储桶指定以下默认设置：

* *默认保留模式*：合规或治理。
* *默认保留期*：添加到此存储桶的新对象版本应保留多长时间（从添加之日起）。


默认存储桶设置仅适用于没有自己的保留设置的新对象。添加或更改这些默认设置时，现有的存储桶对象不会受到影响。

看link:../tenant/creating-s3-bucket.html["创建 S3 存储桶"]和link:../tenant/update-default-retention-settings.html["更新 S3 对象锁默认保留"]。



== S3 对象锁定与旧版合规性的比较

S3 对象锁取代了早期StorageGRID版本中提供的合规性功能。由于 S3 对象锁定功能符合 Amazon S3 要求，因此它弃用了专有的StorageGRID合规性功能，后者现在被称为“旧版合规性”。


NOTE: 全局合规性设置已被弃用。如果您使用以前版本的StorageGRID启用此设置，则 S3 对象锁定设置将自动启用。您可以继续使用StorageGRID来管理现有兼容存储桶的设置；但是，您无法创建新的兼容存储桶。有关详细信息，请参阅 https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/StorageGRID/How_to_manage_legacy_Compliant_buckets_in_StorageGRID_11.5["NetApp知识库：如何在StorageGRID 11.5 中管理旧版兼容存储桶"^]。

如果您在以前版本的StorageGRID中使用了旧版合规性功能，请参阅下表了解它与StorageGRID中的 S3 对象锁定功能的比较。

[cols="1a,1a,1a"]
|===
|  | S3 对象锁 | 合规性（遗留） 


 a| 
如何在全球范围内启用该功能？
 a| 
从网格管理器中，选择 *配置* > *系统* > *S3 对象锁*。
 a| 
不再支持。



 a| 
如何为存储桶启用该功能？
 a| 
用户在使用租户管理器、租户管理 API 或 S3 REST API 创建新存储桶时必须启用 S3 对象锁定。
 a| 
不再支持。



 a| 
是否支持存储桶版本控制？
 a| 
是存储桶版本控制是必需的，并且在为存储桶启用 S3 对象锁定时会自动启用。
 a| 
目标卷



 a| 
对象保留如何设置？
 a| 
用户可以为每个对象版本设置保留截止日期，也可以为每个存储桶设置默认保留期。
 a| 
用户必须为整个存储桶设置保留期。保留期适用于存储桶中的所有对象。



 a| 
保留期限可以更改吗？
 a| 
* 在合规模式下，对象版本的保留截止日期可以增加但不能减少。
* 在治理模式下，具有特殊权限的用户可以减少甚至删除对象的保留设置。

 a| 
存储桶的保留期可以增加，但不能减少。



 a| 
合法保留在哪里控制？
 a| 
用户可以对存储桶中的任何对象版本设置合法保留或解除合法保留。
 a| 
对存储桶实施合法保留，并影响存储桶中的所有对象。



 a| 
什么时候可以删除对象？
 a| 
* 在合规模式下，假设对象未处于合法保留状态，则可以在达到保留期限后删除对象版本。
* 在治理模式下，具有特殊权限的用户可以在达到保留期限之前删除对象，假设该对象不受合法保留。

 a| 
假设存储桶未处于合法保留状态，则可以在保留期到期后删除对象。对象可以自动或手动删除。



 a| 
是否支持 bucket 生命周期配置？
 a| 
是
 a| 
否

|===