---
permalink: ilm/removing-cloud-storage-pool.html 
sidebar: sidebar 
keywords: remove cloud storage pool 
summary: 如果云存储池未在 ILM 规则中使用并且不包含对象数据，则可以将其删除。 
---
= 删除云存储池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果云存储池未在 ILM 规则中使用并且不包含对象数据，则可以将其删除。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:../admin/admin-group-permissions.html["所需的访问权限"]。




== 如果需要，使用 ILM 移动对象数据

如果要删除的云存储池包含对象数据，则必须使用 ILM 将数据移动到其他位置。例如，您可以将数据移动到网格上的存储节点或其他云存储池。

.步骤
. 选择 *ILM* > *存储池* > *云存储池*。
. 查看表中的 ILM 使用情况列以确定是否可以删除云存储池。
+
如果云存储池正在 ILM 规则或擦除编码配置文件中使用，则无法将其移除。

. 如果正在使用云存储池，请选择*_云存储池名称_* > *ILM 使用情况*。
. link:working-with-ilm-rules-and-ilm-policies.html["克隆每个 ILM 规则"]当前将对象放置在您想要移除的云存储池中。
. 确定要将由您克隆的每个规则管理的现有对象移动到哪里。
+
您可以使用一个或多个存储池或不同的云存储池。

. 编辑您克隆的每个规则。
+
对于创建 ILM 规则向导的第 2 步，从 *副本位置* 字段中选择新位置。

. link:creating-ilm-policy.html["创建新的 ILM 策略"]并用克隆的规则替换每个旧规则。
. 激活新策略。
. 等待 ILM 从云存储池中删除对象并将其放置在新位置。




== 删除云存储池

当云存储池为空且未在任何 ILM 规则中使用时，您可以将其删除。

.开始之前
* 您已删除任何可能使用该池的 ILM 规则。
* 您已确认 S3 存储桶或 Azure 容器不包含任何对象。
+
如果尝试删除包含对象的云存储池，则会发生错误。看link:troubleshooting-cloud-storage-pools.html["排除云存储池故障"] 。

+

NOTE: 当您创建云存储池时， StorageGRID会将标记文件写入存储桶或容器以将其标识为云存储池。不要删除这个名为 `x-ntap-sgws-cloud-pool-uuid`。



.步骤
. 选择 *ILM* > *存储池* > *云存储池*。
. 如果 ILM 使用情况列表明未使用云存储池，请选中该复选框。
. 选择*操作* > *删除*。
. 选择“确定”。

