---
permalink: ilm/requirements-for-s3-object-lock.html 
sidebar: sidebar 
keywords: requirements, s3 object lock, compliant ilm rule, compliant ilm policy 
summary: 您必须查看启用全局 S3 对象锁定设置的要求、创建合规 ILM 规则和 ILM 策略的要求以及StorageGRID对使用 S3 对象锁定的存储桶和对象施加的限制。 
---
= S3 对象锁定的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须查看启用全局 S3 对象锁定设置的要求、创建合规 ILM 规则和 ILM 策略的要求以及StorageGRID对使用 S3 对象锁定的存储桶和对象施加的限制。



== 使用全局 S3 对象锁定设置的要求

* 您必须先使用网格管理器或网格管理 API 启用全局 S3 对象锁定设置，然后任何 S3 租户才能创建启用了 S3 对象锁定的存储桶。
* 启用全局 S3 对象锁定设置允许所有 S3 租户帐户创建启用了 S3 对象锁定的存储桶。
* 启用全局 S3 对象锁定设置后，您无法禁用该设置。
* 除非所有活动 ILM 策略中的默认规则都符合要求（即，默认规则必须符合启用了 S3 对象锁定的存储桶的要求），否则您无法启用全局 S3 对象锁定。
* 启用全局 S3 对象锁定设置后，您无法创建新的 ILM 策略或激活现有的 ILM 策略，除非该策略中的默认规则符合要求。启用全局 S3 对象锁定设置后，ILM 规则和 ILM 策略页面会指示哪些 ILM 规则是合规的。




== 符合 ILM 规则的要求

如果要启用全局 S3 对象锁定设置，则必须确保所有活动 ILM 策略中的默认规则都符合要求。合规规则满足启用了 S3 对象锁定的存储桶以及启用了旧版合规性的任何现有存储桶的要求：

* 它必须创建至少两个复制的对象副本或一个擦除编码副本。
* 这些副本必须在放置指令的每一行的整个持续时间内存在于存储节点上。
* 对象副本无法保存在云存储池中。
* 放置说明中至少有一行必须从第 0 天开始，使用 *摄取时间* 作为参考时间。
* 放置说明中至少有一行必须是“永远”。




== ILM 策略的要求

启用全局 S3 对象锁定设置后，活动和非活动的 ILM 策略可以同时包含合规和不合规规则。

* 活动或非活动 ILM 策略中的默认规则必须合规。
* 不合规规则仅适用于未启用 S3 对象锁定或未启用旧版合规性功能的存储桶中的对象。
* 合规规则可应用于任何存储桶中的对象；存储桶无需启用 S3 对象锁定或旧版合规性。


link:example-7-compliant-ilm-policy-for-s3-object-lock.html["S3 对象锁定的合规 ILM 策略示例"]



== 启用 S3 对象锁定的存储桶的要求

* 如果为StorageGRID系统启用了全局 S3 对象锁定设置，则您可以使用租户管理器、租户管理 API 或 S3 REST API 创建启用了 S3 对象锁定的存储桶。
* 如果您计划使用 S3 对象锁，则必须在创建存储桶时启用 S3 对象锁。您无法为现有存储桶启用 S3 对象锁定。
* 当为存储桶启用 S3 对象锁定时， StorageGRID会自动为该存储桶启用版本控制。您无法禁用 S3 对象锁定或暂停存储桶的版本控制。
* 或者，您可以使用租户管理器、租户管理 API 或 S3 REST API 为每个存储桶指定默认保留模式和保留期限。存储桶的默认保留设置仅适用于添加到存储桶且没有自己的保留设置的新对象。您可以通过在上传每个对象版本时为其指定保留模式和保留截止日期来覆盖这些默认设置。
* 启用 S3 对象锁的存储桶支持存储桶生命周期配置。
* 启用了 S3 对象锁的存储桶不支持 CloudMirror 复制。




== 启用 S3 对象锁的存储桶中的对象要求

* 为了保护对象版本，您可以为存储桶指定默认保留设置，也可以为每个对象版本指定保留设置。可以使用 S3 客户端应用程序或 S3 REST API 指定对象级保留设置。
* 保留设置适用于单个对象版本。对象版本可以同时具有保留截止日期和合法保留设置，或者只具有其中之一，或者两者都不具有。为对象指定保留期限或合法保留设置仅保护请求中指定的版本。您可以创建该对象的新版本，同时该对象的先前版本仍保持锁定状态。




== 启用 S3 对象锁的存储桶中对象的生命周期

启用 S3 对象锁后，保存在存储桶中的每个对象都会经历以下阶段：

. *对象摄取*
+
当对象版本添加到启用了 S3 对象锁定的存储桶时，将应用以下保留设置：

+
** 如果为对象指定了保留设置，则应用对象级别的设置。任何默认存储桶设置都将被忽略。
** 如果没有为对象指定保留设置，则应用默认存储桶设置（如果存在）。
** 如果没有为对象或存储桶指定保留设置，则该对象不受 S3 对象锁保护。


+
如果应用了保留设置，则对象和任何 S3 用户定义的元数据都受到保护。

. *对象保留和删除*
+
StorageGRID会存储每个受保护对象的多个副本，并保留指定的期限。对象副本的确切数量和类型以及存储位置由活动 ILM 策略中的兼容规则决定。受保护对象是否可以在达到保留期限之前被删除取决于其保留模式。

+
** 如果某个对象处于合法保留之下，则无论其保留模式如何，任何人都无法删除该对象。




.相关信息
* link:../tenant/creating-s3-bucket.html["创建 S3 存储桶"]
* link:../tenant/update-default-retention-settings.html["更新 S3 对象锁默认保留"]
* link:../s3/use-s3-api-for-s3-object-lock.html["使用 S3 REST API 配置 S3 对象锁"]
* link:example-7-compliant-ilm-policy-for-s3-object-lock.html["示例 7：符合 S3 对象锁定的 ILM 策略"]

