---
permalink: ilm/troubleshooting-cloud-storage-pools.html 
sidebar: sidebar 
keywords: cloud storage pool, troubleshoot 
summary: 使用这些故障排除步骤来帮助解决您在创建、编辑或删除云存储池时可能遇到的错误。 
---
= 排除云存储池故障
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用这些故障排除步骤来帮助解决您在创建、编辑或删除云存储池时可能遇到的错误。



== 确定是否发生错误

StorageGRID通过读取已知对象对每个云存储池执行简单的健康检查 `x-ntap-sgws-cloud-pool-uuid`确保云存储池可以访问并正常运行。当StorageGRID在端点上遇到错误时，它会每分钟从每个存储节点执行一次健康检查。当错误解决后，健康检查停止。如果健康检查检测到问题，则会在存储池页面上的云存储池表的最后一个错误列中显示一条消息。

该表显示了每个云存储池检测到的最近错误，并指示错误发生的时间。

此外，如果运行状况检查检测到过去 5 分钟内发生了一个或多个新的云存储池错误，则会触发*云存储池连接错误*警报。如果您收到此警报的电子邮件通知，请转到存储池页面（选择 *ILM* > *存储池*），查看上一个错误列中的错误消息，并参考下面的故障排除指南。



== 检查错误是否已解决

解决所有潜在问题后，您可以确定错误是否已解决。从云存储池页面，选择端点，然后选择*清除错误*。确认消息表明StorageGRID已清除云存储池的错误。

如果根本问题已解决，则不再显示错误消息。但是，如果根本问题尚未解决（或者遇到其他错误），则错误消息将在几分钟内显示在“上次错误”列中。



== 错误：健康检查失败。端点错误

当您开始将此存储桶用作云存储池后，为 Amazon S3 存储桶启用具有默认保留的 S3 对象锁定时，可能会遇到此错误。当 PUT 操作没有包含有效负载校验和值的 HTTP 标头时，就会发生此错误，例如 `Content-MD5`。对于启用了 S3 对象锁的存储桶中的 PUT 操作，AWS 需要此标头值。

要解决此问题，请按照link:editing-cloud-storage-pool.html["编辑云存储池"]无需做任何改变。此操作会触发云存储池配置的验证，该验证会自动检测并更新云存储池端点配置上的 S3 对象锁定标志。



== 错误：此云存储池包含意外内容

当您尝试创建、编辑或删除云存储池时，可能会遇到此错误。如果存储桶或容器包含 `x-ntap-sgws-cloud-pool-uuid`标记文件，但该文件没有具有预期 UUID 的元数据字段。

通常，只有在创建新的云存储池并且StorageGRID的另一个实例已经在使用相同的云存储池时，才会看到此错误。

请尝试以下步骤之一来纠正该问题：

* 如果您正在配置新的云存储池，并且存储桶包含 `x-ntap-sgws-cloud-pool-uuid`文件和附加对象键类似于以下示例，创建一个新的存储桶并使用这个新的存储桶。
+
附加对象键的示例： `my-bucket.3E64CF2C-B74D-4B7D-AFE7-AD28BC18B2F6.1727326606730410`

* 如果 `x-ntap-sgws-cloud-pool-uuid`文件是存储桶中的唯一对象，请删除该文件。


如果这些步骤不适用于您的情况，请联系支持人员。



== 错误：无法创建或更新云存储池。端点错误

您可能会在以下情况下遇到此错误：

* 当您尝试创建或编辑云存储池时。
* 当您在配置新的云存储池期间选择不受支持的平台、身份验证或与 S3 对象锁定的协议组合时。看link:../ilm/considerations-for-cloud-storage-pools.html["云存储池的注意事项"] 。


此错误表明连接或配置问题阻止StorageGRID写入云存储池。

要纠正该问题，请查看来自端点的错误消息。

* 如果错误消息包含 `Get _url_: EOF`，检查用于云存储池的服务端点是否对需要 HTTPS 的容器或存储桶使用 HTTP。
* 如果错误消息包含 `Get _url_: net/http: request canceled while waiting for connection`，验证网络配置是否允许存储节点访问用于云存储池的服务端点。
* 如果错误是由于不受支持的平台、身份验证或协议造成的，请使用 S3 对象锁更改为受支持的配置，然后尝试再次保存新的云存储池。
* 对于所有其他端点错误消息，请尝试以下一项或多项操作：
+
** 创建一个与您为云存储池输入的名称相同的外部容器或存储桶，然后尝试再次保存新的云存储池。
** 更正您为云存储池指定的容器或存储桶名称，然后尝试再次保存新的云存储池。






== 错误：无法解析 CA 证书

当您尝试创建或编辑云存储池时，可能会遇到此错误。如果StorageGRID无法解析您在配置云存储池时输入的证书，则会发生错误。

要纠正此问题，请检查您提供的 CA 证书是否存在问题。



== 错误：未找到具有此 ID 的云存储池

当您尝试编辑或删除云存储池时，可能会遇到此错误。如果端点返回 404 响应，则会发生此错误，这可能意味着以下任一情况：

* 用于云存储池的凭据没有该存储桶的读取权限。
* 用于云存储池的存储桶不包括 `x-ntap-sgws-cloud-pool-uuid`标记文件。


请尝试以下一个或多个步骤来纠正该问题：

* 检查与配置的访问密钥关联的用户是否具有必要的权限。
* 使用具有必要权限的凭据编辑云存储池。
* 如果权限正确，请联系支持人员。




== 错误：无法检查云存储池的内容。端点错误

当您尝试删除云存储池时，可能会遇到此错误。此错误表明某种连接或配置问题阻止StorageGRID读取云存储池存储桶的内容。

要纠正该问题，请查看来自端点的错误消息。



== 错误：对象已放入此存储桶

当您尝试删除云存储池时，可能会遇到此错误。如果云存储池包含由 ILM 移动到该池的数据、在您配置云存储池之前存储桶中的数据或在创建云存储池之后由其他来源放入存储桶中的数据，则您无法删除该云存储池。

请尝试以下一个或多个步骤来纠正该问题：

* 按照“云存储池对象的生命周期”中的说明将对象移回StorageGRID 。
* 如果您确定剩余对象未由 ILM 放置在云存储池中，请手动从存储桶中删除这些对象。
+

NOTE: 切勿手动删除 ILM 可能放置于云存储池中的对象。如果您稍后尝试从StorageGRID访问手动删除的对象，则将找不到已删除的对象。





== 错误：代理在尝试访问云存储池时遇到外部错误

如果您在存储节点和用于云存储池的外部 S3 端点之间配置了非透明存储代理，则可能会遇到此错误。如果外部代理服务器无法访问云存储池端点，就会发生此错误。例如，DNS 服务器可能无法解析主机名，或者可能存在外部网络问题。

请尝试以下一个或多个步骤来纠正该问题：

* 检查云存储池的设置（*ILM* > *存储池*）。
* 检查存储代理服务器的网络配置。




== 错误：X.509 证书超出有效期

当您尝试删除云存储池时，可能会遇到此错误。当身份验证需要 X.509 证书以确保验证正确的外部云存储池，并且在删除云存储池配置之前外部池为空时，会发生此错误。

请尝试以下步骤来纠正该问题：

* 更新为云存储池身份验证配置的证书。
* 确保此云存储池上的任何证书过期警报都已解决。


.相关信息
link:lifecycle-of-cloud-storage-pool-object.html["云存储池对象的生命周期"]
