---
permalink: ilm/using-last-access-time-in-ilm-rules.html 
sidebar: sidebar 
keywords: last access time, ilm rule reference time 
summary: 您可以使用上次访问时间作为 ILM 规则中的参考时间。例如，您可能希望将过去三个月内查看过的对象保留在本地存储节点上，同时将最近未查看过的对象移动到异地位置。如果您希望 ILM 规则仅适用于在特定日期最后访问的对象，您还可以使用上次访问时间作为高级过滤器。 
---
= 在 ILM 规则中使用上次访问时间
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用上次访问时间作为 ILM 规则中的参考时间。例如，您可能希望将过去三个月内查看过的对象保留在本地存储节点上，同时将最近未查看过的对象移动到异地位置。如果您希望 ILM 规则仅适用于在特定日期最后访问的对象，您还可以使用上次访问时间作为高级过滤器。

.关于此任务
在 ILM 规则中使用上次访问时间之前，请检查以下注意事项：

* 当使用上次访问时间作为参考时间时，请注意更改对象的上次访问时间不会触发立即的 ILM 评估。相反，当背景 ILM 评估对象时，会评估对象的位置并根据需要移动对象。访问对象后，这可能需要两周或更长时间。
+
根据上次访问时间创建 ILM 规则时请考虑此延迟，并避免使用短时间段（少于一个月）的放置。

* 当使用上次访问时间作为高级过滤器或参考时间时，您必须为 S3 存储桶启用上次访问时间更新。您可以使用link:../tenant/enabling-or-disabling-last-access-time-updates.html["租户经理"]或link:../s3/put-bucket-last-access-time-request.html["租户管理 API"]。
+

NOTE: 默认情况下，S3 存储桶的上次访问时间更新处于禁用状态。

+

NOTE: 请注意，启用上次访问时间更新可能会降低性能，尤其是在具有小对象的系统中。性能受到影响的原因是StorageGRID每次检索对象时都必须使用新的时间戳更新对象。



下表总结了针对不同类型的请求，存储桶中所有对象的上次访问时间是否更新。

[cols="1a,1a,1a"]
|===
| 请求类型 | 当上次访问时间更新被禁用时，是否更新上次访问时间 | 启用上次访问时间更新时是否更新上次访问时间 


 a| 
请求检索对象、其访问控制列表或其元数据
 a| 
否
 a| 
是



 a| 
请求更新对象的元数据
 a| 
是
 a| 
是



 a| 
请求将对象从一个存储桶复制到另一个存储桶
 a| 
* 不，对于源副本
* 是的，对于目标副本

 a| 
* 是的，对于源副本
* 是的，对于目标副本




 a| 
请求完成分段上传
 a| 
是的，对于组装好的物体
 a| 
是的，对于组装好的物体

|===