---
permalink: ilm/what-cloud-storage-pool-is.html 
sidebar: sidebar 
keywords: what is a cloud storage pool 
summary: 云存储池允许您使用 ILM 将对象数据移出StorageGRID系统。例如，您可能希望将不经常访问的对象移动到成本较低的云存储，例如 Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud 或 Microsoft Azure Blob 存储中的存档访问层。或者，您可能希望维护StorageGRID对象的云备份以增强灾难恢复。 
---
= 什么是云存储池？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
云存储池允许您使用 ILM 将对象数据移出StorageGRID系统。例如，您可能希望将不经常访问的对象移动到成本较低的云存储，例如 Amazon S3 Glacier、S3 Glacier Deep Archive、Google Cloud 或 Microsoft Azure Blob 存储中的存档访问层。或者，您可能希望维护StorageGRID对象的云备份以增强灾难恢复。

从 ILM 角度来看，云存储池类似于存储池。要将对象存储在任一位置，请在创建 ILM 规则的放置说明时选择池。但是，虽然存储池由StorageGRID系统内的存储节点组成，但云存储池由外部存储桶（S3）或容器（Azure Blob 存储）组成。

该表将存储池与云存储池进行了比较，并展示了高层次的相似之处和不同之处。

[cols="1a,2a,5a"]
|===
|  | 存储池 | 云存储池 


 a| 
它是如何创建的？
 a| 
使用网格管理器中的 *ILM* > *存储池* 选项。
 a| 
使用网格管理器中的 *ILM* > *存储池* > *云存储池* 选项。

您必须先设置外部存储桶或容器，然后才能创建云存储池。



 a| 
您可以创建多少个池？
 a| 
无限。
 a| 
最多 10 个。



 a| 
对象存储在哪里？
 a| 
在StorageGRID内的一个或多个存储节点上。
 a| 
在StorageGRID系统外部的 Amazon S3 存储桶、Azure Blob 存储容器或 Google Cloud 中。

如果云存储池是 Amazon S3 存储桶：

* 您可以选择配置存储桶生命周期，将对象转换为低成本、长期存储，例如 Amazon S3 Glacier 或 S3 Glacier Deep Archive。外部存储系统必须支持 Glacier 存储类和 S3 RestoreObject API。
* 您可以创建云存储池以用于支持 AWS 机密区域的 AWS 商业云服务 (C2S)。


如果云存储池是 Azure Blob 存储容器， StorageGRID会将对象转换到存档层。

*注意：*一般来说，不要为用于云存储池的容器配置 Azure Blob 存储生命周期管理。云存储池中对象的 RestoreObject 操作可能会受到配置的生命周期的影响。



 a| 
什么控制物体的放置？
 a| 
活动 ILM 策略中的 ILM 规则。
 a| 
活动 ILM 策略中的 ILM 规则。



 a| 
使用哪种数据保护方法？
 a| 
复制或擦除编码。
 a| 
复制。



 a| 
每个对象允许有多少个副本？
 a| 
多种的。
 a| 
云存储池中有一个副本，并且（可选） StorageGRID中有一个或多个副本。

*注意：*您不能在任何时候将一个对象存储在多个云存储池中。



 a| 
有什么优势？
 a| 
可以随时快速访问对象。
 a| 
低成本存储。

*注意*： FabricPool数据不能分层到云存储池。

|===