---
permalink: ilm/when-to-use-cloud-storage-pools.html 
sidebar: sidebar 
keywords: use cloud storage pool, benefits of cloud storage pools 
summary: 使用云存储池，您可以将数据备份或分层到外部位置。此外，您还可以将数据备份或分层到多个云。 
---
= 何时使用云存储池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用云存储池，您可以将数据备份或分层到外部位置。此外，您还可以将数据备份或分层到多个云。



== 将StorageGRID数据备份到外部位置

您可以使用云存储池将StorageGRID对象备份到外部位置。

如果StorageGRID中的副本无法访问，则可以使用云存储池中的对象数据来满足客户端请求。但是，您可能需要发出 S3 RestoreObject 请求来访问云存储池中的备份对象副本。

云存储池中的对象数据还可用于恢复由于存储卷或存储节点故障而从StorageGRID丢失的数据。如果对象的唯一剩余副本位于云存储池中， StorageGRID会临时恢复该对象并在恢复的存储节点上创建新副本。

要实施备份解决方案：

. 创建单个云存储池。
. 配置 ILM 规则，同时将对象副本存储在存储节点上（作为复制或擦除编码副本）以及云存储池中的单个对象副本。
. 将规则添加到您的 ILM 策略。然后，模拟并激活该策略。




== 将数据从StorageGRID分层到外部位置

您可以使用云存储池存储StorageGRID系统之外的对象。例如，假设您有大量需要保留的对象，但您预计很少访问这些对象。您可以使用云存储池将对象分层到成本较低的存储并释放StorageGRID中的空间。

要实施分层解决方案：

. 创建单个云存储池。
. 配置 ILM 规则，将很少使用的对象从存储节点移动到云存储池。
. 将规则添加到您的 ILM 策略。然后，模拟并激活该策略。




== 维护多个云端点

如果您想要将对象数据分层或备份到多个云，则可以配置多个云存储池端点。 ILM 规则中的过滤器允许您指定每个云存储池中存储的对象。例如，您可能希望将某些租户或存储桶中的对象存储在 Amazon S3 Glacier 中，并将其他租户或存储桶中的对象存储在 Azure Blob 存储中。或者，您可能希望在 Amazon S3 Glacier 和 Azure Blob 存储之间移动数据。


NOTE: 使用多个云存储池端点时，请记住一个对象一次只能存储在一个云存储池中。

要实现多个云端点：

. 创建最多 10 个云存储池。
. 配置 ILM 规则以在适当的时间将适当的对象数据存储在每个云存储池中。例如，将存储桶 A 中的对象存储在云存储池 A 中，将存储桶 B 中的对象存储在云存储池 B 中。或者，将对象在云存储池 A 中存储一段时间，然后将其移动到云存储池 B。
. 将规则添加到您的 ILM 策略。然后，模拟并激活该策略。

