---
permalink: fabricpool/best-practices-ilm.html 
sidebar: sidebar 
keywords: FabricPool, best practices, ILM, information lifecycle management, ILM rule, ILM policy, erasure-coding, replication 
summary: '如果您使用FabricPool将数据分层到StorageGRID，则必须了解将StorageGRID信息生命周期管理 (ILM) 与FabricPool数据结合使用的要求。' 
---
= 将 ILM 与FabricPool数据结合使用的最佳实践
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用FabricPool将数据分层到StorageGRID，则必须了解将StorageGRID信息生命周期管理 (ILM) 与FabricPool数据结合使用的要求。


CAUTION: FabricPool不了解StorageGRID ILM 规则或策略。如果StorageGRID ILM 策略配置错误，则可能会发生数据丢失。有关详细信息，请参阅link:../ilm/what-ilm-rule-is.html["使用 ILM 规则管理对象"]和link:../ilm/creating-ilm-policy.html["创建 ILM 策略"]。



== ILM 与FabricPool结合使用的指南

当您使用FabricPool设置向导时，该向导会自动为您创建的每个 S3 存储桶创建一个新的 ILM 规则，并将该规则添加到非活动策略中。系统会提示您激活该策略。自动创建的规则遵循推荐的最佳实践：它在单个站点使用 2+1 擦除编码。

如果您手动配置StorageGRID而不是使用FabricPool设置向导，请查看这些指南以确保您的 ILM 规则和 ILM 策略适合FabricPool数据和您的业务需求。您可能需要创建新规则并更新有效的 ILM 策略以满足这些准则。

* 您可以使用复制和擦除编码规则的任意组合来保护云层数据。
+
建议的最佳做法是在站点内使用 2+1 擦除编码，以实现经济高效的数据保护。与复制相比，擦除编码使用更多的 CPU，但提供的存储容量明显较少。 4+1 和 6+1 方案使用的容量比 2+1 方案要少。但是，如果需要在电网扩展期间添加存储节点，4+1 和 6+1 方案的灵活性较差。有关详细信息，请参阅link:../expand/adding-storage-capacity-for-erasure-coded-objects.html["增加擦除编码对象的存储容量"] 。

* 应用于FabricPool数据的每条规则都必须使用擦除编码，或者必须创建至少两个副本。
+

CAUTION: 任何时间段内仅创建一个复制副本的 ILM 规则会使数据面临永久丢失的风险。如果某个对象的副本只有一个，则当存储节点发生故障或出现重大错误时，该对象将会丢失。在升级等维护过程中，您还会暂时失去对该对象的访问权限。

* 如果你需要link:remove-fabricpool-data.html["从StorageGRID中删除FabricPool数据"]，使用ONTAP检索FabricPool卷的所有数据并将其提升到性能层。
+

CAUTION: 为避免数据丢失，请勿使用会过期或删除FabricPool云层数据的 ILM 规则。将每个 ILM 规则中的保留期设置为 *永久*，以确保FabricPool对象不会被StorageGRID ILM 删除。

* 不要创建将FabricPool云层数据从存储桶移出到另一个位置的规则。您不能使用云存储池将FabricPool数据移动到另一个对象存储。
+

NOTE: 不支持将云存储池与FabricPool一起使用，因为从云存储池目标检索对象会增加延迟。

* 从ONTAP 9.8 开始，您可以选择创建对象标签来帮助对分层数据进行分类和排序，以便于管理。例如，您只能在连接到StorageGRID 的FabricPool卷上设置标签。然后，当您在StorageGRID中创建 ILM 规则时，您可以使用对象标记高级过滤器来选择和放置此数据。

