---
permalink: fabricpool/configure-ontap.html 
sidebar: sidebar 
keywords: fabricPool, system manager, ONTAP CLI, add cloud tier 
summary: 获取所需的StorageGRID信息后，您可以转到ONTAP将StorageGRID添加为云层。 
---
= 配置ONTAP系统管理器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
获取所需的StorageGRID信息后，您可以转到ONTAP将StorageGRID添加为云层。

.开始之前
* 如果您完成了FabricPool设置向导，您将拥有 `ONTAP_FabricPool_settings___bucketname__.txt`您下载的文件。
* 如果您手动配置了StorageGRID ，则您拥有用于StorageGRID 的完全限定域名 (FQDN) 或StorageGRID HA 组的虚拟 IP (VIP) 地址、负载均衡器端点的端口号、负载均衡器证书、租户帐户的根用户的访问密钥 ID 和密钥，以及ONTAP将在该租户中使用的存储桶的名称。




== 访问ONTAP系统管理器

这些说明介绍了如何使用ONTAP系统管理器将StorageGRID添加为云层。您可以使用ONTAP CLI 完成相同的配置。有关说明，请访问 https://docs.netapp.com/us-en/ontap/fabricpool/index.html["FabricPool的ONTAP文档"^]。

.步骤
. 访问要分层到StorageGRID 的ONTAP集群的系统管理器。
. 以集群管理员Sign in。
. 导航到 *存储* > *层级* > *添加云层*。
. 从对象存储提供商列表中选择* StorageGRID*。




== 输入StorageGRID值

看 https://docs.netapp.com/us-en/ontap/fabricpool/index.html["FabricPool的ONTAP文档"^]了解更多信息。

.步骤
. 使用以下方式填写添加云层表单 `ONTAP_FabricPool_settings___bucketname__.txt`文件或您手动获取的值。
+
[cols="1a,3a"]
|===
| 字段 | 描述 


 a| 
名称
 a| 
输入此云层的唯一名称。您可以接受默认值。



 a| 
URL 样式
 a| 
如果你link:../admin/configuring-s3-api-endpoint-domain-names.html["配置的 S3 端点域名"]，选择*虚拟托管式 URL*。

*路径样式 URL* 是ONTAP的默认设置，但建议对StorageGRID使用虚拟托管样式请求。如果您为 *服务器名称 (FQDN)* 字段提供 IP 地址而不是域名，则必须使用 *路径样式 URL*。



 a| 
服务器名称 (FQDN)
 a| 
输入您用于StorageGRID 的完全限定域名 (FQDN) 或StorageGRID HA 组的虚拟 IP (VIP) 地址。例如，  `s3.storagegrid.__company__.com` 。

请注意以下事项：

** 您在此处指定的 IP 地址或域名必须与您为StorageGRID负载均衡器端点上传或生成的证书相匹配。
** 如果您提供域名，则 DNS 记录必须映射到您将用于连接到StorageGRID 的每个 IP 地址。看link:configure-dns-server.html["配置 DNS 服务器"] 。




 a| 
SSL
 a| 
已启用（默认）。



 a| 
对象存储证书
 a| 
粘贴用于StorageGRID负载均衡器端点的证书 PEM，包括：
`-----BEGIN CERTIFICATE-----`和 `-----END CERTIFICATE-----`。

*注意：*如果中间 CA 颁发了StorageGRID证书，则必须提供中间 CA 证书。如果StorageGRID证书是由根 CA 直接颁发的，则必须提供根 CA 证书。



 a| 
端口
 a| 
输入StorageGRID负载均衡器端点使用的端口。 ONTAP在连接到StorageGRID时将使用此端口。例如，10433。



 a| 
访问密钥和密钥
 a| 
输入StorageGRID租户帐户的根用户的访问密钥 ID 和秘密访问密钥。

*提示*：如果您将来在StorageGRID中生成新的访问密钥和秘密访问密钥，请先将新密钥输入ONTAP，然后再从StorageGRID中删除旧值。否则， ONTAP可能会暂时失去对StorageGRID的访问权限。



 a| 
容器名称
 a| 
输入您创建的用于此ONTAP层的StorageGRID桶的名称。

|===
. 在ONTAP中完成最终的FabricPool配置。
+
.. 将一个或多个聚合附加到云层。
.. 或者，创建卷分层策略。



