---
permalink: fabricpool/creating-load-balancer-endpoint-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, load balancer, endpoint, load balancing, create, creating, certificate 
summary: StorageGRID使用负载均衡器来管理来自客户端应用程序（例如FabricPool）的工作负载。负载平衡可最大限度地提高多个存储节点的速度和连接容量。 
---
= 为FabricPool创建负载均衡器端点
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID使用负载均衡器来管理来自客户端应用程序（例如FabricPool）的工作负载。负载平衡可最大限度地提高多个存储节点的速度和连接容量。

配置StorageGRID以与FabricPool一起使用时，必须配置负载平衡器端点并上传或生成负载平衡器端点证书，该证书用于保护ONTAP和StorageGRID之间的连接。

要使用FabricPool设置向导完成此任务，请转至link:use-fabricpool-setup-wizard-steps.html["访问并完成FabricPool设置向导"]。

.开始之前
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:../admin/admin-group-permissions.html["Root访问权限"]。
* 您已查看了常规link:../admin/managing-load-balancing.html["负载平衡的注意事项"]以及link:best-practices-for-load-balancing.html["FabricPool负载平衡的最佳实践"]。


.步骤
. 选择 *配置* > *网络* > *负载均衡器端点*。
. 选择“*创建*”。
. 对于*输入端点详细信息*步骤，请填写以下字段。
+
[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
名称
 a| 
端点的描述性名称。



 a| 
端口
 a| 
您想要用于负载平衡的StorageGRID端口。对于您创建的第一个端点，此字段默认为 10433，但您可以输入任何未使用的外部端口。如果输入 80 或 443，则端点仅在网关节点上配置。这些端口在管理节点上保留。

*注意：*不允许使用其他网格服务使用的端口。查看link:../network/internal-grid-node-communications.html["网络端口参考"]。

当您将StorageGRID作为FabricPool云层连接时，您将向ONTAP提供此号码。



 a| 
客户端类型
 a| 
选择*S3*。



 a| 
网络协议
 a| 
选择 *HTTPS*。

*注意*：支持但不建议使用没有 TLS 加密的StorageGRID进行通信。

|===
. 对于*选择绑定模式*步骤，指定绑定模式。绑定模式控制如何使用任意 IP 地址或使用特定 IP 地址和网络接口访问端点。
+
[cols="1a,3a"]
|===
| 模式 | 描述 


 a| 
全局（默认）
 a| 
客户端可以使用任何网关节点或管理节点的 IP 地址、任何网络上任何 HA 组的虚拟 IP (VIP) 地址或相应的 FQDN 访问端点。

除非您需要限制此端点的可访问性，否则请使用*全局*设置（默认）。



 a| 
HA 组的虚拟 IP
 a| 
客户端必须使用 HA 组的虚拟 IP 地址（或相应的 FQDN）来访问此端点。

具有此绑定模式的端点都可以使用相同的端口号，只要您为端点选择的 HA 组不重叠。



 a| 
节点接口
 a| 
客户端必须使用选定节点接口的 IP 地址（或相应的 FQDN）来访问此端点。



 a| 
节点类型
 a| 
根据您选择的节点类型，客户端必须使用任何管理节点的 IP 地址（或相应的 FQDN）或任何网关节点的 IP 地址（或相应的 FQDN）来访问此端点。

|===
. 对于“租户访问”步骤，选择以下选项之一：
+
[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
允许所有租户（默认）
 a| 
所有租户帐户都可以使用此端点访问他们的存储桶。

*允许所有租户*几乎始终是用于FabricPool的负载均衡器端点的适当选项。

如果您尚未创建任何租户帐户，则必须选择此选项。



 a| 
允许选定的租户
 a| 
只有选定的租户帐户可以使用此端点访问其存储桶。



 a| 
阻止选定的租户
 a| 
选定的租户帐户不能使用此端点访问其存储桶。所有其他租户都可以使用此端点。

|===
. 对于*附加证书*步骤，选择以下之一：
+
[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
上传证书（推荐）
 a| 
使用此选项上传 CA 签名的服务器证书、证书私钥和可选的 CA 包。



 a| 
生成证书
 a| 
使用此选项生成自签名证书。看link:../admin/configuring-load-balancer-endpoints.html["配置负载均衡器端点"]了解输入内容的详细信息。



 a| 
使用StorageGRID S3 证书
 a| 
仅当您已上传或生成StorageGRID全局证书的自定义版本时，此选项才可用。看link:../admin/configuring-custom-server-certificate-for-storage-node.html["配置 S3 API 证书"]了解详情。

|===
. 选择“*创建*”。



NOTE: 对端点证书的更改最多可能需要 15 分钟才能应用到所有节点。
