---
permalink: fabricpool/creating-ha-group-for-fabricpool.html 
sidebar: sidebar 
keywords: fabricPool, high availability group, HA group, create, creating, virtual IP, VIP, active interface, backup interface 
summary: '配置StorageGRID以与FabricPool一起使用时，您可以选择创建一个或多个高可用性 (HA) 组。  HA 组是每个包含StorageGRID负载均衡器服务的节点集合。  HA 组可以包含网关节点、管理节点或两者。' 
---
= 为FabricPool创建高可用性 (HA) 组
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置StorageGRID以与FabricPool一起使用时，您可以选择创建一个或多个高可用性 (HA) 组。  HA 组是每个包含StorageGRID负载均衡器服务的节点集合。  HA 组可以包含网关节点、管理节点或两者。

您可以使用 HA 组来帮助保持FabricPool数据连接可用。 HA 组使用虚拟 IP 地址 (VIP) 来提供对负载均衡器服务的高度可用访问。如果 HA 组中的活动接口出现故障，则备用接口可以管理工作负载，而对FabricPool操作的影响很小。

有关此任务的详细信息，请参阅link:../admin/managing-high-availability-groups.html["管理高可用性组"]。要使用FabricPool设置向导完成此任务，请转至link:use-fabricpool-setup-wizard-steps.html["访问并完成FabricPool设置向导"]。

.开始之前
* 您已审阅link:best-practices-for-high-availability-groups.html["高可用性组的最佳实践"]。
* 您已使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 你有link:../admin/admin-group-permissions.html["Root访问权限"]。
* 如果您计划使用 VLAN，则您已经创建了 VLAN 接口。看link:../admin/configure-vlan-interfaces.html["配置VLAN接口"] 。


.步骤
. 选择 *配置* > *网络* > *高可用性组*。
. 选择“*创建*”。
. 对于*输入详细信息*步骤，请填写以下字段。
+
[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
HA组名称
 a| 
此 HA 组的唯一显示名称。



 a| 
描述（可选）
 a| 
该 HA 组的描述。

|===
. 对于*添加接口*步骤，选择您想要在此 HA 组中使用的节点接口。
+
使用列标题对行进行排序，或输入搜索词以更快地找到接口。

+
您可以选择一个或多个节点，但每个节点只能选择一个接口。

. 对于*优先考虑接口*步骤，确定此 HA 组的主接口和任何备份接口。
+
拖动行来更改“优先级顺序”列中的值。

+
列表中的第一个接口是主接口。除非发生故障，否则主接口是活动接口。

+
如果 HA 组包含多个接口并且活动接口出现故障，则虚拟 IP (VIP) 地址将按优先级顺序移动到第一个备份接口。如果该接口出现故障，VIP 地址将移动到下一个备份接口，依此类推。当故障解决后，VIP 地址将移回可用的最高优先级接口。

. 对于*输入 IP 地址*步骤，请填写以下字段。
+
[cols="1a,2a"]
|===
| 字段 | 描述 


 a| 
子网 CIDR
 a| 
CIDR 表示法中的 VIP 子网地址——IPv4 地址后跟斜杠和子网长度（0-32）。

网络地址不得设置任何主机位。例如，  `192.16.0.0/22` 。



 a| 
网关 IP 地址（可选）
 a| 
可选。如果用于访问StorageGRID 的ONTAP IP 地址与StorageGRID VIP 地址不在同一子网中，请输入StorageGRID VIP 本地网关 IP 地址。本地网关IP地址必须在VIP子网内。



 a| 
虚拟 IP 地址
 a| 
为 HA 组中的活动接口输入至少一个、最多十个 VIP 地址。所有 VIP 地址都必须位于 VIP 子网内。

至少一个地址必须是 IPv4。您也可以选择指定其他 IPv4 和 IPv6 地址。

|===
. 选择*创建 HA 组*，然后选择*完成*。

