---
permalink: fabricpool/remove-fabricpool-data.html 
sidebar: sidebar 
keywords: fabricPool, ontap, remove data from storagegrid 
summary: 如果需要删除当前存储在StorageGRID中的FabricPool数据，请按照以下步骤操作。 
---
= 从StorageGRID中删除FabricPool数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果需要删除当前存储在StorageGRID中的FabricPool数据，则必须使用ONTAP检索FabricPool卷的所有数据并将其提升到性能层。

.开始之前
* 您已阅读 https://docs.netapp.com/us-en/ontap/fabricpool/promote-data-performance-tier-task.html["将数据提升至性能层"^]。
* 您正在使用ONTAP 9.8 或更高版本。
* 您正在使用link:../admin/web-browser-requirements.html["支持的网络浏览器"]。
* 您属于具有以下权限的FabricPool租户帐户的StorageGRID用户组：link:../tenant/tenant-management-permissions.html["管理所有 bucket 或 Root 访问权限"] 。


.关于此任务
这些说明解释了如何将数据从StorageGRID移回FabricPool。您可以使用ONTAP和StorageGRID Tenant Manager 执行此过程。

.步骤
. 从ONTAP发出 `volume modify`命令。
+
放 `tiering-policy`到 `none`停止新的分层并设置 `cloud-retrieval-policy`到 `promote`返回之前分层到StorageGRID 的所有数据。

+
看 https://docs.netapp.com/us-en/ontap/fabricpool/promote-all-data-performance-tier-task.html["将FabricPool卷中的所有数据提升到性能层"^]。

. 等待操作完成。
+
您可以使用 `volume object-store`命令 `tiering`选择 https://docs.netapp.com/us-en/ontap/fabricpool/check-status-performance-tier-promotion-task.html["检查性能等级提升的状态"^]。

. 提升操作完成后，请登录到FabricPool租户帐户的StorageGRID租户管理器。
. 从仪表板中选择 *查看存储桶*，或选择 *存储（S3）* > *存储桶*。
. 确认FabricPool存储桶现在为空。
. 如果桶是空的，link:../tenant/deleting-s3-bucket.html["删除存储桶"] 。


.完成后
当您删除存储桶时，从FabricPool到StorageGRID 的分层将无法继续。但是，由于本地层仍连接到StorageGRID云层， ONTAP系统管理器将返回错误消息，指示存储桶无法访问。

要避免出现这些错误消息，请执行以下操作之一：

* 使用FabricPool Mirror 将不同的云层附加到聚合。
* 将数据从FabricPool聚合移动到非FabricPool聚合，然后删除未使用的聚合。


查看 https://docs.netapp.com/us-en/ontap/fabricpool/index.html["FabricPool的ONTAP文档"^]以获取说明。
