---
permalink: fabricpool/use-fabricpool-setup-wizard.html 
sidebar: sidebar 
keywords: fabricPool, FabricPool setup wizard, ontap system manager 
summary: 您可以使用FabricPool设置向导将StorageGRID配置为FabricPool云层的对象存储系统。完成设置向导后，您可以在ONTAP系统管理器中输入所需的详细信息。 
---
= 使用FabricPool设置向导：注意事项和要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用FabricPool设置向导将StorageGRID配置为FabricPool云层的对象存储系统。完成设置向导后，您可以在ONTAP系统管理器中输入所需的详细信息。



== 何时使用FabricPool设置向导

FabricPool设置向导将指导您完成配置StorageGRID以与FabricPool一起使用的每个步骤，并自动为您配置某些实体，例如 ILM 和流量分类策略。作为完成向导的一部分，您将下载一个文件，可以使用该文件将值输入ONTAP系统管理器。使用向导可以更快地配置您的系统并确保您的设置符合StorageGRID和FabricPool最佳实践。

假设您拥有 Root 访问权限，您可以在开始使用StorageGRID Grid Manager 时完成FabricPool设置向导，或者您可以在以后的任何时间访问并完成该向导。根据您的要求，您还可以手动配置部分或全部所需项目，然后使用向导将ONTAP所需的值组合到一个文件中。


TIP: 使用FabricPool设置向导，除非您知道您有特殊要求或您的实施需要大量定制。



== 使用向导之前

确认您已完成这些先决条件步骤。



=== 回顾最佳实践

* 您已大致了解link:information-needed-to-attach-storagegrid-as-cloud-tier.html["将StorageGRID附加为云层所需的信息"]。
* 您已查看了以下FabricPool最佳实践：
+
** link:best-practices-for-high-availability-groups.html["高可用性 (HA) 组"]
** link:best-practices-for-load-balancing.html["负载均衡"]
** link:best-practices-ilm.html["ILM 规则和政策"]






=== 获取 IP 地址并设置 VLAN 接口

如果您要配置 HA 组，您就会知道ONTAP将连接到哪些节点以及将使用哪个StorageGRID网络。您还知道要为子网 CIDR、网关 IP 地址和虚拟 IP (VIP) 地址输入哪些值。

如果您计划使用虚拟 LAN 来隔离FabricPool流量，则您已经配置了 VLAN 接口。看link:../admin/configure-vlan-interfaces.html["配置VLAN接口"] 。



=== 配置身份联合和 SSO

如果您计划对StorageGRID系统使用身份联合或单点登录 (SSO)，则您已启用这些功能。您还知道哪个联合组应该对ONTAP将使用的租户帐户具有 root 访问权限。看link:../admin/using-identity-federation.html["使用身份联合"]和link:../admin/configuring-sso.html["配置单点登录"]。



=== 获取并配置域名

* 您知道要为StorageGRID使用哪个完全限定域名 (FQDN)。域名服务器 (DNS) 条目会将此 FQDN 映射到您使用向导创建的 HA 组的虚拟 IP (VIP) 地址。看link:../fabricpool/configure-dns-server.html["配置 DNS 服务器"] 。
* 如果您计划使用 S3 虚拟托管式请求，则link:../admin/configuring-s3-api-endpoint-domain-names.html["配置的 S3 端点域名"]。  ONTAP默认使用路径样式 URL，但建议使用虚拟托管样式请求。




=== 审查负载均衡器和安全证书要求

如果您计划使用StorageGRID负载均衡器，则您已查看了常规link:../admin/managing-load-balancing.html["负载平衡的注意事项"]。您拥有将要上传的证书或生成证书所需的值。

如果您计划使用外部（第三方）负载均衡器端点，则您拥有该负载均衡器的完全限定域名（FQDN）、端口和证书。



=== 确认 ILM 存储池配置

如果您最初安装了StorageGRID 11.6 或更早版本，则您已经配置了将使用的存储池。一般来说，您应该为用于存储ONTAP数据的每个StorageGRID站点创建一个存储池。


NOTE: 如果您最初安装的是StorageGRID 11.7 或 11.8，则此先决条件不适用。当您最初安装这两个版本中的任何一个时，都会自动为每个站点创建存储池。



== ONTAP与StorageGRID云层之间的关系

FabricPool向导将指导您完成创建单个StorageGRID云层的过程，该云层包括一个StorageGRID租户、一组访问密钥和一个StorageGRID桶。您可以将此StorageGRID云层附加到一个或多个ONTAP本地层。

将单个云层附加到集群中的多个本地层是一般的最佳实践。但是，根据您的要求，您可能希望在单个集群中为本地层使用多个存储桶甚至多个StorageGRID租户。使用不同的存储桶和租户允许您隔离ONTAP本地层之间的数据和数据访问，但配置和管理稍微复杂一些。

NetApp不建议将单个云层附加到多个集群中的本地层。


NOTE: 有关将StorageGRID与NetApp MetroCluster™ 和FabricPool Mirror 结合使用的最佳实践，请参阅 https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["TR-4598： ONTAP中的FabricPool最佳实践"^]。



=== 可选：为每个本地层使用不同的存储桶

要在ONTAP集群中为本地层使用多个存储桶，请在ONTAP中添加多个StorageGRID云层。每个云层共享相同的 HA 组、负载均衡器端点、租户和访问密钥，但使用不同的容器（ StorageGRID桶）。请遵循以下常规步骤：

. 从StorageGRID Grid Manager 完成第一个云层的FabricPool设置向导。
. 从ONTAP系统管理器添加云层并使用从StorageGRID下载的文件提供所需的值。
. 从StorageGRID Tenant Manager 登录到向导创建的租户，并创建第二个存储桶。
. 再次完成FabricPool向导。选择现有的 HA 组、负载均衡器端点和租户。然后，选择您手动创建的新存储桶。为新存储桶创建新的 ILM 规则并激活 ILM 策略以包含该规则。
. 从ONTAP添加第二个云层，但提供新的存储桶名称。




=== 可选：为每个本地层使用不同的租户和存储桶

要对ONTAP集群中的本地层使用多个租户和不同的访问密钥集，请在ONTAP中添加多个StorageGRID云层。每个云层共享相同的 HA 组、负载均衡器端点，但使用不同的租户、访问密钥和容器（ StorageGRID桶）。请遵循以下常规步骤：

. 从StorageGRID Grid Manager 完成第一个云层的FabricPool设置向导。
. 从ONTAP系统管理器添加云层并使用从StorageGRID下载的文件提供所需的值。
. 再次完成FabricPool向导。选择现有的 HA 组和负载均衡器端点。创建新的租户和存储桶。为新存储桶创建新的 ILM 规则并激活 ILM 策略以包含该规则。
. 从ONTAP添加第二个云层，但提供新的访问密钥、密钥和存储桶名称。

